ARTS: WorkspaceMemoryHandler Class Reference
WorkspaceMemoryHandler Class Reference
#include <auto_workspace.h>
Public Member Functions
WorkspaceMemoryHandler ()
Default constructor.
void * allocate (Index wsvg)
Getaway function to call the allocation function for the WSV group with the given Index.
void deallocate (Index wsvg, void *vp)
Getaway function to call the deallocation function for the WSV group with the given Index.
void * duplicate (Index wsvg, void *vp)
Getaway function to call the duplication function for the WSV group with the given Index.
Static Private Member Functions
static void * allocate_wsvg_Any ()
static void deallocate_wsvg_Any (void *vp)
static void * duplicate_wsvg_Any (void *vp)
static void * allocate_wsvg_Index ()
static void deallocate_wsvg_Index (void *vp)
static void * duplicate_wsvg_Index (void *vp)
static void * allocate_wsvg_Numeric ()
static void deallocate_wsvg_Numeric (void *vp)
static void * duplicate_wsvg_Numeric (void *vp)
static void * allocate_wsvg_String ()
static void deallocate_wsvg_String (void *vp)
static void * duplicate_wsvg_String (void *vp)
static void * allocate_wsvg_Vector ()
static void deallocate_wsvg_Vector (void *vp)
static void * duplicate_wsvg_Vector (void *vp)
static void * allocate_wsvg_Matrix ()
static void deallocate_wsvg_Matrix (void *vp)
static void * duplicate_wsvg_Matrix (void *vp)
static void * allocate_wsvg_Sparse ()
static void deallocate_wsvg_Sparse (void *vp)
static void * duplicate_wsvg_Sparse (void *vp)
static void * allocate_wsvg_Tensor3 ()
static void deallocate_wsvg_Tensor3 (void *vp)
static void * duplicate_wsvg_Tensor3 (void *vp)
static void * allocate_wsvg_Tensor4 ()
static void deallocate_wsvg_Tensor4 (void *vp)
static void * duplicate_wsvg_Tensor4 (void *vp)
static void * allocate_wsvg_Tensor5 ()
static void deallocate_wsvg_Tensor5 (void *vp)
static void * duplicate_wsvg_Tensor5 (void *vp)
static void * allocate_wsvg_Tensor6 ()
static void deallocate_wsvg_Tensor6 (void *vp)
static void * duplicate_wsvg_Tensor6 (void *vp)
static void * allocate_wsvg_Tensor7 ()
static void deallocate_wsvg_Tensor7 (void *vp)
static void * duplicate_wsvg_Tensor7 (void *vp)
static void * allocate_wsvg_Timer ()
static void deallocate_wsvg_Timer (void *vp)
static void * duplicate_wsvg_Timer (void *vp)
static void * allocate_wsvg_Verbosity ()
static void deallocate_wsvg_Verbosity (void *vp)
static void * duplicate_wsvg_Verbosity (void *vp)
static void * allocate_wsvg_ArrayOfIndex ()
static void deallocate_wsvg_ArrayOfIndex (void *vp)
static void * duplicate_wsvg_ArrayOfIndex (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfIndex ()
static void deallocate_wsvg_ArrayOfArrayOfIndex (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfIndex (void *vp)
static void * allocate_wsvg_ArrayOfString ()
static void deallocate_wsvg_ArrayOfString (void *vp)
static void * duplicate_wsvg_ArrayOfString (void *vp)
static void * allocate_wsvg_ArrayOfVector ()
static void deallocate_wsvg_ArrayOfVector (void *vp)
static void * duplicate_wsvg_ArrayOfVector (void *vp)
static void * allocate_wsvg_ArrayOfMatrix ()
static void deallocate_wsvg_ArrayOfMatrix (void *vp)
static void * duplicate_wsvg_ArrayOfMatrix (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfMatrix ()
static void deallocate_wsvg_ArrayOfArrayOfMatrix (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfMatrix (void *vp)
static void * allocate_wsvg_ArrayOfSparse ()
static void deallocate_wsvg_ArrayOfSparse (void *vp)
static void * duplicate_wsvg_ArrayOfSparse (void *vp)
static void * allocate_wsvg_ArrayOfTensor3 ()
static void deallocate_wsvg_ArrayOfTensor3 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor3 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfTensor3 ()
static void deallocate_wsvg_ArrayOfArrayOfTensor3 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfTensor3 (void *vp)
static void * allocate_wsvg_ArrayOfTensor4 ()
static void deallocate_wsvg_ArrayOfTensor4 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor4 (void *vp)
static void * allocate_wsvg_ArrayOfTensor6 ()
static void deallocate_wsvg_ArrayOfTensor6 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor6 (void *vp)
static void * allocate_wsvg_ArrayOfTensor7 ()
static void deallocate_wsvg_ArrayOfTensor7 (void *vp)
static void * duplicate_wsvg_ArrayOfTensor7 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfTensor6 ()
static void deallocate_wsvg_ArrayOfArrayOfTensor6 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfTensor6 (void *vp)
static void * allocate_wsvg_ArrayOfLineRecord ()
static void deallocate_wsvg_ArrayOfLineRecord (void *vp)
static void * duplicate_wsvg_ArrayOfLineRecord (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfLineRecord ()
static void deallocate_wsvg_ArrayOfArrayOfLineRecord (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfLineRecord (void *vp)
static void * allocate_wsvg_ArrayOfLineshapeSpec ()
static void deallocate_wsvg_ArrayOfLineshapeSpec (void *vp)
static void * duplicate_wsvg_ArrayOfLineshapeSpec (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfSpeciesTag ()
static void deallocate_wsvg_ArrayOfArrayOfSpeciesTag (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfSpeciesTag (void *vp)
static void * allocate_wsvg_Ppath ()
static void deallocate_wsvg_Ppath (void *vp)
static void * duplicate_wsvg_Ppath (void *vp)
static void * allocate_wsvg_Agenda ()
static void deallocate_wsvg_Agenda (void *vp)
static void * duplicate_wsvg_Agenda (void *vp)
static void * allocate_wsvg_GridPos ()
static void deallocate_wsvg_GridPos (void *vp)
static void * duplicate_wsvg_GridPos (void *vp)
static void * allocate_wsvg_GasAbsLookup ()
static void deallocate_wsvg_GasAbsLookup (void *vp)
static void * duplicate_wsvg_GasAbsLookup (void *vp)
static void * allocate_wsvg_SingleScatteringData ()
static void deallocate_wsvg_SingleScatteringData (void *vp)
static void * duplicate_wsvg_SingleScatteringData (void *vp)
static void * allocate_wsvg_ArrayOfSingleScatteringData ()
static void deallocate_wsvg_ArrayOfSingleScatteringData (void *vp)
static void * duplicate_wsvg_ArrayOfSingleScatteringData (void *vp)
static void * allocate_wsvg_ScatteringMetaData ()
static void deallocate_wsvg_ScatteringMetaData (void *vp)
static void * duplicate_wsvg_ScatteringMetaData (void *vp)
static void * allocate_wsvg_ArrayOfScatteringMetaData ()
static void deallocate_wsvg_ArrayOfScatteringMetaData (void *vp)
static void * duplicate_wsvg_ArrayOfScatteringMetaData (void *vp)
static void * allocate_wsvg_GriddedField1 ()
static void deallocate_wsvg_GriddedField1 (void *vp)
static void * duplicate_wsvg_GriddedField1 (void *vp)
static void * allocate_wsvg_GriddedField2 ()
static void deallocate_wsvg_GriddedField2 (void *vp)
static void * duplicate_wsvg_GriddedField2 (void *vp)
static void * allocate_wsvg_GriddedField3 ()
static void deallocate_wsvg_GriddedField3 (void *vp)
static void * duplicate_wsvg_GriddedField3 (void *vp)
static void * allocate_wsvg_GriddedField4 ()
static void deallocate_wsvg_GriddedField4 (void *vp)
static void * duplicate_wsvg_GriddedField4 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField1 ()
static void deallocate_wsvg_ArrayOfGriddedField1 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField1 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField2 ()
static void deallocate_wsvg_ArrayOfGriddedField2 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField2 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField3 ()
static void deallocate_wsvg_ArrayOfGriddedField3 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField3 (void *vp)
static void * allocate_wsvg_ArrayOfGriddedField4 ()
static void deallocate_wsvg_ArrayOfGriddedField4 (void *vp)
static void * duplicate_wsvg_ArrayOfGriddedField4 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfGriddedField1 ()
static void deallocate_wsvg_ArrayOfArrayOfGriddedField1 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfGriddedField1 (void *vp)
static void * allocate_wsvg_ArrayOfArrayOfGriddedField3 ()
static void deallocate_wsvg_ArrayOfArrayOfGriddedField3 (void *vp)
static void * duplicate_wsvg_ArrayOfArrayOfGriddedField3 (void *vp)
static void * allocate_wsvg_ArrayOfRetrievalQuantity ()
static void deallocate_wsvg_ArrayOfRetrievalQuantity (void *vp)
static void * duplicate_wsvg_ArrayOfRetrievalQuantity (void *vp)
static void * allocate_wsvg_MCAntenna ()
static void deallocate_wsvg_MCAntenna (void *vp)
static void * duplicate_wsvg_MCAntenna (void *vp)
Private Attributes
void *(* allocfp [51])()
void(* deallocfp [51])(void *)
void *(* duplicatefp [51])(void *)
Detailed Description
Definition at line 35 of file auto_workspace.h.
Constructor & Destructor Documentation
WorkspaceMemoryHandler()
WorkspaceMemoryHandler::WorkspaceMemoryHandler () inline
Default constructor.
Initialize allocation and deallocation function pointer lists.
Definition at line 509 of file auto_workspace.h.
References allocate_wsvg_Agenda(), allocate_wsvg_Any(), allocate_wsvg_ArrayOfArrayOfGriddedField1(), allocate_wsvg_ArrayOfArrayOfGriddedField3(), allocate_wsvg_ArrayOfArrayOfIndex(), allocate_wsvg_ArrayOfArrayOfLineRecord(), allocate_wsvg_ArrayOfArrayOfMatrix(), allocate_wsvg_ArrayOfArrayOfSpeciesTag(), allocate_wsvg_ArrayOfArrayOfTensor3(), allocate_wsvg_ArrayOfArrayOfTensor6(), allocate_wsvg_ArrayOfGriddedField1(), allocate_wsvg_ArrayOfGriddedField2(), allocate_wsvg_ArrayOfGriddedField3(), allocate_wsvg_ArrayOfGriddedField4(), allocate_wsvg_ArrayOfIndex(), allocate_wsvg_ArrayOfLineRecord(), allocate_wsvg_ArrayOfLineshapeSpec(), allocate_wsvg_ArrayOfMatrix(), allocate_wsvg_ArrayOfRetrievalQuantity(), allocate_wsvg_ArrayOfScatteringMetaData(), allocate_wsvg_ArrayOfSingleScatteringData(), allocate_wsvg_ArrayOfSparse(), allocate_wsvg_ArrayOfString(), allocate_wsvg_ArrayOfTensor3(), allocate_wsvg_ArrayOfTensor4(), allocate_wsvg_ArrayOfTensor6(), allocate_wsvg_ArrayOfTensor7(), allocate_wsvg_ArrayOfVector(), allocate_wsvg_GasAbsLookup(), allocate_wsvg_GriddedField1(), allocate_wsvg_GriddedField2(), allocate_wsvg_GriddedField3(), allocate_wsvg_GriddedField4(), allocate_wsvg_GridPos(), allocate_wsvg_Index(), allocate_wsvg_Matrix(), allocate_wsvg_MCAntenna(), allocate_wsvg_Numeric(), allocate_wsvg_Ppath(), allocate_wsvg_ScatteringMetaData(), allocate_wsvg_SingleScatteringData(), allocate_wsvg_Sparse(), allocate_wsvg_String(), allocate_wsvg_Tensor3(), allocate_wsvg_Tensor4(), allocate_wsvg_Tensor5(), allocate_wsvg_Tensor6(), allocate_wsvg_Tensor7(), allocate_wsvg_Timer(), allocate_wsvg_Vector(), allocate_wsvg_Verbosity(), allocfp, deallocate_wsvg_Agenda(), deallocate_wsvg_Any(), deallocate_wsvg_ArrayOfArrayOfGriddedField1(), deallocate_wsvg_ArrayOfArrayOfGriddedField3(), deallocate_wsvg_ArrayOfArrayOfIndex(), deallocate_wsvg_ArrayOfArrayOfLineRecord(), deallocate_wsvg_ArrayOfArrayOfMatrix(), deallocate_wsvg_ArrayOfArrayOfSpeciesTag(), deallocate_wsvg_ArrayOfArrayOfTensor3(), deallocate_wsvg_ArrayOfArrayOfTensor6(), deallocate_wsvg_ArrayOfGriddedField1(), deallocate_wsvg_ArrayOfGriddedField2(), deallocate_wsvg_ArrayOfGriddedField3(), deallocate_wsvg_ArrayOfGriddedField4(), deallocate_wsvg_ArrayOfIndex(), deallocate_wsvg_ArrayOfLineRecord(), deallocate_wsvg_ArrayOfLineshapeSpec(), deallocate_wsvg_ArrayOfMatrix(), deallocate_wsvg_ArrayOfRetrievalQuantity(), deallocate_wsvg_ArrayOfScatteringMetaData(), deallocate_wsvg_ArrayOfSingleScatteringData(), deallocate_wsvg_ArrayOfSparse(), deallocate_wsvg_ArrayOfString(), deallocate_wsvg_ArrayOfTensor3(), deallocate_wsvg_ArrayOfTensor4(), deallocate_wsvg_ArrayOfTensor6(), deallocate_wsvg_ArrayOfTensor7(), deallocate_wsvg_ArrayOfVector(), deallocate_wsvg_GasAbsLookup(), deallocate_wsvg_GriddedField1(), deallocate_wsvg_GriddedField2(), deallocate_wsvg_GriddedField3(), deallocate_wsvg_GriddedField4(), deallocate_wsvg_GridPos(), deallocate_wsvg_Index(), deallocate_wsvg_Matrix(), deallocate_wsvg_MCAntenna(), deallocate_wsvg_Numeric(), deallocate_wsvg_Ppath(), deallocate_wsvg_ScatteringMetaData(), deallocate_wsvg_SingleScatteringData(), deallocate_wsvg_Sparse(), deallocate_wsvg_String(), deallocate_wsvg_Tensor3(), deallocate_wsvg_Tensor4(), deallocate_wsvg_Tensor5(), deallocate_wsvg_Tensor6(), deallocate_wsvg_Tensor7(), deallocate_wsvg_Timer(), deallocate_wsvg_Vector(), deallocate_wsvg_Verbosity(), deallocfp, duplicate_wsvg_Agenda(), duplicate_wsvg_Any(), duplicate_wsvg_ArrayOfArrayOfGriddedField1(), duplicate_wsvg_ArrayOfArrayOfGriddedField3(), duplicate_wsvg_ArrayOfArrayOfIndex(), duplicate_wsvg_ArrayOfArrayOfLineRecord(), duplicate_wsvg_ArrayOfArrayOfMatrix(), duplicate_wsvg_ArrayOfArrayOfSpeciesTag(), duplicate_wsvg_ArrayOfArrayOfTensor3(), duplicate_wsvg_ArrayOfArrayOfTensor6(), duplicate_wsvg_ArrayOfGriddedField1(), duplicate_wsvg_ArrayOfGriddedField2(), duplicate_wsvg_ArrayOfGriddedField3(), duplicate_wsvg_ArrayOfGriddedField4(), duplicate_wsvg_ArrayOfIndex(), duplicate_wsvg_ArrayOfLineRecord(), duplicate_wsvg_ArrayOfLineshapeSpec(), duplicate_wsvg_ArrayOfMatrix(), duplicate_wsvg_ArrayOfRetrievalQuantity(), duplicate_wsvg_ArrayOfScatteringMetaData(), duplicate_wsvg_ArrayOfSingleScatteringData(), duplicate_wsvg_ArrayOfSparse(), duplicate_wsvg_ArrayOfString(), duplicate_wsvg_ArrayOfTensor3(), duplicate_wsvg_ArrayOfTensor4(), duplicate_wsvg_ArrayOfTensor6(), duplicate_wsvg_ArrayOfTensor7(), duplicate_wsvg_ArrayOfVector(), duplicate_wsvg_GasAbsLookup(), duplicate_wsvg_GriddedField1(), duplicate_wsvg_GriddedField2(), duplicate_wsvg_GriddedField3(), duplicate_wsvg_GriddedField4(), duplicate_wsvg_GridPos(), duplicate_wsvg_Index(), duplicate_wsvg_Matrix(), duplicate_wsvg_MCAntenna(), duplicate_wsvg_Numeric(), duplicate_wsvg_Ppath(), duplicate_wsvg_ScatteringMetaData(), duplicate_wsvg_SingleScatteringData(), duplicate_wsvg_Sparse(), duplicate_wsvg_String(), duplicate_wsvg_Tensor3(), duplicate_wsvg_Tensor4(), duplicate_wsvg_Tensor5(), duplicate_wsvg_Tensor6(), duplicate_wsvg_Tensor7(), duplicate_wsvg_Timer(), duplicate_wsvg_Vector(), duplicate_wsvg_Verbosity(), and duplicatefp.
Member Function Documentation
allocate()
void* WorkspaceMemoryHandler::allocate (Index wsvg) inline
Getaway function to call the allocation function for the WSV group with the given Index.
Definition at line 669 of file auto_workspace.h.
References allocfp.
Referenced by Workspace::operator[]().
allocate_wsvg_Agenda()
static void* WorkspaceMemoryHandler::allocate_wsvg_Agenda () inline static private
Definition at line 334 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Any()
static void* WorkspaceMemoryHandler::allocate_wsvg_Any () inline static private
Definition at line 46 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfGriddedField1 () inline static private
Definition at line 469 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfGriddedField3 () inline static private
Definition at line 478 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfIndex()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfIndex () inline static private
Definition at line 181 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfLineRecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfLineRecord () inline static private
Definition at line 298 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfMatrix()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfMatrix () inline static private
Definition at line 217 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfSpeciesTag()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfSpeciesTag () inline static private
Definition at line 316 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfTensor3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfTensor3 () inline static private
Definition at line 244 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfArrayOfTensor6()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfArrayOfTensor6 () inline static private
Definition at line 280 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField1 () inline static private
Definition at line 433 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField2()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField2 () inline static private
Definition at line 442 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField3 () inline static private
Definition at line 451 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfGriddedField4()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfGriddedField4 () inline static private
Definition at line 460 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfIndex()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfIndex () inline static private
Definition at line 172 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfLineRecord()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfLineRecord () inline static private
Definition at line 289 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfLineshapeSpec()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfLineshapeSpec () inline static private
Definition at line 307 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfMatrix()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfMatrix () inline static private
Definition at line 208 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfRetrievalQuantity()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfRetrievalQuantity () inline static private
Definition at line 487 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfScatteringMetaData()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfScatteringMetaData () inline static private
Definition at line 388 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfSingleScatteringData()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfSingleScatteringData () inline static private
Definition at line 370 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfSparse()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfSparse () inline static private
Definition at line 226 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfString()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfString () inline static private
Definition at line 190 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor3()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor3 () inline static private
Definition at line 235 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor4()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor4 () inline static private
Definition at line 253 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor6()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor6 () inline static private
Definition at line 262 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfTensor7()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfTensor7 () inline static private
Definition at line 271 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ArrayOfVector()
static void* WorkspaceMemoryHandler::allocate_wsvg_ArrayOfVector () inline static private
Definition at line 199 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GasAbsLookup()
static void* WorkspaceMemoryHandler::allocate_wsvg_GasAbsLookup () inline static private
Definition at line 352 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField1()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField1 () inline static private
Definition at line 397 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField2()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField2 () inline static private
Definition at line 406 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField3()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField3 () inline static private
Definition at line 415 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GriddedField4()
static void* WorkspaceMemoryHandler::allocate_wsvg_GriddedField4 () inline static private
Definition at line 424 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_GridPos()
static void* WorkspaceMemoryHandler::allocate_wsvg_GridPos () inline static private
Definition at line 343 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Index()
static void* WorkspaceMemoryHandler::allocate_wsvg_Index () inline static private
Definition at line 55 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Matrix()
static void* WorkspaceMemoryHandler::allocate_wsvg_Matrix () inline static private
Definition at line 91 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_MCAntenna()
static void* WorkspaceMemoryHandler::allocate_wsvg_MCAntenna () inline static private
Definition at line 496 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Numeric()
static void* WorkspaceMemoryHandler::allocate_wsvg_Numeric () inline static private
Definition at line 64 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Ppath()
static void* WorkspaceMemoryHandler::allocate_wsvg_Ppath () inline static private
Definition at line 325 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_ScatteringMetaData()
static void* WorkspaceMemoryHandler::allocate_wsvg_ScatteringMetaData () inline static private
Definition at line 379 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_SingleScatteringData()
static void* WorkspaceMemoryHandler::allocate_wsvg_SingleScatteringData () inline static private
Definition at line 361 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Sparse()
static void* WorkspaceMemoryHandler::allocate_wsvg_Sparse () inline static private
Definition at line 100 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_String()
static void* WorkspaceMemoryHandler::allocate_wsvg_String () inline static private
Definition at line 73 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor3()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor3 () inline static private
Definition at line 109 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor4()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor4 () inline static private
Definition at line 118 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor5()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor5 () inline static private
Definition at line 127 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor6()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor6 () inline static private
Definition at line 136 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Tensor7()
static void* WorkspaceMemoryHandler::allocate_wsvg_Tensor7 () inline static private
Definition at line 145 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Timer()
static void* WorkspaceMemoryHandler::allocate_wsvg_Timer () inline static private
Definition at line 154 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Vector()
static void* WorkspaceMemoryHandler::allocate_wsvg_Vector () inline static private
Definition at line 82 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
allocate_wsvg_Verbosity()
static void* WorkspaceMemoryHandler::allocate_wsvg_Verbosity () inline static private
Definition at line 163 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate()
void WorkspaceMemoryHandler::deallocate (Index wsvg, void * vp) inline
Getaway function to call the deallocation function for the WSV group with the given Index.
Definition at line 677 of file auto_workspace.h.
References deallocfp.
Referenced by Workspace::del(), Workspace::pop_free(), and Workspace::~Workspace().
deallocate_wsvg_Agenda()
static void WorkspaceMemoryHandler::deallocate_wsvg_Agenda (void * vp) inline static private
Definition at line 337 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Any()
static void WorkspaceMemoryHandler::deallocate_wsvg_Any (void * vp) inline static private
Definition at line 49 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfGriddedField1()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfGriddedField1 (void * vp) inline static private
Definition at line 472 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfGriddedField3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfGriddedField3 (void * vp) inline static private
Definition at line 481 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfIndex()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfIndex (void * vp) inline static private
Definition at line 184 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfLineRecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfLineRecord (void * vp) inline static private
Definition at line 301 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfMatrix()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfMatrix (void * vp) inline static private
Definition at line 220 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfSpeciesTag()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfSpeciesTag (void * vp) inline static private
Definition at line 319 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfTensor3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfTensor3 (void * vp) inline static private
Definition at line 247 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfArrayOfTensor6()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfArrayOfTensor6 (void * vp) inline static private
Definition at line 283 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField1()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField1 (void * vp) inline static private
Definition at line 436 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField2()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField2 (void * vp) inline static private
Definition at line 445 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField3 (void * vp) inline static private
Definition at line 454 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfGriddedField4()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfGriddedField4 (void * vp) inline static private
Definition at line 463 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfIndex()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfIndex (void * vp) inline static private
Definition at line 175 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfLineRecord()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfLineRecord (void * vp) inline static private
Definition at line 292 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfLineshapeSpec()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfLineshapeSpec (void * vp) inline static private
Definition at line 310 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfMatrix()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfMatrix (void * vp) inline static private
Definition at line 211 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfRetrievalQuantity()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfRetrievalQuantity (void * vp) inline static private
Definition at line 490 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfScatteringMetaData()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfScatteringMetaData (void * vp) inline static private
Definition at line 391 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfSingleScatteringData()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfSingleScatteringData (void * vp) inline static private
Definition at line 373 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfSparse()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfSparse (void * vp) inline static private
Definition at line 229 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfString()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfString (void * vp) inline static private
Definition at line 193 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor3()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor3 (void * vp) inline static private
Definition at line 238 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor4()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor4 (void * vp) inline static private
Definition at line 256 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor6()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor6 (void * vp) inline static private
Definition at line 265 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfTensor7()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfTensor7 (void * vp) inline static private
Definition at line 274 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ArrayOfVector()
static void WorkspaceMemoryHandler::deallocate_wsvg_ArrayOfVector (void * vp) inline static private
Definition at line 202 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GasAbsLookup()
static void WorkspaceMemoryHandler::deallocate_wsvg_GasAbsLookup (void * vp) inline static private
Definition at line 355 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField1()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField1 (void * vp) inline static private
Definition at line 400 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField2()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField2 (void * vp) inline static private
Definition at line 409 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField3()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField3 (void * vp) inline static private
Definition at line 418 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GriddedField4()
static void WorkspaceMemoryHandler::deallocate_wsvg_GriddedField4 (void * vp) inline static private
Definition at line 427 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_GridPos()
static void WorkspaceMemoryHandler::deallocate_wsvg_GridPos (void * vp) inline static private
Definition at line 346 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Index()
static void WorkspaceMemoryHandler::deallocate_wsvg_Index (void * vp) inline static private
Definition at line 58 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Matrix()
static void WorkspaceMemoryHandler::deallocate_wsvg_Matrix (void * vp) inline static private
Definition at line 94 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_MCAntenna()
static void WorkspaceMemoryHandler::deallocate_wsvg_MCAntenna (void * vp) inline static private
Definition at line 499 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Numeric()
static void WorkspaceMemoryHandler::deallocate_wsvg_Numeric (void * vp) inline static private
Definition at line 67 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Ppath()
static void WorkspaceMemoryHandler::deallocate_wsvg_Ppath (void * vp) inline static private
Definition at line 328 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_ScatteringMetaData()
static void WorkspaceMemoryHandler::deallocate_wsvg_ScatteringMetaData (void * vp) inline static private
Definition at line 382 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_SingleScatteringData()
static void WorkspaceMemoryHandler::deallocate_wsvg_SingleScatteringData (void * vp) inline static private
Definition at line 364 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Sparse()
static void WorkspaceMemoryHandler::deallocate_wsvg_Sparse (void * vp) inline static private
Definition at line 103 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_String()
static void WorkspaceMemoryHandler::deallocate_wsvg_String (void * vp) inline static private
Definition at line 76 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor3()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor3 (void * vp) inline static private
Definition at line 112 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor4()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor4 (void * vp) inline static private
Definition at line 121 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor5()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor5 (void * vp) inline static private
Definition at line 130 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor6()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor6 (void * vp) inline static private
Definition at line 139 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Tensor7()
static void WorkspaceMemoryHandler::deallocate_wsvg_Tensor7 (void * vp) inline static private
Definition at line 148 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Timer()
static void WorkspaceMemoryHandler::deallocate_wsvg_Timer (void * vp) inline static private
Definition at line 157 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Vector()
static void WorkspaceMemoryHandler::deallocate_wsvg_Vector (void * vp) inline static private
Definition at line 85 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
deallocate_wsvg_Verbosity()
static void WorkspaceMemoryHandler::deallocate_wsvg_Verbosity (void * vp) inline static private
Definition at line 166 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate()
void* WorkspaceMemoryHandler::duplicate (Index wsvg, void * vp) inline
Getaway function to call the duplication function for the WSV group with the given Index.
Definition at line 685 of file auto_workspace.h.
References duplicatefp.
Referenced by Workspace::duplicate().
duplicate_wsvg_Agenda()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Agenda (void * vp) inline static private
Definition at line 340 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Any()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Any (void * vp) inline static private
Definition at line 52 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfGriddedField1 (void * vp) inline static private
Definition at line 475 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfGriddedField3 (void * vp) inline static private
Definition at line 484 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfIndex()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfIndex (void * vp) inline static private
Definition at line 187 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfLineRecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfLineRecord (void * vp) inline static private
Definition at line 304 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfMatrix()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfMatrix (void * vp) inline static private
Definition at line 223 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfSpeciesTag()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfSpeciesTag (void * vp) inline static private
Definition at line 322 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfTensor3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfTensor3 (void * vp) inline static private
Definition at line 250 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfArrayOfTensor6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfArrayOfTensor6 (void * vp) inline static private
Definition at line 286 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField1()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField1 (void * vp) inline static private
Definition at line 439 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField2()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField2 (void * vp) inline static private
Definition at line 448 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField3 (void * vp) inline static private
Definition at line 457 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfGriddedField4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfGriddedField4 (void * vp) inline static private
Definition at line 466 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfIndex()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfIndex (void * vp) inline static private
Definition at line 178 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfLineRecord()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfLineRecord (void * vp) inline static private
Definition at line 295 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfLineshapeSpec()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfLineshapeSpec (void * vp) inline static private
Definition at line 313 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfMatrix()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfMatrix (void * vp) inline static private
Definition at line 214 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfRetrievalQuantity()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfRetrievalQuantity (void * vp) inline static private
Definition at line 493 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfScatteringMetaData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfScatteringMetaData (void * vp) inline static private
Definition at line 394 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfSingleScatteringData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfSingleScatteringData (void * vp) inline static private
Definition at line 376 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfSparse()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfSparse (void * vp) inline static private
Definition at line 232 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfString()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfString (void * vp) inline static private
Definition at line 196 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor3 (void * vp) inline static private
Definition at line 241 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor4 (void * vp) inline static private
Definition at line 259 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor6 (void * vp) inline static private
Definition at line 268 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfTensor7()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfTensor7 (void * vp) inline static private
Definition at line 277 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ArrayOfVector()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ArrayOfVector (void * vp) inline static private
Definition at line 205 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GasAbsLookup()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GasAbsLookup (void * vp) inline static private
Definition at line 358 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField1()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField1 (void * vp) inline static private
Definition at line 403 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField2()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField2 (void * vp) inline static private
Definition at line 412 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField3 (void * vp) inline static private
Definition at line 421 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GriddedField4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GriddedField4 (void * vp) inline static private
Definition at line 430 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_GridPos()
static void* WorkspaceMemoryHandler::duplicate_wsvg_GridPos (void * vp) inline static private
Definition at line 349 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Index()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Index (void * vp) inline static private
Definition at line 61 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Matrix()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Matrix (void * vp) inline static private
Definition at line 97 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_MCAntenna()
static void* WorkspaceMemoryHandler::duplicate_wsvg_MCAntenna (void * vp) inline static private
Definition at line 502 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Numeric()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Numeric (void * vp) inline static private
Definition at line 70 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Ppath()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Ppath (void * vp) inline static private
Definition at line 331 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_ScatteringMetaData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_ScatteringMetaData (void * vp) inline static private
Definition at line 385 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_SingleScatteringData()
static void* WorkspaceMemoryHandler::duplicate_wsvg_SingleScatteringData (void * vp) inline static private
Definition at line 367 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Sparse()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Sparse (void * vp) inline static private
Definition at line 106 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_String()
static void* WorkspaceMemoryHandler::duplicate_wsvg_String (void * vp) inline static private
Definition at line 79 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor3()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor3 (void * vp) inline static private
Definition at line 115 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor4()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor4 (void * vp) inline static private
Definition at line 124 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor5()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor5 (void * vp) inline static private
Definition at line 133 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor6()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor6 (void * vp) inline static private
Definition at line 142 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Tensor7()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Tensor7 (void * vp) inline static private
Definition at line 151 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Timer()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Timer (void * vp) inline static private
Definition at line 160 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Vector()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Vector (void * vp) inline static private
Definition at line 88 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
duplicate_wsvg_Verbosity()
static void* WorkspaceMemoryHandler::duplicate_wsvg_Verbosity (void * vp) inline static private
Definition at line 169 of file auto_workspace.h.
Referenced by WorkspaceMemoryHandler().
Member Data Documentation
allocfp
void*(* WorkspaceMemoryHandler::allocfp[51])() private
Definition at line 38 of file auto_workspace.h.
Referenced by allocate(), and WorkspaceMemoryHandler().
deallocfp
void(* WorkspaceMemoryHandler::deallocfp[51])(void *) private
Definition at line 40 of file auto_workspace.h.
Referenced by deallocate(), and WorkspaceMemoryHandler().
duplicatefp
void*(* WorkspaceMemoryHandler::duplicatefp[51])(void *) private
Definition at line 43 of file auto_workspace.h.
Referenced by duplicate(), and WorkspaceMemoryHandler().
The documentation for this class was generated from the following file:
auto_workspace.h