ARTS: IsotopeRecord Class Reference
IsotopeRecord Class Reference
Contains the lookup data for one isotope.
#include <absorption.h>
Public Member Functions
IsotopeRecord ()
Default constructor.
IsotopeRecord (const IsotopeRecord &x)
Copy constructor.
IsotopeRecord (const String &name, const Numeric &abundance, const Numeric &mass, const Index &mytrantag, const Index &hitrantag, const MakeArray< Index > &jpltags)
Constructor that sets the values.
const String & Name () const
Isotope name.
const Numeric & Abundance () const
Normal abundance (= isotopic ratio).
const Numeric & Mass () const
Mass of the isotope.
const Index & MytranTag () const
MYTRAN2 tag numbers for all isotopes.
const Index & HitranTag () const
HITRAN-96 tag numbers for all isotopes.
const ArrayOfIndex & JplTags () const
JPL tag numbers for all isotopes.
void SetPartitionFctCoeff (const ArrayOfNumeric &qcoeff)
Numeric CalculatePartitionFctRatio (Numeric reference_temperature, Numeric actual_temperature) const
Calculate partition function ratio.
Private Member Functions
Numeric CalculatePartitionFctAtTemp (Numeric temperature) const
Private Attributes
String mname
Numeric mabundance
Numeric mmass
Index mmytrantag
Index mhitrantag
ArrayOfIndex mjpltags
ArrayOfNumeric mqcoeff
Detailed Description
Contains the lookup data for one isotope.
Author
Stefan Buehler
Definition at line 181 of file absorption.h.
Constructor & Destructor Documentation
IsotopeRecord() [1/3]
IsotopeRecord::IsotopeRecord () inline
Default constructor.
Needed by make_array.
Definition at line 185 of file absorption.h.
IsotopeRecord() [2/3]
IsotopeRecord::IsotopeRecord (const IsotopeRecord & x) inline
Copy constructor.
We need this, since operator= does not work correctly for Arrays. (Target Array has to be resized first.)
Definition at line 196 of file absorption.h.
IsotopeRecord() [3/3]
IsotopeRecord::IsotopeRecord (const String & name, const Numeric & abundance, const Numeric & mass, const Index & mytrantag, const Index & hitrantag, const MakeArray< Index > & jpltags) inline
Constructor that sets the values.
Definition at line 207 of file absorption.h.
References mhitrantag, mjpltags, mmytrantag, and Array< base >::nelem().
Member Function Documentation
Abundance()
const Numeric& IsotopeRecord::Abundance () const inline
Normal abundance (= isotopic ratio).
(Absolute number.)
Definition at line 238 of file absorption.h.
References mabundance.
Referenced by xml_write_to_stream(), and xsec_species().
CalculatePartitionFctAtTemp()
Numeric IsotopeRecord::CalculatePartitionFctAtTemp (Numeric temperature) const private
Definition at line 51 of file absorption.cc.
References mqcoeff.
Referenced by CalculatePartitionFctRatio().
CalculatePartitionFctRatio()
Numeric IsotopeRecord::CalculatePartitionFctRatio (Numeric reference_temperature, Numeric actual_temperature) const inline
Calculate partition function ratio.
This computes the partition function ratio Q(Tref)/Q(T).
Unfortunately, we have to recalculate also Q(Tref) for each spectral line, because the reference temperatures can be different!
Parameters
reference_temperature The reference temperature.
actual_temperature The actual temperature.
Returns
The ratio.
Definition at line 269 of file absorption.h.
References CalculatePartitionFctAtTemp(), and mname.
Referenced by xsec_species().
HitranTag()
const Index& IsotopeRecord::HitranTag () const inline
HITRAN-96 tag numbers for all isotopes.
-1 means not included.
Definition at line 245 of file absorption.h.
References mhitrantag.
Referenced by xml_write_to_stream().
JplTags()
const ArrayOfIndex& IsotopeRecord::JplTags () const inline
JPL tag numbers for all isotopes.
Empty array means not included. There can be more than one JPL tag for an isotopic species, because in JPL different vibrational states have different tags.
Definition at line 249 of file absorption.h.
References mjpltags.
Referenced by xml_write_to_stream().
Mass()
const Numeric& IsotopeRecord::Mass () const inline
Mass of the isotope.
(In unified atomic mass units u) If I understand this correctly this is the same as g/mol.
Definition at line 241 of file absorption.h.
References mmass.
Referenced by xml_write_to_stream(), and xsec_species().
MytranTag()
const Index& IsotopeRecord::MytranTag () const inline
MYTRAN2 tag numbers for all isotopes.
-1 means not included.
Definition at line 243 of file absorption.h.
References mmytrantag.
Referenced by xml_write_to_stream().
Name()
const String& IsotopeRecord::Name () const inline
Isotope name.
Definition at line 236 of file absorption.h.
References mname.
Referenced by xml_write_to_stream().
SetPartitionFctCoeff()
void IsotopeRecord::SetPartitionFctCoeff (const ArrayOfNumeric & qcoeff) inline
Definition at line 251 of file absorption.h.
References mqcoeff.
Member Data Documentation
mabundance
Numeric IsotopeRecord::mabundance private
Definition at line 295 of file absorption.h.
Referenced by Abundance().
mhitrantag
Index IsotopeRecord::mhitrantag private
Definition at line 298 of file absorption.h.
Referenced by HitranTag(), and IsotopeRecord().
mjpltags
ArrayOfIndex IsotopeRecord::mjpltags private
Definition at line 299 of file absorption.h.
Referenced by IsotopeRecord(), and JplTags().
mmass
Numeric IsotopeRecord::mmass private
Definition at line 296 of file absorption.h.
Referenced by Mass().
mmytrantag
Index IsotopeRecord::mmytrantag private
Definition at line 297 of file absorption.h.
Referenced by IsotopeRecord(), and MytranTag().
mname
String IsotopeRecord::mname private
Definition at line 294 of file absorption.h.
Referenced by CalculatePartitionFctRatio(), and Name().
mqcoeff
ArrayOfNumeric IsotopeRecord::mqcoeff private
Definition at line 300 of file absorption.h.
Referenced by CalculatePartitionFctAtTemp(), and SetPartitionFctCoeff().
The documentation for this class was generated from the following files:
absorption.h
absorption.cc