ARTS: continua.h File Reference
continua.h File Reference
This header file contains all the declarations of the implemented continua and full absorption (lines+continuum) models.
#include "matpackI.h"
#include "mystring.h"
#include "messages.h"
Functions
void xsec_continuum_tag (MatrixView xsec, const String &name, ConstVectorView parameters, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
Calculates model absorption for one continuum or full model tag.
void check_continuum_model (const String &name)
An auxiliary functions that checks if a given continuum model is listed in species_data.cc.
void MPM87H2OAbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM87H2OAbsModel.
void MPM89H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM89H2OAbsModel.
void MPM93H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93H2OAbsModel.
void PWR98H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
PWR98H2OAbsModel.
void CP98H2OAbsModel (MatrixView xsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CP98H2OAbsModel.
void Pardo_ATM_H2O_ForeignContinuum (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Pardo_ATM_H2O_ForeignContinuum.
void Standard_H2O_self_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Standard_H2O_self_continuum.
void Standard_H2O_foreign_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Standard_H2O_foreign_continuum.
void MaTipping_H2O_foreign_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MaTipping_H2O_foreign_continuum.
void MPM93_H2O_continuum (MatrixView xsec, const Numeric fcenter, const Numeric b1, const Numeric b2, const Numeric b3, const Numeric b4, const Numeric b5, const Numeric b6, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 H2O pseudo continuum line parameters:
void CKD_222_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.2.2 H2O self continuum absorption model.
void CKD_222_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.2.2 H2O foreign continuum absorption model.
void CKD_242_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.4.2 H2O self continuum absorption model.
void CKD24_H20 (MatrixView xsec, int isf, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.4 H2O continuum absorption model.
void CKD_242_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version 2.4.2 H2O foreign continuum absorption model.
void CKD_mt_100_self_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version MT 1.00 H2O self continuum absorption model.
void CKD_mt_100_foreign_h2o (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version MT 1.00 H2O foreign continuum absorption model.
void MPM85O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM85O2AbsModel.
void MPM87O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM87O2AbsModel.
void MPM89O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM89O2AbsModel.
void MPM92O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr)
void MPM93O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93O2AbsModel.
void PWR93O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String &model, const String &version, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
Oxygen complex at 60 GHz plus mm O2 lines plus O2 continuum.
void MPM93_O2_continuum (MatrixView xsec, const Numeric S0in, const Numeric G0in, const Numeric XSOin, const Numeric XG0in, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 O2 continuum:
void Rosenkranz_O2_continuum (MatrixView xsec, const Numeric S0in, const Numeric G0in, const Numeric XSOin, const Numeric XG0in, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
3) O2-air
void CKD_mt_CIAfun_o2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 O2-O2 collision induced absorption (fundamental band)
void CKD_mt_v0v0_o2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity &verbosity)
CKD version MT 1.00 O2 v0<-v0 band absorption.
void CKD_mt_v1v0_o2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 O2 v1<-v0 band absorption.
void CKD_mt_CIArot_n2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (rotational band)
void CKD_mt_CIAfun_n2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (fundamental band)
void BF86_CIA_N2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Borysow-Frommhold 1986 N2-N2 CIA absorption model;.
void MPM93_N2_continuum (MatrixView xsec, const Numeric Cin, const Numeric Gin, const Numeric xTin, const Numeric xfin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity &verbosity)
MPM93 N2 continuum.
void Rosenkranz_N2_self_continuum (MatrixView xsec, const Numeric Cin, const Numeric xin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_N2_self_continuum.
void Standard_N2_self_continuum (MatrixView xsec, const Numeric Cin, const Numeric xfin, const Numeric xtin, const Numeric xpin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
4) N2-N2
void Pardo_ATM_N2_dry_continuum (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_h2o, const Verbosity &verbosity)
Pardo_ATM_N2_dry_continuum.
void CKD_241_co2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version 2.4.1 CO2 continuum absorption model.
void CKD_mt_co2 (MatrixView xsec, const Numeric Cin, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
CKD version MT 1.00 CO2 continuum absorption model.
void Rosenkranz_CO2_self_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_CO2_self_continuum.
void Rosenkranz_CO2_foreign_continuum (MatrixView xsec, const Numeric C, const Numeric x, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity &verbosity)
Rosenkranz_CO2_foreign_continuum.
void MPM93WaterDropletAbs (MatrixView xsec, const Numeric CC, const Numeric CG, const Numeric CE, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93WaterDropletAbs.
void MPM93IceCrystalAbs (MatrixView xsec, const Numeric CC, const Numeric CA, const Numeric CB, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93IceCrystalAbs.
void MPM93RainExt (MatrixView xsec, const Numeric CE, const Numeric CA, const Numeric CB, const String &model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity &verbosity)
MPM93RainExt.
Numeric MPMLineShapeFunction (const Numeric gamma, const Numeric fl, const Numeric f)
Numeric MPMLineShapeO2Function (const Numeric gamma, const Numeric fl, const Numeric f, const Numeric delta)
Numeric WVSatPressureLiquidWater (const Numeric t)
Numeric WVSatPressureIce (const Numeric t)
Variables
const int addF77fields = 1
const Numeric SL296_ckd_0_v1 = -20.0
const Numeric SL296_ckd_0_v2 = 20000.0
const Numeric SL296_ckd_0_dv = 10.0
const int SL296_ckd_0_npt = 2003
const double SL296_ckd_0 [SL296_ckd_0_npt+addF77fields]
const Numeric FH2O_ckd_0_v1 = -20.0
const Numeric FH2O_ckd_0_v2 = 20000.0
const Numeric FH2O_ckd_0_dv = 10.0
const int FH2O_ckd_0_npt = 2003
const double FH2O_ckd_0 [FH2O_ckd_0_npt+addF77fields]
const Numeric SL260_ckd_0_v1 = -20.0
const Numeric SL260_ckd_0_v2 = 20000.0
const Numeric SL260_ckd_0_dv = 10.0
const int SL260_ckd_0_npt = 2003
const double SL260_ckd_0 [SL260_ckd_0_npt+addF77fields]
const Numeric SL296_ckd_mt_100_v1 = -20.0
const Numeric SL296_ckd_mt_100_v2 = 20000.0
const Numeric SL296_ckd_mt_100_dv = 10.0
const int SL296_ckd_mt_100_npt = 2003
const double SL296_ckd_mt_100 [SL296_ckd_mt_100_npt+addF77fields]
const Numeric SL260_ckd_mt_100_v1 = -20.0
const Numeric SL260_ckd_mt_100_v2 = 20000.0
const Numeric SL260_ckd_mt_100_dv = 10.0
const int SL260_ckd_mt_100_npt = 2003
const double SL260_ckd_mt_100 [SL260_ckd_mt_100_npt+addF77fields]
const Numeric FH2O_ckd_mt_100_v1 = -20.0
const Numeric FH2O_ckd_mt_100_v2 = 20000.0
const Numeric FH2O_ckd_mt_100_dv = 10.0
const int FH2O_ckd_mt_100_npt = 2003
const double FH2O_ckd_mt_100 [FH2O_ckd_mt_100_npt+addF77fields]
const Numeric FCO2_ckd_mt_100_v1 = -20.0
const Numeric FCO2_ckd_mt_100_v2 = 10000.0
const Numeric FCO2_ckd_mt_100_dv = 10.0
const int FCO2_ckd_mt_100_npt = 1003
const double FCO2_ckd_mt_100 [FCO2_ckd_mt_100_npt+addF77fields]
const Numeric N2N2_CT296_ckd_mt_100_v1 = -10.0
const Numeric N2N2_CT296_ckd_mt_100_v2 = 350.0
const Numeric N2N2_CT296_ckd_mt_100_dv = 5.0
const int N2N2_CT296_ckd_mt_100_npt = 73
const double N2N2_CT296_ckd_mt_100 [N2N2_CT296_ckd_mt_100_npt+addF77fields]
const Numeric N2N2_CT220_ckd_mt_100_v1 = -10.0
const Numeric N2N2_CT220_ckd_mt_100_v2 = 350.0
const Numeric N2N2_CT220_ckd_mt_100_dv = 5.0
const int N2N2_CT220_ckd_mt_100_npt = 73
const double N2N2_CT220_ckd_mt_100 [N2N2_CT220_ckd_mt_100_npt+addF77fields]
const Numeric N2N2_N2F_ckd_mt_100_v1 = 2085.000
const Numeric N2N2_N2F_ckd_mt_100_v2 = 2670.000
const Numeric N2N2_N2F_ckd_mt_100_dv = 5.000
const int N2N2_N2F_ckd_mt_100_npt = 118
const double N2N2_N2F_ckd_mt_100 [N2N2_N2F_ckd_mt_100_npt+addF77fields]
const double N2N2_N2Ft_ckd_mt_100 [N2N2_N2F_ckd_mt_100_npt+addF77fields]
const Numeric O2O2_O2F_ckd_mt_100_v1 = 1340.000
const Numeric O2O2_O2F_ckd_mt_100_v2 = 1850.000
const Numeric O2O2_O2F_ckd_mt_100_dv = 5.000
const int O2O2_O2F_ckd_mt_100_npt = 103
const double O2O2_O2Fo_ckd_mt_100 [O2O2_O2F_ckd_mt_100_npt+addF77fields]
const double O2O2_O2Ft_ckd_mt_100 [O2O2_O2F_ckd_mt_100_npt+addF77fields]
const Numeric O2_00_ckd_mt_100_v1 = 7536.000e0
const Numeric O2_00_ckd_mt_100_v2 = 8500.000e0
const Numeric O2_00_ckd_mt_100_dv = 2.000e0
const int O2_00_ckd_mt_100_npt = 483
const double O2_00_ckd_mt_100 [O2_00_ckd_mt_100_npt+addF77fields]
const Numeric O2_10_ckd_mt_100_v1 = 9100.000e0
const Numeric O2_10_ckd_mt_100_v2 = 11000.000e0
const Numeric O2_10_ckd_mt_100_dv = 2.000e0
Detailed Description
This header file contains all the declarations of the implemented continua and full absorption (lines+continuum) models.
This is the file from arts-1-0, back-ported to arts-1-1.
Author
Thomas Kuhn
Date
2001-11-05
Definition in file continua.h.
Function Documentation
BF86_CIA_N2()
void BF86_CIA_N2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Borysow-Frommhold 1986 N2-N2 CIA absorption model;.
see publication A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see http://adsabs.harvard.edu/article_service.html for a scanned version of the paper
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-CIA according to BF-86 model [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Note
this "crude" version of the N2-N2 model is a f2c conversion of the N2-N2 F77 code of Prof. A. Borysow. The original code can be downloaded at F77 code.
Remarks
Reference: A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see for a scanned version of the paper.
Author
Thomas Kuhn
Date
2002-03-05
Definition at line 7838 of file continua.cc.
References CREATE_OUT3, n2n2tks_(), ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
check_continuum_model()
void check_continuum_model (const String & name)
An auxiliary functions that checks if a given continuum model is listed in species_data.cc.
This is just in order to verify that this really represents a valid continuum model.
The given name should be something like ‘ContStandardSelf’. The function simply checks if there is a species H2O with an isotope ContStandardSelf.
For user-friendliness, the function also compiles a list of allowed continuum models and gives this as an error message if the model is not found.
The function has no return value, since, if the name does not match a valid model an error is thrown anyway.
Parameters
name The name of the continuum model to check.
Exceptions
runtime_error The model does not exist.
Author
Stefan Buehler
Date
2001-03-12
Definition at line 12872 of file continua.cc.
References species_data.
Referenced by abs_cont_descriptionAppend(), and abs_xsec_per_speciesAddConts().
CKD24_H20()
void CKD24_H20 (MatrixView pxsec, int isf, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.4 H2O continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O continuum according to CKD2.4 [1/m]
isf =0 self continuum, =1 foreign continuum
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
this "crude" version of the CKD2.4 model is a f2c conversion of the F77 code taken out of MonoRTM RT-model written by
S. BOUKABARA, S.A. CLOUGH, and R. HOFFMAN
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421
USA
E-mail: sbouk.nosp@m.aba@.nosp@m.aer.c.nosp@m.om, cloug.nosp@m.h@ae.nosp@m.r.com
Remarks
Reference: A. Borysow and L. Frommhold, The Astrophysical Journal, vol.311, pp.1043-1057, 1986 see for a scanned version of the paper.
Author
Thomas Kuhn
Date
2002-03-06
Definition at line 5182 of file continua.cc.
References artsckd_(), CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
CKD_222_foreign_h2o()
void CKD_222_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.2.2 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKDv.2.2.2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.2.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 2450 of file continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_0, FH2O_ckd_0_dv, FH2O_ckd_0_npt, FH2O_ckd_0_v1, FH2O_ckd_0_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_222_self_h2o()
void CKD_222_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.2.2 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_2_2_2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.2.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-31-10
Definition at line 2162 of file continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SL260_ckd_0, SL260_ckd_0_dv, SL260_ckd_0_npt, SL260_ckd_0_v1, SL260_ckd_0_v2, SL296_ckd_0, SL296_ckd_0_dv, SL296_ckd_0_npt, SL296_ckd_0_v1, SL296_ckd_0_v2, SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_241_co2()
void CKD_241_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version 2.4.1 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.1 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 3671 of file continua.cc.
References addF77fields, CREATE_OUT3, FCO2_ckd_mt_100, FCO2_ckd_mt_100_dv, FCO2_ckd_mt_100_npt, FCO2_ckd_mt_100_v1, FCO2_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_242_foreign_h2o()
void CKD_242_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.4.2 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKDv.2.4.2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 2977 of file continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_0, FH2O_ckd_0_dv, FH2O_ckd_0_npt, FH2O_ckd_0_v1, FH2O_ckd_0_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_242_self_h2o()
void CKD_242_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version 2.4.2 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_2_4_2 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD version 2.4.2 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-30-10
Definition at line 2676 of file continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SL260_ckd_0, SL260_ckd_0_dv, SL260_ckd_0_npt, SL260_ckd_0_v1, SL260_ckd_0_v2, SL296_ckd_0, SL296_ckd_0_dv, SL296_ckd_0_npt, SL296_ckd_0_v1, SL296_ckd_0_v2, SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_100_foreign_h2o()
void CKD_mt_100_foreign_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version MT 1.00 H2O foreign continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O foreign continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 3475 of file continua.cc.
References addF77fields, CREATE_OUT3, FH2O_ckd_mt_100, FH2O_ckd_mt_100_dv, FH2O_ckd_mt_100_npt, FH2O_ckd_mt_100_v1, FH2O_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_100_self_h2o()
void CKD_mt_100_self_h2o (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version MT 1.00 H2O self continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O self continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 3222 of file continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SL260_ckd_mt_100, SL260_ckd_mt_100_dv, SL260_ckd_mt_100_npt, SL260_ckd_mt_100_v1, SL260_ckd_mt_100_v2, SL296_ckd_mt_100, SL296_ckd_mt_100_dv, SL296_ckd_mt_100_npt, SL296_ckd_mt_100_v1, SL296_ckd_mt_100_v2, SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_CIAfun_n2()
void CKD_mt_CIAfun_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (fundamental band)
Model reference: version_1 of the Nitrogen Collision Induced Fundamental Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann, Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling, Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Lafferty, W.J., A.M. Solodov,A. Weber, W.B. Olson and J._M. Hartmann,
Infrared collision-induced absorption by N2 near 4.3 microns for atmospheric applications: Measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996)
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 4323 of file continua.cc.
References addF77fields, CREATE_OUT3, N2N2_N2F_ckd_mt_100, N2N2_N2F_ckd_mt_100_dv, N2N2_N2F_ckd_mt_100_npt, N2N2_N2F_ckd_mt_100_v1, N2N2_N2F_ckd_mt_100_v2, N2N2_N2Ft_ckd_mt_100, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, VMRCalcLimit, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_CIAfun_o2()
void CKD_mt_CIAfun_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 O2-O2 collision induced absorption (fundamental band)
Model reference: F. Thibault, V. Menoux, R. Le Doucen, L. Rosenman, J.-M. Hartmann, Ch. Boulet, "Infrared collision-induced absorption by O2 near 6.4 microns for atmospheric applications: measurements and emprirical modeling", Appl. Optics, 35, 5911-5917, (1996).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-O2 CIA fundamental band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Remarks
F. Thibault, V. Menoux, R. Le Doucen, L. Rosenman, J.-M. Hartmann, Ch. Boulet,
Infrared collision-induced absorption by O2 near 6.4 microns for atmospheric applications: measurements and emprirical modeling,
Appl. Optics, 35, 5911-5917, (1996).
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 4534 of file continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2O2_O2F_ckd_mt_100_dv, O2O2_O2F_ckd_mt_100_npt, O2O2_O2F_ckd_mt_100_v1, O2O2_O2F_ckd_mt_100_v2, O2O2_O2Fo_ckd_mt_100, O2O2_O2Ft_ckd_mt_100, RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_CIArot_n2()
void CKD_mt_CIArot_n2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 N2-N2 collision induced absorption (rotational band)
Model reference: Borysow, A, and L. Frommhold, "Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K", The Astrophysical Journal, 311, 1043-1057, 1986.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-N2 CIA rot. band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio profile [1]
Remarks
Borysow, A, and L. Frommhold,
Collision-induced rototranslational absorption spectra of N2-N2 pairs for temperatures from 50 to 300 K,
The Astrophysical Journal, 311, 1043-1057, 1986.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 4077 of file continua.cc.
References addF77fields, CREATE_OUT3, N2N2_CT220_ckd_mt_100, N2N2_CT220_ckd_mt_100_dv, N2N2_CT220_ckd_mt_100_npt, N2N2_CT220_ckd_mt_100_v1, N2N2_CT220_ckd_mt_100_v2, N2N2_CT296_ckd_mt_100, N2N2_CT296_ckd_mt_100_dv, N2N2_CT296_ckd_mt_100_npt, N2N2_CT296_ckd_mt_100_v1, N2N2_CT296_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_co2()
void CKD_mt_co2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 CO2 continuum absorption model.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2 continuum according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio profile [1]
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 3869 of file continua.cc.
References addF77fields, CREATE_OUT3, FCO2_ckd_mt_100, FCO2_ckd_mt_100_dv, FCO2_ckd_mt_100_npt, FCO2_ckd_mt_100_v1, FCO2_ckd_mt_100_v2, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_v0v0_o2()
void CKD_mt_v0v0_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView abs_n2, const Verbosity & verbosity)
CKD version MT 1.00 O2 v0<-v0 band absorption.
Model reference: CKD_MT 1.00 implementation of oxygen collision induced fundamental model of O2 continuum formulated by Mate et al. over the spectral region 7550-8486 cm-1: B. Mate, C. Lugez, G.T. Fraser, W.J. Lafferty, "Absolute Intensities for the O2 1.27 micron continuum absorption", J. Geophys. Res., 104, 30,585-30,590, 1999.
The units of these continua coefficients are 1 / (amagat_O2*amagat_air)
Also, refer to the paper "Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands", Mlawer, Clough, Brown, Stephen, Landry, Goldman, & Murcray, Journal of Geophysical Research (1997).
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v0<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
abs_n2 N2 volume mixing ratio profile [1]
Remarks
B. Mate, C. Lugez, G.T. Fraser, W.J. Lafferty,
Absolute Intensities for the O2 1.27 micron continuum absorption,
J. Geophys. Res., 104, 30,585-30,590, 1999.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 4754 of file continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2_00_ckd_mt_100, O2_00_ckd_mt_100_dv, O2_00_ckd_mt_100_npt, O2_00_ckd_mt_100_v1, O2_00_ckd_mt_100_v2, RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CKD_mt_v1v0_o2()
void CKD_mt_v1v0_o2 (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CKD version MT 1.00 O2 v1<-v0 band absorption.
Model reference: CKD_MT 1.00 implementation of oxygen v1<-v0 band model of Mlawer, Clough, Brown, Stephen, Landry, Goldman, Murcray, "Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands", Journal of Geophysical Research, vol 103, no. D4, pp. 3859-3863, 1998.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 v1<-v0 band according to CKD_MT 1.00 [1/m]
Cin strength scaling factor [1]
model allows user defined input parameter set (Cin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr O2 volume mixing ratio profile [1]
Remarks
Mlawer, Clough, Brown, Stephen, Landry, Goldman, Murcray,
Observed Atmospheric Collision Induced Absorption in Near Infrared Oxygen Bands,
J. Geophys. Res., 103, D4, 3859-3863, 1998.
Note
This absorption model is taken from the FORTRAN77 code of CKD_MT version 1.00 written by
Atmospheric and Environmental Research Inc. (AER),
Radiation and Climate Group
131 Hartwell Avenue
Lexington, MA 02421, USA
http://www.rtweb.aer.com/continuum_frame.html
Oxygen band absorption model for the ← band system considering the ← transitions.
Author
Thomas Kuhn
Date
2002-28-08
Definition at line 4960 of file continua.cc.
References addF77fields, CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), O2_10_ckd_mt_100_dv, O2_10_ckd_mt_100_v1, O2_10_ckd_mt_100_v2, RADFN_FUN(), SPEED_OF_LIGHT, and XINT_FUN().
Referenced by xsec_continuum_tag().
CP98H2OAbsModel()
void CP98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
CP98H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to Cruz-Pol 1998 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'CruzPol', 'CruzPolLines', 'CruzPolContinuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: S. L. Cruz-Pol et al., Radio Science, 33(5), 1319, 1998.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 1527 of file continua.cc.
References CREATE_OUT3, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MaTipping_H2O_foreign_continuum()
void MaTipping_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MaTipping_H2O_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-dry air continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)]
xin temperature exponent [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'MaTipping', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Q. Ma and R. H. Tipping, J. Chem. Phys., 117(23), 10581, 2002.
Author
Thomas Kuhn
Date
2002-12-04
Definition at line 1907 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
MPM85O2AbsModel()
void MPM85O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM85O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM85', 'MPM85Lines', 'MPM85Continuum', 'MPM85NoCoupling', 'MPM85NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe,
An updated model for millimeter wave propagation in moist air,,
Radio Science, vol. 20, pp. 1069-1089, 1985
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 5621 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM87H2OAbsModel()
void MPM87H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM87H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM87 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the H2O-line strengths [1]
CWin scaling factor for the H2O-line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM87', 'MPM87Lines', 'MPM87Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
H. J. Liebe,
A contribution to modeling atmospheric millimeter-wave properties,
Frequenz, 41, 1987, 31-36
and
H. J. Liebe and D. H. Layton,
Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modeling,
U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences,
325 Broadway, Boulder, CO 80303-3328, report 87224.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 441 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and Pa_to_kPa.
Referenced by xsec_continuum_tag().
MPM87O2AbsModel()
void MPM87O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM87O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM87', 'MPM87Lines', 'MPM87Continuum', 'MPM87NoCoupling', 'MPM87NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and D. H. Layton,
Millimeter-wave properties of the atmosphere: Laboratory studies and propagation modelling,
U.S. Dept. of Commerce, National Telecommunications and Information Administration, Institute for Communication Sciences, rep. 87-224,
325 Broadway, Boulder, CO 80303-3328
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 5906 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM89H2OAbsModel()
void MPM89H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM89H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM89 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM89', 'MPM89Lines', 'MPM89Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe, Int. J. Infrared and Millimeter Waves, 10(6), 1989, 631.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 627 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and Pa_to_kPa.
Referenced by xsec_continuum_tag().
MPM89O2AbsModel()
void MPM89O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM89O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM89 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM89', 'MPM89Lines', 'MPM89Continuum', 'MPM89NoCoupling', 'MPM89NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe,
MPM - an atmospheric millimeter-wave propagation model,
Int. J. Infrared and Mill. Waves, Vol 10, pp. 631-650, 1989.
Author
Thomas Kuhn
Date
2002-04-05
Definition at line 6183 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_kPa, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM92O2AbsModel()
void MPM92O2AbsModel (MatrixView xsec, const Numeric CC, const Numeric CL, const Numeric CW, const Numeric CO, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr)
MPM93_H2O_continuum()
void MPM93_H2O_continuum (MatrixView pxsec, const Numeric fcenter, const Numeric b1, const Numeric b2, const Numeric b3, const Numeric b4, const Numeric b5, const Numeric b6, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 H2O pseudo continuum line parameters:
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O according to MPM87 [1/m]
fcenter continuum pseudo-line center frequency [Hz]
b1 continuum pseudo-line line strength [Hz/Pa]
b2 continuum pseudo-line line strength temperature exponent [1]
b3 continuum pseudo-line line broadening parameter [Hz/Pa]
b4 continuum pseudo-line line broadening parameter [1]
b5 continuum pseudo-line line broadening parameter [1]
b6 continuum pseudo-line line broadening parameter [1]
model allows user defined input parameter set (fcenter and b1 to b6)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters fcenter and b1 to b6 are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 5482 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
MPM93_N2_continuum()
void MPM93_N2_continuum (MatrixView pxsec, const Numeric Cin, const Numeric Gin, const Numeric xTin, const Numeric xfin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 N2 continuum.
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to MPM93 [1/m]
Cin continuum strength [ppm/GHz]
Gin width parameter [Hz/Pa]
xTin continuum strength temperature exponent [1]
xfin continuum frequency exponent [1]
model allows user defined input parameter set (Cin, Gin, xTin, and xfin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr N2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin, Gin, xTin, and xfin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 7964 of file continua.cc.
References CREATE_OUT3, fac(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, and SPEED_OF_LIGHT.
Referenced by xsec_continuum_tag().
MPM93_O2_continuum()
void MPM93_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93 O2 continuum:
see publication side of National Telecommunications and Information Administration http://www.its.bldrdoc.gov/pub/all_pubs/all_pubs.html and ftp side for downloading the MPM93 original source code: ftp://ftp.its.bldrdoc.gov/pub/mpm93/
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to MPM93 [1/m]
S0in O2-continuum strength [1/Pa]
G0in O2-continuum width [Hz/Pa]
XS0in O2-continuum strength temperature exponent [1]
XG0in O2-continuum width temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, xS0in, and xG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, xS0in, and xG0in are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 7393 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), PI, SPEED_OF_LIGHT, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93H2OAbsModel()
void MPM93H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to MPM93 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Attention
The H2O lines at 547.676440 GHz and 552.020960 GHz are isotopic lines:
547 GHz is from the isotope 1-8-1 (HITRAN code 181, JPL code 20003) with an isotopic ratio of 0.00199983 and
552 GHz is from the isotope 1-7-1 (HITRAN code 171, JPL code 19003) with an isotopic ratio of 0.00037200.
The original source code of MPM93 has these isotopic ratios not included in the line strength parameter b1, which is an error.
In the arts implementation the line strength parameter b1 of these two lines is multiplied with the appropriate isotopic ratio.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 1091 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeFunction(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and Pa_to_hPa.
Referenced by xsec_continuum_tag().
MPM93IceCrystalAbs()
void MPM93IceCrystalAbs (MatrixView pxsec, const Numeric CCin, const Numeric CAin, const Numeric CBin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93IceCrystalAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of ice clouds according to MPM93 [1/m]
CCin scaling parameter of the calculated cross section [1]
CAin scaling parameter of the permittivity function a (see page 3-6 in the reference) [1]
CBin scaling parameter of the permittivity function b (see page 3-6 in the reference) [1]
model allows user defined input parameter (CCin, CAin, CBin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile (valid range: 0-0.001) [kg/m]
Note
Except for model 'user' the input parameters CCin, CAin, and CBin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 8807 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
MPM93O2AbsModel()
void MPM93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
MPM93O2AbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to MPM93 [1/m]
CCin scaling factor for the O2-continuum [1]
CLin scaling factor for the O2-line strengths [1]
CWin scaling factor for the O2-line widths [1]
COin scaling factor for the O2-line coupling [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models: 'MPM93', 'MPM93Lines', 'MPM93Continuum', 'MPM93NoCoupling', 'MPM93NoCutoff', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 6726 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, MPMLineShapeO2Function(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
MPM93RainExt()
void MPM93RainExt (MatrixView pxsec, const Numeric CEin, const Numeric CAin, const Numeric CBin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93RainExt.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to MPM93 [1/m]
CEin scaling parameter of the calculated cross section [1]
CAin scaling parameter of the factor a_rain [1]
CBin scaling parameter of the exponent b_rain [1]
model allows user defined input parameter (CEin, CAin, CBin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr rain rate vector (i.e. vertical profile), (valid range: 0-150) [mm/h]
Note
Except for model 'user' the input parameters CEin, CAin, and CBin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: R. L. Olsen and D.V. Rogers and D. B. Hodge,
The aR^b relation in the calculation of rain attenuation,
IEEE Trans. Antennas Propagat., vol. AP-26, pp. 318-329, 1978.
Author
Christian Melsheimer
Date
2003-22-05
Definition at line 8970 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
MPM93WaterDropletAbs()
void MPM93WaterDropletAbs (MatrixView pxsec, const Numeric CCin, const Numeric CGin, const Numeric CEin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
MPM93WaterDropletAbs.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of water clouds according to MPM93 [1/m]
CCin scaling parameter of the calculated cross section [1]
CGin scaling parameter of the first relaxation frequency (gamma_1, see page 3-6 in the reference) [1]
CEin scaling parameter of the first permittivity component (epsilon_0, see page 3-6 in the reference) [1]
model allows user defined input parameter (CCin, CGin, CEin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr suspended water droplet density profile (valid range: 0-0.001) [kg/m]
Note
Except for model 'user' the input parameters CCin, CGin, and CEin are neglected (model dominates over parameters).
Allowed models: 'MPM93' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 8630 of file continua.cc.
References CREATE_OUT3, dB_km_to_1_m, Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
MPMLineShapeFunction()
Numeric MPMLineShapeFunction (const Numeric gamma, const Numeric fl, const Numeric f)
Return values
MPMLineShapeFunction H2O-line shape function value [1/Hz]
Parameters
gamma H2O-line width [Hz]
fl H2O-line central frequency [Hz]
f frequency position of calculation [Hz]
Note
This function calculates the line shape function of Van Vleck and Weisskopf with the factor (f/fl). for the MPM pseudo continuum line.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 9247 of file continua.cc.
Referenced by CP98H2OAbsModel(), MPM02H2OAbsModel(), MPM87H2OAbsModel(), MPM89H2OAbsModel(), MPM93_H2O_continuum(), and MPM93H2OAbsModel().
MPMLineShapeO2Function()
Numeric MPMLineShapeO2Function (const Numeric gamma, const Numeric fl, const Numeric f, const Numeric delta)
Return values
MPMLineShapeO2Function O2-line shape function value [1]
Parameters
gamma O2-line width [Hz]
fl H2O-line central frequency of the [Hz]
f frequency position of calculation [Hz]
delta O2-line mixing parameter [1]
Note
This function calculates the line shape function of Van Vleck and Weisskopf for O2 with line mixing.
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 9304 of file continua.cc.
Referenced by MPM85O2AbsModel(), MPM87O2AbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), and MPM93O2AbsModel().
Pardo_ATM_H2O_ForeignContinuum()
void Pardo_ATM_H2O_ForeignContinuum (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Pardo_ATM_H2O_ForeignContinuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'ATM', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Pardo et al., IEEE, Trans. Ant. Prop.,
Vol 49, No 12, pp. 1683-1694, 2001.
Author
Thomas Kuhn
Date
2001-04-10
Definition at line 5366 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Pardo_ATM_N2_dry_continuum()
void Pardo_ATM_N2_dry_continuum (MatrixView pxsec, const Numeric Cin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, ConstVectorView h2ovmr, const Verbosity & verbosity)
Pardo_ATM_N2_dry_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr N2 volume mixing ratio [1]
h2ovmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'ATM', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: Pardo et al., IEEE, Trans. Ant. Prop.,
Vol 49, No 12, pp. 1683-1694, 2001.
Author
Thomas Kuhn
Date
2001-04-10
Definition at line 8098 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and VMRCalcLimit.
Referenced by xsec_continuum_tag().
PWR93O2AbsModel()
void PWR93O2AbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const Numeric COin, const String & model, const String & version, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmrh2o, ConstVectorView vmr, const Verbosity & verbosity)
Oxygen complex at 60 GHz plus mm O2 lines plus O2 continuum.
REFERENCES FOR EQUATIONS AND COEFFICIENTS: P.W. Rosenkranz, CHAP. 2 and appendix, in ATMOSPHERIC REMOTE SENSING BY MICROWAVE RADIOMETRY (M.A. Janssen, ed., 1993). H.J. Liebe et al, JQSRT V.48, PP.629-643 (1992). M.J. Schwartz, Ph.D. thesis, M.I.T. (1997). SUBMILLIMETER LINE INTENSITIES FROM HITRAN96. This version differs from Liebe's MPM92 in two significant respects:
It uses the modification of the 1- line width temperature dependence recommended by Schwartz: (1/T).
It uses the same temperature dependence (X) for submillimeter line widths as in the 60 GHz band: (1/T)**0.8
history: 05-01-95 P. Rosenkranz 11-05-97 P. Rosenkranz - 1- line modification. 12-16-98 pwr - updated submm freq's and intensities from HITRAN96
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2 according to the P. W. Rosenkranz, 1993 [1/m]
CCin O2-continuum scale factor [1]
CLin O2 line strength scale factor [1]
CWin O2 line broadening scale factor [1]
COin O2 line coupling scale factor [1]
model allows user defined input parameter set (CCin, CLin, CWin, and COin)
or choice of pre-defined parameters of specific models (see note below).
version determines model version: 1988, 1993, 1998
f_grid predefined frequency grid [Hz]
abs_p predefined pressure [Pa]
abs_t predefined temperature grid [K]
vmrh2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters CCin, CLin, CWin, and COin are neglected (model dominates over parameters).
Allowed models:
'Rosenkranz', 'RosenkranzLines', 'RosenkranzContinuum', 'RosenkranzNoCoupling', and 'user'.
For the parameter version the following three string values are allowed: 'PWR88', 'PWR93', 'PWR98'.
See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 7024 of file continua.cc.
References CREATE_OUT3, Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Pa_to_hPa, PI, and VMRCalcLimit.
Referenced by xsec_continuum_tag().
PWR98H2OAbsModel()
void PWR98H2OAbsModel (MatrixView pxsec, const Numeric CCin, const Numeric CLin, const Numeric CWin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
PWR98H2OAbsModel.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of H2O (lines+continuum) according to P. W. Rosenkranz, 1998 [1/m]
CCin scaling factor for the H2O-continuum [1]
CLin scaling factor for the line strengths [1]
CWin scaling factor for the line widths [1]
model allows user defined input parameter set (CCin, CLin, and CWin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters CCin, CLin, and CWin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'RosenkranzLines', 'RosenkranzContinuum', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 1317 of file continua.cc.
References CREATE_OUT3, Hz_to_GHz, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and Pa_to_hPa.
Referenced by xsec_continuum_tag().
Rosenkranz_CO2_foreign_continuum()
void Rosenkranz_CO2_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_CO2_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_n2 N2 volume mixing ratio profile [1]
vmr CO2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 8524 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Rosenkranz_CO2_self_continuum()
void Rosenkranz_CO2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_CO2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of CO2-CO2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)]
xin continuum temperature exponent [1]
model allows user defined input parameter set (Cin and xin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr CO2 volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 8423 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Rosenkranz_N2_self_continuum()
void Rosenkranz_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Rosenkranz_N2_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)]
xin temperature exponent of N2-continuum [1]
model allows user defined input parameter set (Cin and xTin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin and xTin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, pp 74, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 8203 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Rosenkranz_O2_continuum()
void Rosenkranz_O2_continuum (MatrixView pxsec, const Numeric S0in, const Numeric G0in, const Numeric XS0in, const Numeric XG0in, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
3) O2-air
P. W. Rosenkranz Chapter 2, pp 74, in M. A. Janssen, "Atmospheric Remote Sensing by Microwave Radiometry", John Wiley & Sons, Inc., 1993. Also stated in Liebe et al. JQSRT, Vol 48, Nr 5/6, pp. 629-643, 1992. Default continuum parameters are C=1.6E-17*10E-9, x=0.8
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of O2-continuum according to Rosenkranz 1993 [1/m]
S0in line strength [K/(Hz*Pa*m)]
G0in line width [Hz/Pa]
XS0in line strength temperature exponent [1]
XG0in line widths temperature exponent [1]
model allows user defined input parameter set (S0in, G0in, XS0in, and XG0in)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
abs_h2o H2O volume mixing ratio profile [1]
vmr O2 volume mixing ratio profile [1]
Note
Except for model 'user' the input parameters S0in, G0in, XS0in, and XG0in are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz' and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 7541 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Standard_H2O_foreign_continuum()
void Standard_H2O_foreign_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Standard_H2O_foreign_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-dry air continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)]
xin temperature exponent [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_t predefined temperature grid [K]
abs_p predefined pressure [Pa]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'CruzPol', 'MPM89', 'MPM87', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-08-03
Definition at line 1783 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Standard_H2O_self_continuum()
void Standard_H2O_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
Standard_H2O_self_continuum.
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of the H2O-H2O continuum [1/m]
Cin constant absorption strength [1/m / (Hz*Pa)]
xin temperature exponent of (300/T) [1]
model allows user defined input parameter set (C and x)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters C and x are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', 'CruzPol', 'MPM89', 'MPM87', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz., Radio Science, 33(4), 919, 1998 and Radio Science, Vol. 34(4), 1025, 1999.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 1659 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
Standard_N2_self_continuum()
void Standard_N2_self_continuum (MatrixView pxsec, const Numeric Cin, const Numeric xfin, const Numeric xtin, const Numeric xpin, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView vmr, const Verbosity & verbosity)
4) N2-N2
P. W. Rosenkranz Chapter 2, pp 74, in M. A. Janssen, "Atmospheric Remote Sensing by Microwave Radiometry", John Wiley & Sons, Inc., 1993
Parameters
[out] pxsec cross section (absorption/volume mixing ratio) of N2-continuum according to Rosenkranz, 1993 [1/m]
Cin continuum strength [1/m * 1/(Hz*Pa)]
xfin continuum frequency exponent [1]
xtin continuum strength temperature exponent [1]
xpin continuum strength pressure exponent [1]
model allows user defined input parameter set (Cin, xfin, xtin, and xpin)
or choice of pre-defined parameters of specific models (see note below).
f_grid predefined frequency grid [Hz]
abs_p predefined pressure grid [Pa]
abs_t predefined temperature grid [K]
vmr H2O volume mixing ratio [1]
Note
Except for model 'user' the input parameters Cin, xfin, xtin, and xpin are neglected (model dominates over parameters).
Allowed models: 'Rosenkranz', and 'user'. See the user guide for detailed explanations.
Remarks
Reference: P. W. Rosenkranz, Chapter 2, in M. A. Janssen,
Atmospheric Remote Sensing by Microwave Radiometry,
John Wiley & Sons, Inc., 1993.
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 8309 of file continua.cc.
References CREATE_OUT3, ConstMatrixView::ncols(), ConstVectorView::nelem(), and ConstMatrixView::nrows().
Referenced by xsec_continuum_tag().
WVSatPressureIce()
Numeric WVSatPressureIce (const Numeric t)
Return values
WVSatPressureIce water vapor saturation pressure over liquid water [Pa]
Parameters
t temperature [K]
Note
This function calculates the water vapor saturation pressure over ice water according to the Goff-Gratch equation. Other links:
Global Atmospheric Water Balance
Schlatter (profsc.fsl.noaa.gov)
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 9429 of file continua.cc.
WVSatPressureLiquidWater()
Numeric WVSatPressureLiquidWater (const Numeric t)
Return values
WVSatPressureLiquidWater water vapor saturation pressure over liquid water [Pa]
Parameters
t temperature [K]
Note
This function calculates the water vapor saturation pressure over liquid water according to the Goff-Gratch equation.
Other links:
Global Atmospheric Water Balance
Schlatter (profsc.fsl.noaa.gov)
Remarks
Reference: H. J. Liebe and G. A. Hufford and M. G. Cotton,
Propagation modeling of moist air and suspended water/ice particles at frequencies below 1000 GHz,
AGARD 52nd Specialists Meeting of the Electromagnetic Wave Propagation Panel,
Palma de Mallorca, Spain, 1993, May 17-21
Author
Thomas Kuhn
Date
2001-11-05
Definition at line 9364 of file continua.cc.
xsec_continuum_tag()
void xsec_continuum_tag (MatrixView xsec, const String & name, ConstVectorView parameters, const String & model, ConstVectorView f_grid, ConstVectorView abs_p, ConstVectorView abs_t, ConstVectorView abs_n2, ConstVectorView abs_h2o, ConstVectorView vmr, const Verbosity & verbosity)
Calculates model absorption for one continuum or full model tag.
Note, that only one tag can be taken at a time.
Calculated is the true absorption cross section, that means you have to multiply this with n*VMR in order to get the absorption coefficient in units of 1/m.
This is the type of xsec that is used all over ARTS, but not what is used by the internal continuum functions! (We have to divide the output of the internal continuum functions by the number density n.)
Return values
xsec Cross section of one continuum tag,
xsec = alpha / (n*VMR) [m^2]. This is both input and output! (The function adds the continuum absorption cross section to the previous content of xsec.)
Parameters
name The name of the model to calculate (derived from the tag name)
parameters model parameters, as defined in method abs_cont_parameters.
model model, related to model parameters
f_grid Frequency grid [Hz]
abs_p Pressure grid [Pa]
abs_t Temperatures associated with the pressure grid, abs_p [K]
abs_n2 Total volume mixing ratio profile of molecular nitrogen.
This will be needed only for the CO2 foreign continuum [1]
however one is forced to give this input [1]
abs_h2o Total volume mixing ratio profile of water vapor.
This will be needed only for the oxygen continuum
however one is forced to give this input [1]
vmr Volume mixing ratio profile of the actual species [1]
Author
Stefan Buehler, Thomas Kuhn
Date
2001-11-05
Definition at line 9495 of file continua.cc.
References BF86_CIA_N2(), BOLTZMAN_CONST, CKD24_H20(), CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), CKD_mt_v1v0_o2(), CP98H2OAbsModel(), CREATE_OUT3, joker, MaTipping_H2O_foreign_continuum(), MPM85O2AbsModel(), MPM87H2OAbsModel(), MPM87O2AbsModel(), MPM89H2OAbsModel(), MPM89O2AbsModel(), MPM92O2AbsModel(), MPM93_H2O_continuum(), MPM93_N2_continuum(), MPM93_O2_continuum(), MPM93H2OAbsModel(), MPM93IceCrystalAbs(), MPM93O2AbsModel(), MPM93RainExt(), MPM93WaterDropletAbs(), ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), parameters, Pardo_ATM_H2O_ForeignContinuum(), Pardo_ATM_N2_dry_continuum(), PWR93O2AbsModel(), PWR98H2OAbsModel(), Rosenkranz_CO2_foreign_continuum(), Rosenkranz_CO2_self_continuum(), Rosenkranz_N2_self_continuum(), Rosenkranz_O2_continuum(), Standard_H2O_foreign_continuum(), Standard_H2O_self_continuum(), Standard_N2_self_continuum(), and Standard_O2_continuum().
Referenced by abs_xsec_per_speciesAddConts().
Variable Documentation
addF77fields
const int addF77fields = 1
Definition at line 577 of file continua.h.
Referenced by CKD_222_foreign_h2o(), CKD_222_self_h2o(), CKD_241_co2(), CKD_242_foreign_h2o(), CKD_242_self_h2o(), CKD_mt_100_foreign_h2o(), CKD_mt_100_self_h2o(), CKD_mt_CIAfun_n2(), CKD_mt_CIAfun_o2(), CKD_mt_CIArot_n2(), CKD_mt_co2(), CKD_mt_v0v0_o2(), and CKD_mt_v1v0_o2().
FCO2_ckd_mt_100
const double FCO2_ckd_mt_100[FCO2_ckd_mt_100_npt+addF77fields]
Definition at line 3115 of file continua.h.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_dv
const Numeric FCO2_ckd_mt_100_dv = 10.0
Definition at line 3113 of file continua.h.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_npt
const int FCO2_ckd_mt_100_npt = 1003
Definition at line 3114 of file continua.h.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_v1
const Numeric FCO2_ckd_mt_100_v1 = -20.0
Definition at line 3111 of file continua.h.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FCO2_ckd_mt_100_v2
const Numeric FCO2_ckd_mt_100_v2 = 10000.0
Definition at line 3112 of file continua.h.
Referenced by CKD_241_co2(), and CKD_mt_co2().
FH2O_ckd_0
const double FH2O_ckd_0[FH2O_ckd_0_npt+addF77fields]
Definition at line 1018 of file continua.h.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_dv
const Numeric FH2O_ckd_0_dv = 10.0
Definition at line 1016 of file continua.h.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_npt
const int FH2O_ckd_0_npt = 2003
Definition at line 1017 of file continua.h.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_v1
const Numeric FH2O_ckd_0_v1 = -20.0
Definition at line 1014 of file continua.h.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_0_v2
const Numeric FH2O_ckd_0_v2 = 20000.0
Definition at line 1015 of file continua.h.
Referenced by CKD_222_foreign_h2o(), and CKD_242_foreign_h2o().
FH2O_ckd_mt_100
const double FH2O_ckd_mt_100[FH2O_ckd_mt_100_npt+addF77fields]
Definition at line 2704 of file continua.h.
Referenced by CKD_mt_100_foreign_h2o().
FH2O_ckd_mt_100_dv
const Numeric FH2O_ckd_mt_100_dv = 10.0
Definition at line 2702 of file continua.h.
Referenced by CKD_mt_100_foreign_h2o().
FH2O_ckd_mt_100_npt
const int FH2O_ckd_mt_100_npt = 2003
Definition at line 2703 of file continua.h.
Referenced by CKD_mt_100_foreign_h2o().
FH2O_ckd_mt_100_v1
const Numeric FH2O_ckd_mt_100_v1 = -20.0
Definition at line 2700 of file continua.h.
Referenced by CKD_mt_100_foreign_h2o().
FH2O_ckd_mt_100_v2
const Numeric FH2O_ckd_mt_100_v2 = 20000.0
Definition at line 2701 of file continua.h.
Referenced by CKD_mt_100_foreign_h2o().
N2N2_CT220_ckd_mt_100
const double N2N2_CT220_ckd_mt_100[N2N2_CT220_ckd_mt_100_npt+addF77fields]
Initial value:
= {
           0.0000e0,
           0.4946E-06, 0.5756E-06, 0.5964E-06, 0.5756E-06, 0.4946E-06,
           0.4145E-06, 0.3641E-06, 0.3482E-06, 0.3340E-06, 0.3252E-06,
           0.3299E-06, 0.3206E-06, 0.3184E-06, 0.3167E-06, 0.2994E-06,
           0.2943E-06, 0.2794E-06, 0.2582E-06, 0.2468E-06, 0.2237E-06,
           0.2038E-06, 0.1873E-06, 0.1641E-06, 0.1474E-06, 0.1297E-06,
           0.1114E-06, 0.9813E-07, 0.8309E-07, 0.7059E-07, 0.6068E-07,
           0.5008E-07, 0.4221E-07, 0.3537E-07, 0.2885E-07, 0.2407E-07,
           0.1977E-07, 0.1605E-07, 0.1313E-07, 0.1057E-07, 0.8482E-08,
           0.6844E-08, 0.5595E-08, 0.4616E-08, 0.3854E-08, 0.3257E-08,
           0.2757E-08, 0.2372E-08, 0.2039E-08, 0.1767E-08, 0.1548E-08,
           0.1346E-08, 0.1181E-08, 0.1043E-08, 0.9110E-09, 0.8103E-09,
           0.7189E-09, 0.6314E-09, 0.5635E-09, 0.4976E-09, 0.4401E-09,
           0.3926E-09, 0.3477E-09, 0.3085E-09, 0.2745E-09, 0.2416E-09,
           0.2155E-09, 0.1895E-09, 0.1678E-09, 0.1493E-09, 0.1310E-09,
           0.1154E-09, 0.1019E-09, 0.8855E-10}
Definition at line 3360 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_dv
const Numeric N2N2_CT220_ckd_mt_100_dv = 5.0
Definition at line 3358 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_npt
const int N2N2_CT220_ckd_mt_100_npt = 73
Definition at line 3359 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_v1
const Numeric N2N2_CT220_ckd_mt_100_v1 = -10.0
Definition at line 3356 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT220_ckd_mt_100_v2
const Numeric N2N2_CT220_ckd_mt_100_v2 = 350.0
Definition at line 3357 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100
const double N2N2_CT296_ckd_mt_100[N2N2_CT296_ckd_mt_100_npt+addF77fields]
Initial value:
= {
           0.0000e0,
           0.4303E-06, 0.4850E-06, 0.4979E-06, 0.4850E-06, 0.4303E-06,
           0.3715E-06, 0.3292E-06, 0.3086E-06, 0.2920E-06, 0.2813E-06,
           0.2804E-06, 0.2738E-06, 0.2726E-06, 0.2724E-06, 0.2635E-06,
           0.2621E-06, 0.2547E-06, 0.2428E-06, 0.2371E-06, 0.2228E-06,
           0.2100E-06, 0.1991E-06, 0.1822E-06, 0.1697E-06, 0.1555E-06,
           0.1398E-06, 0.1281E-06, 0.1138E-06, 0.1012E-06, 0.9078E-07,
           0.7879E-07, 0.6944E-07, 0.6084E-07, 0.5207E-07, 0.4540E-07,
           0.3897E-07, 0.3313E-07, 0.2852E-07, 0.2413E-07, 0.2045E-07,
           0.1737E-07, 0.1458E-07, 0.1231E-07, 0.1031E-07, 0.8586E-08,
           0.7162E-08, 0.5963E-08, 0.4999E-08, 0.4226E-08, 0.3607E-08,
           0.3090E-08, 0.2669E-08, 0.2325E-08, 0.2024E-08, 0.1783E-08,
           0.1574E-08, 0.1387E-08, 0.1236E-08, 0.1098E-08, 0.9777E-09,
           0.8765E-09, 0.7833E-09, 0.7022E-09, 0.6317E-09, 0.5650E-09,
           0.5100E-09, 0.4572E-09, 0.4115E-09, 0.3721E-09, 0.3339E-09,
           0.3005E-09, 0.2715E-09, 0.2428E-09}
Definition at line 3330 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_dv
const Numeric N2N2_CT296_ckd_mt_100_dv = 5.0
Definition at line 3328 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_npt
const int N2N2_CT296_ckd_mt_100_npt = 73
Definition at line 3329 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_v1
const Numeric N2N2_CT296_ckd_mt_100_v1 = -10.0
Definition at line 3326 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_CT296_ckd_mt_100_v2
const Numeric N2N2_CT296_ckd_mt_100_v2 = 350.0
Definition at line 3327 of file continua.h.
Referenced by CKD_mt_CIArot_n2().
N2N2_N2F_ckd_mt_100
const double N2N2_N2F_ckd_mt_100[N2N2_N2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
            0.000E+00,
            0.000E+00,  2.000E-10,  5.200E-09,  1.020E-08,  1.520E-08,
            2.020E-08,  2.520E-08,  3.020E-08,  4.450E-08,  5.220E-08,
            6.460E-08,  7.750E-08,  9.030E-08,  1.060E-07,  1.210E-07,
            1.370E-07,  1.570E-07,  1.750E-07,  2.010E-07,  2.300E-07,
            2.590E-07,  2.950E-07,  3.260E-07,  3.660E-07,  4.050E-07,
            4.470E-07,  4.920E-07,  5.340E-07,  5.840E-07,  6.240E-07,
            6.670E-07,  7.140E-07,  7.260E-07,  7.540E-07,  7.840E-07,
            8.090E-07,  8.420E-07,  8.620E-07,  8.870E-07,  9.110E-07,
            9.360E-07,  9.760E-07,  1.030E-06,  1.110E-06,  1.230E-06,
            1.390E-06,  1.610E-06,  1.760E-06,  1.940E-06,  1.970E-06,
            1.870E-06,  1.750E-06,  1.560E-06,  1.420E-06,  1.350E-06,
            1.320E-06,  1.290E-06,  1.290E-06,  1.290E-06,  1.300E-06,
            1.320E-06,  1.330E-06,  1.340E-06,  1.350E-06,  1.330E-06,
            1.310E-06,  1.290E-06,  1.240E-06,  1.200E-06,  1.160E-06,
            1.100E-06,  1.040E-06,  9.960E-07,  9.380E-07,  8.630E-07,
            7.980E-07,  7.260E-07,  6.550E-07,  5.940E-07,  5.350E-07,
            4.740E-07,  4.240E-07,  3.770E-07,  3.330E-07,  2.960E-07,
            2.630E-07,  2.340E-07,  2.080E-07,  1.850E-07,  1.670E-07,
            1.470E-07,  1.320E-07,  1.200E-07,  1.090E-07,  9.850E-08,
            9.080E-08,  8.180E-08,  7.560E-08,  6.850E-08,  6.140E-08,
            5.830E-08,  5.770E-08,  5.000E-08,  4.320E-08,  3.140E-08,
            2.890E-08,  2.640E-08,  2.390E-08,  2.140E-08,  1.890E-08,
            1.640E-08,  1.390E-08,  1.140E-08,  8.900E-09,  6.400E-09,
            3.900E-09,  1.400E-09,  0.000E+00}
Definition at line 3388 of file continua.h.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_dv
const Numeric N2N2_N2F_ckd_mt_100_dv = 5.000
Definition at line 3386 of file continua.h.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_npt
const int N2N2_N2F_ckd_mt_100_npt = 118
Definition at line 3387 of file continua.h.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_v1
const Numeric N2N2_N2F_ckd_mt_100_v1 = 2085.000
Definition at line 3384 of file continua.h.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2F_ckd_mt_100_v2
const Numeric N2N2_N2F_ckd_mt_100_v2 = 2670.000
Definition at line 3385 of file continua.h.
Referenced by CKD_mt_CIAfun_n2().
N2N2_N2Ft_ckd_mt_100
const double N2N2_N2Ft_ckd_mt_100[N2N2_N2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
            0.000E+00,
            1.040E+03,  1.010E+03,  9.800E+02,  9.500E+02,  9.200E+02,
            8.900E+02,  8.600E+02,  8.300E+02,  8.020E+02,  7.610E+02,
            7.220E+02,  6.790E+02,  6.460E+02,  6.090E+02,  5.620E+02,
            5.110E+02,  4.720E+02,  4.360E+02,  4.060E+02,  3.770E+02,
            3.550E+02,  3.380E+02,  3.190E+02,  2.990E+02,  2.780E+02,
            2.550E+02,  2.330E+02,  2.080E+02,  1.840E+02,  1.490E+02,
            1.070E+02,  6.600E+01,  2.500E+01, -1.300E+01, -4.900E+01,
           -8.200E+01, -1.040E+02, -1.190E+02, -1.300E+02, -1.390E+02,
           -1.440E+02, -1.460E+02, -1.460E+02, -1.470E+02, -1.480E+02,
           -1.500E+02, -1.530E+02, -1.600E+02, -1.690E+02, -1.810E+02,
           -1.890E+02, -1.950E+02, -2.000E+02, -2.050E+02, -2.090E+02,
           -2.110E+02, -2.100E+02, -2.100E+02, -2.090E+02, -2.050E+02,
           -1.990E+02, -1.900E+02, -1.800E+02, -1.680E+02, -1.570E+02,
           -1.430E+02, -1.260E+02, -1.080E+02, -8.900E+01, -6.300E+01,
           -3.200E+01,  1.000E+00,  3.500E+01,  6.500E+01,  9.500E+01,
            1.210E+02,  1.410E+02,  1.520E+02,  1.610E+02,  1.640E+02,
            1.640E+02,  1.610E+02,  1.550E+02,  1.480E+02,  1.430E+02,
            1.370E+02,  1.330E+02,  1.310E+02,  1.330E+02,  1.390E+02,
            1.500E+02,  1.650E+02,  1.870E+02,  2.130E+02,  2.480E+02,
            2.840E+02,  3.210E+02,  3.720E+02,  4.490E+02,  5.140E+02,
            5.690E+02,  6.090E+02,  6.420E+02,  6.730E+02,  7.000E+02,
            7.300E+02,  7.600E+02,  7.900E+02,  8.200E+02,  8.500E+02,
            8.800E+02,  9.100E+02,  9.400E+02,  9.700E+02,  1.000E+03,
            1.030E+03,  1.060E+03,  1.090E+03}
Definition at line 3416 of file continua.h.
Referenced by CKD_mt_CIAfun_n2().
O2_00_ckd_mt_100
const double O2_00_ckd_mt_100[O2_00_ckd_mt_100_npt+addF77fields]
Definition at line 3523 of file continua.h.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_dv
const Numeric O2_00_ckd_mt_100_dv = 2.000e0
Definition at line 3521 of file continua.h.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_npt
const int O2_00_ckd_mt_100_npt = 483
Definition at line 3522 of file continua.h.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_v1
const Numeric O2_00_ckd_mt_100_v1 = 7536.000e0
Definition at line 3519 of file continua.h.
Referenced by CKD_mt_v0v0_o2().
O2_00_ckd_mt_100_v2
const Numeric O2_00_ckd_mt_100_v2 = 8500.000e0
Definition at line 3520 of file continua.h.
Referenced by CKD_mt_v0v0_o2().
O2_10_ckd_mt_100_dv
const Numeric O2_10_ckd_mt_100_dv = 2.000e0
Definition at line 3640 of file continua.h.
Referenced by CKD_mt_v1v0_o2().
O2_10_ckd_mt_100_v1
const Numeric O2_10_ckd_mt_100_v1 = 9100.000e0
Definition at line 3638 of file continua.h.
Referenced by CKD_mt_v1v0_o2().
O2_10_ckd_mt_100_v2
const Numeric O2_10_ckd_mt_100_v2 = 11000.000e0
Definition at line 3639 of file continua.h.
Referenced by CKD_mt_v1v0_o2().
O2O2_O2F_ckd_mt_100_dv
const Numeric O2O2_O2F_ckd_mt_100_dv = 5.000
Definition at line 3452 of file continua.h.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2F_ckd_mt_100_npt
const int O2O2_O2F_ckd_mt_100_npt = 103
Definition at line 3453 of file continua.h.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2F_ckd_mt_100_v1
const Numeric O2O2_O2F_ckd_mt_100_v1 = 1340.000
Definition at line 3450 of file continua.h.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2F_ckd_mt_100_v2
const Numeric O2O2_O2F_ckd_mt_100_v2 = 1850.000
Definition at line 3451 of file continua.h.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2Fo_ckd_mt_100
const double O2O2_O2Fo_ckd_mt_100[O2O2_O2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
            0.000E+00,
            0.000E+00,  9.744E-09,  2.256E-08,  3.538E-08,  4.820E-08,
            6.100E-08,  7.400E-08,  8.400E-08,  9.600E-08,  1.200E-07,
            1.620E-07,  2.080E-07,  2.460E-07,  2.850E-07,  3.140E-07,
            3.800E-07,  4.440E-07,  5.000E-07,  5.710E-07,  6.730E-07,
            7.680E-07,  8.530E-07,  9.660E-07,  1.100E-06,  1.210E-06,
            1.330E-06,  1.470E-06,  1.590E-06,  1.690E-06,  1.800E-06,
            1.920E-06,  2.040E-06,  2.150E-06,  2.260E-06,  2.370E-06,
            2.510E-06,  2.670E-06,  2.850E-06,  3.070E-06,  3.420E-06,
            3.830E-06,  4.200E-06,  4.450E-06,  4.600E-06,  4.530E-06,
            4.280E-06,  3.960E-06,  3.680E-06,  3.480E-06,  3.350E-06,
            3.290E-06,  3.250E-06,  3.230E-06,  3.230E-06,  3.210E-06,
            3.190E-06,  3.110E-06,  3.030E-06,  2.910E-06,  2.800E-06,
            2.650E-06,  2.510E-06,  2.320E-06,  2.130E-06,  1.930E-06,
            1.760E-06,  1.590E-06,  1.420E-06,  1.250E-06,  1.110E-06,
            9.900E-07,  8.880E-07,  7.910E-07,  6.780E-07,  5.870E-07,
            5.240E-07,  4.640E-07,  4.030E-07,  3.570E-07,  3.200E-07,
            2.900E-07,  2.670E-07,  2.420E-07,  2.150E-07,  1.820E-07,
            1.600E-07,  1.460E-07,  1.280E-07,  1.030E-07,  8.700E-08,
            8.100E-08,  7.100E-08,  6.400E-08,  5.807E-08,  5.139E-08,
            4.496E-08,  3.854E-08,  3.212E-08,  2.569E-08,  1.927E-08,
            1.285E-08,  6.423E-09,  0.000E+00}
Definition at line 3454 of file continua.h.
Referenced by CKD_mt_CIAfun_o2().
O2O2_O2Ft_ckd_mt_100
const double O2O2_O2Ft_ckd_mt_100[O2O2_O2F_ckd_mt_100_npt+addF77fields]
Initial value:
= {
            0.000E+00,
            4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,
            4.670E+02,  4.000E+02,  3.150E+02,  3.790E+02,  3.680E+02,
            4.750E+02,  5.210E+02,  5.310E+02,  5.120E+02,  4.420E+02,
            4.440E+02,  4.300E+02,  3.810E+02,  3.350E+02,  3.240E+02,
            2.960E+02,  2.480E+02,  2.150E+02,  1.930E+02,  1.580E+02,
            1.270E+02,  1.010E+02,  7.100E+01,  3.100E+01, -6.000E+00,
           -2.600E+01, -4.700E+01, -6.300E+01, -7.900E+01, -8.800E+01,
           -8.800E+01, -8.700E+01, -9.000E+01, -9.800E+01, -9.900E+01,
           -1.090E+02, -1.340E+02, -1.600E+02, -1.670E+02, -1.640E+02,
           -1.580E+02, -1.530E+02, -1.510E+02, -1.560E+02, -1.660E+02,
           -1.680E+02, -1.730E+02, -1.700E+02, -1.610E+02, -1.450E+02,
           -1.260E+02, -1.080E+02, -8.400E+01, -5.900E+01, -2.900E+01,
            4.000E+00,  4.100E+01,  7.300E+01,  9.700E+01,  1.230E+02,
            1.590E+02,  1.980E+02,  2.200E+02,  2.420E+02,  2.560E+02,
            2.810E+02,  3.110E+02,  3.340E+02,  3.190E+02,  3.130E+02,
            3.210E+02,  3.230E+02,  3.100E+02,  3.150E+02,  3.200E+02,
            3.350E+02,  3.610E+02,  3.780E+02,  3.730E+02,  3.380E+02,
            3.190E+02,  3.460E+02,  3.220E+02,  2.910E+02,  2.900E+02,
            3.500E+02,  3.710E+02,  5.040E+02,  4.000E+02,  4.000E+02,
            4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,  4.000E+02,
            4.000E+02,  4.000E+02,  4.000E+02}
Definition at line 3478 of file continua.h.
Referenced by CKD_mt_CIAfun_o2().
SL260_ckd_0
const double SL260_ckd_0[SL260_ckd_0_npt+addF77fields]
Definition at line 1434 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_dv
const Numeric SL260_ckd_0_dv = 10.0
Definition at line 1432 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_npt
const int SL260_ckd_0_npt = 2003
Definition at line 1433 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_v1
const Numeric SL260_ckd_0_v1 = -20.0
Definition at line 1430 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_0_v2
const Numeric SL260_ckd_0_v2 = 20000.0
Definition at line 1431 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL260_ckd_mt_100
const double SL260_ckd_mt_100[SL260_ckd_mt_100_npt+addF77fields]
Definition at line 2292 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL260_ckd_mt_100_dv
const Numeric SL260_ckd_mt_100_dv = 10.0
Definition at line 2290 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL260_ckd_mt_100_npt
const int SL260_ckd_mt_100_npt = 2003
Definition at line 2291 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL260_ckd_mt_100_v1
const Numeric SL260_ckd_mt_100_v1 = -20.0
Definition at line 2288 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL260_ckd_mt_100_v2
const Numeric SL260_ckd_mt_100_v2 = 20000.0
Definition at line 2289 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL296_ckd_0
const double SL296_ckd_0[SL296_ckd_0_npt+addF77fields]
Definition at line 605 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_dv
const Numeric SL296_ckd_0_dv = 10.0
Definition at line 603 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_npt
const int SL296_ckd_0_npt = 2003
Definition at line 604 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_v1
const Numeric SL296_ckd_0_v1 = -20.0
Definition at line 601 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_0_v2
const Numeric SL296_ckd_0_v2 = 20000.0
Definition at line 602 of file continua.h.
Referenced by CKD_222_self_h2o(), and CKD_242_self_h2o().
SL296_ckd_mt_100
const double SL296_ckd_mt_100[SL296_ckd_mt_100_npt+addF77fields]
Definition at line 1881 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL296_ckd_mt_100_dv
const Numeric SL296_ckd_mt_100_dv = 10.0
Definition at line 1879 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL296_ckd_mt_100_npt
const int SL296_ckd_mt_100_npt = 2003
Definition at line 1880 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL296_ckd_mt_100_v1
const Numeric SL296_ckd_mt_100_v1 = -20.0
Definition at line 1877 of file continua.h.
Referenced by CKD_mt_100_self_h2o().
SL296_ckd_mt_100_v2
const Numeric SL296_ckd_mt_100_v2 = 20000.0
Definition at line 1878 of file continua.h.
Referenced by CKD_mt_100_self_h2o().