ARTS: describe.cc File Reference
describe.cc File Reference
Describe type and dimensions of a tensor view.
#include "describe.h"
Functions
string describe (ConstTensor7View x)
Describe Tensor7.
string describe (ConstTensor6View x)
Describe Tensor6.
string describe (ConstTensor5View x)
Describe Tensor5.
string describe (ConstTensor4View x)
Describe Tensor4.
string describe (ConstTensor3View x)
Describe Tensor3.
string describe (ConstMatrixView x)
Describe Matrix.
string describe (ConstVectorView x)
Describe Vector.
string describe (const Numeric &x)
Describe Scalar.
Detailed Description
Describe type and dimensions of a tensor view.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Tue Feb 25 15:35:56 2003
This file contains a set of helper functions called describe, which you can use to output the dimensions of a tensor. This is just for testing purposes.
Definition in file describe.cc.
Function Documentation
describe() [1/8]
string describe (const Numeric & x)
Describe Scalar.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 141 of file describe.cc.
describe() [2/8]
string describe (ConstMatrixView x)
Describe Matrix.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 116 of file describe.cc.
References ConstMatrixView::ncols(), and ConstMatrixView::nrows().
describe() [3/8]
string describe (ConstTensor3View x)
Describe Tensor3.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 102 of file describe.cc.
References ConstTensor3View::ncols(), ConstTensor3View::npages(), and ConstTensor3View::nrows().
describe() [4/8]
string describe (ConstTensor4View x)
Describe Tensor4.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 87 of file describe.cc.
References ConstTensor4View::nbooks(), ConstTensor4View::ncols(), ConstTensor4View::npages(), and ConstTensor4View::nrows().
describe() [5/8]
string describe (ConstTensor5View x)
Describe Tensor5.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 71 of file describe.cc.
References ConstTensor5View::nbooks(), ConstTensor5View::ncols(), ConstTensor5View::npages(), ConstTensor5View::nrows(), and ConstTensor5View::nshelves().
describe() [6/8]
string describe (ConstTensor6View x)
Describe Tensor6.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 54 of file describe.cc.
References ConstTensor6View::nbooks(), ConstTensor6View::ncols(), ConstTensor6View::npages(), ConstTensor6View::nrows(), ConstTensor6View::nshelves(), and ConstTensor6View::nvitrines().
describe() [7/8]
string describe (ConstTensor7View x)
Describe Tensor7.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 36 of file describe.cc.
References ConstTensor7View::nbooks(), ConstTensor7View::ncols(), ConstTensor7View::nlibraries(), ConstTensor7View::npages(), ConstTensor7View::nrows(), ConstTensor7View::nshelves(), and ConstTensor7View::nvitrines().
Referenced by junk2(), junk4(), option_describe(), and test33().
describe() [8/8]
string describe (ConstVectorView x)
Describe Vector.
Parameters
x What to describe.
Returns
Output stream.
Definition at line 129 of file describe.cc.
References ConstVectorView::nelem().