ARTS: m_abs.cc File Reference
m_abs.cc File Reference
Stuff related to the calculation of absorption coefficients.
#include <cmath>
#include <algorithm>
#include "arts.h"
#include "matpackI.h"
#include "array.h"
#include "messages.h"
#include "file.h"
#include "absorption.h"
#include "auto_md.h"
#include "math_funcs.h"
#include "make_array.h"
#include "physics_funcs.h"
#include "continua.h"
#include "make_vector.h"
#include "check_input.h"
#include "xml_io.h"
Functions
void AbsInputFromRteScalars (Vector &abs_p, Vector &abs_t, Matrix &abs_vmrs, const Numeric &rte_pressure, const Numeric &rte_temperature, const Vector &rte_vmr_list, const Verbosity &)
WORKSPACE METHOD: AbsInputFromRteScalars.
void abs_lines_per_speciesSetEmpty (ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &tgs, const Verbosity &)
WORKSPACE METHOD: abs_lines_per_speciesSetEmpty.
void abs_linesReadFromHitran (ArrayOfLineRecord &abs_lines, const String &filename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadFromHitran.
void abs_linesReadFromHitran2004 (ArrayOfLineRecord &abs_lines, const String &filename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadFromHitran2004.
void abs_linesReadFromMytran2 (ArrayOfLineRecord &abs_lines, const String &filename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadFromMytran2.
void abs_linesReadFromJpl (ArrayOfLineRecord &abs_lines, const String &filename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadFromJpl.
void abs_linesReadFromArts (ArrayOfLineRecord &abs_lines, const String &filename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadFromArts.
void abs_linesReadFromSplitArtscat (ArrayOfLineRecord &abs_lines, const ArrayOfArrayOfSpeciesTag &abs_species, const String &basename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_linesReadFromSplitArtscat.
void abs_linesReadFromArtsObsolete (ArrayOfLineRecord &abs_lines, const String &filename, const Numeric &fmin, const Numeric &fmax, const Verbosity &verbosity)
Obsolete old ARTS catalogue reading function.
void linesElowToJoule (ArrayOfLineRecord &abs_lines)
void abs_lines_per_speciesReadFromCatalogues (ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfArrayOfSpeciesTag &tgs, const ArrayOfString &filenames, const ArrayOfString &formats, const Vector &fmin, const Vector &fmax, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesReadFromCatalogues.
void abs_lines_per_speciesCreateFromLines (ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfLineRecord &abs_lines, const ArrayOfArrayOfSpeciesTag &tgs, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lines_per_speciesCreateFromLines.
void abs_lines_per_speciesAddMirrorLines (ArrayOfArrayOfLineRecord &abs_lines_per_species, const Verbosity &)
WORKSPACE METHOD: abs_lines_per_speciesAddMirrorLines.
void abs_lines_per_speciesCompact (ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfLineshapeSpec &abs_lineshape, const Vector &f_grid, const Verbosity &)
WORKSPACE METHOD: abs_lines_per_speciesCompact.
void abs_speciesDefineAllInScenario (ArrayOfArrayOfSpeciesTag &tgs, const String &basename, const Verbosity &verbosity)
WORKSPACE METHOD: abs_speciesDefineAllInScenario.
void abs_lineshapeDefine (ArrayOfLineshapeSpec &abs_lineshape, const String &shape, const String &normalizationfactor, const Numeric &cutoff, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lineshapeDefine.
void abs_lineshape_per_tgDefine (ArrayOfLineshapeSpec &abs_lineshape, const ArrayOfArrayOfSpeciesTag &tgs, const ArrayOfString &shape, const ArrayOfString &normalizationfactor, const Vector &cutoff, const Verbosity &verbosity)
WORKSPACE METHOD: abs_lineshape_per_tgDefine.
void abs_h2oSet (Vector &abs_h2o, const ArrayOfArrayOfSpeciesTag &abs_species, const Matrix &abs_vmrs, const Verbosity &)
WORKSPACE METHOD: abs_h2oSet.
void abs_n2Set (Vector &abs_n2, const ArrayOfArrayOfSpeciesTag &abs_species, const Matrix &abs_vmrs, const Verbosity &)
WORKSPACE METHOD: abs_n2Set.
void AbsInputFromAtmFields (Vector &abs_p, Vector &abs_t, Matrix &abs_vmrs, const Index &atmosphere_dim, const Vector &p_grid, const Tensor3 &t_field, const Tensor4 &vmr_field, const Verbosity &)
WORKSPACE METHOD: AbsInputFromAtmFields.
void abs_coefCalc (Matrix &abs_coef, ArrayOfMatrix &abs_coef_per_species, const ArrayOfArrayOfSpeciesTag &tgs, const Vector &f_grid, const Vector &abs_p, const Vector &abs_t, const Vector &abs_n2, const Vector &abs_h2o, const Matrix &abs_vmrs, const ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfLineshapeSpec &abs_lineshape, const ArrayOfString &abs_cont_names, const ArrayOfString &abs_cont_models, const ArrayOfVector &abs_cont_parameters, const Verbosity &verbosity)
WORKSPACE METHOD: abs_coefCalc.
void abs_coefCalcSaveMemory (Matrix &abs_coef, const ArrayOfArrayOfSpeciesTag &tgs, const Vector &f_grid, const Vector &abs_p, const Vector &abs_t, const Vector &abs_n2, const Vector &abs_h2o, const Matrix &abs_vmrs, const ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfLineshapeSpec &abs_lineshape, const ArrayOfString &abs_cont_names, const ArrayOfString &abs_cont_models, const ArrayOfVector &abs_cont_parameters, const Verbosity &verbosity)
WORKSPACE METHOD: abs_coefCalcSaveMemory.
void abs_coefCalcFromXsec (Matrix &abs_coef, ArrayOfMatrix &abs_coef_per_species, const ArrayOfMatrix &abs_xsec_per_species, const Matrix &abs_vmrs, const Vector &abs_p, const Vector &abs_t, const Verbosity &verbosity)
WORKSPACE METHOD: abs_coefCalcFromXsec.
void abs_xsec_per_speciesInit (ArrayOfMatrix &abs_xsec_per_species, const ArrayOfArrayOfSpeciesTag &tgs, const Vector &f_grid, const Vector &abs_p, const Verbosity &verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesInit.
void abs_xsec_per_speciesAddLines (ArrayOfMatrix &abs_xsec_per_species, const ArrayOfArrayOfSpeciesTag &tgs, const Vector &f_grid, const Vector &abs_p, const Vector &abs_t, const Vector &abs_h2o, const Matrix &abs_vmrs, const ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfLineshapeSpec &abs_lineshape, const Verbosity &verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddLines.
void abs_xsec_per_speciesAddConts (ArrayOfMatrix &abs_xsec_per_species, const ArrayOfArrayOfSpeciesTag &tgs, const Vector &f_grid, const Vector &abs_p, const Vector &abs_t, const Vector &abs_n2, const Vector &abs_h2o, const Matrix &abs_vmrs, const ArrayOfString &abs_cont_names, const ArrayOfVector &abs_cont_parameters, const ArrayOfString &abs_cont_models, const Verbosity &verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddConts.
void abs_cont_descriptionInit (ArrayOfString &names, ArrayOfString &options, ArrayOfVector &parameters, const Verbosity &verbosity)
WORKSPACE METHOD: abs_cont_descriptionInit.
void abs_cont_descriptionAppend (ArrayOfString &abs_cont_names, ArrayOfString &abs_cont_models, ArrayOfVector &abs_cont_parameters, const String &tagname, const String &model, const Vector &userparameters, const Verbosity &)
WORKSPACE METHOD: abs_cont_descriptionAppend.
void abs_scalar_gasFromAbsCoef (Matrix &abs_scalar_gas, const ArrayOfMatrix &abs_coef_per_species, const Verbosity &)
WORKSPACE METHOD: abs_scalar_gasFromAbsCoef.
void abs_scalar_gasCalcLBL (Matrix &abs_scalar_gas, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const Vector &abs_n2, const ArrayOfArrayOfLineRecord &abs_lines_per_species, const ArrayOfLineshapeSpec &abs_lineshape, const ArrayOfString &abs_cont_names, const ArrayOfString &abs_cont_models, const ArrayOfVector &abs_cont_parameters, const Index &f_index, const Numeric &rte_pressure, const Numeric &rte_temperature, const Vector &rte_vmr_list, const Numeric &rte_doppler, const Verbosity &verbosity)
WORKSPACE METHOD: abs_scalar_gasCalcLBL.
void f_gridSelectFIndex (Vector &f_grid, const Index &f_index, const Verbosity &)
WORKSPACE METHOD: f_gridSelectFIndex.
void WriteMolTau (const Vector &f_grid, const Tensor3 &z_field, const Tensor5 &abs_field, const Index &atmosphere_dim, const String &filename, const Verbosity &)
WORKSPACE METHOD: WriteMolTau.
Variables
const Numeric SPEED_OF_LIGHT
Detailed Description
Stuff related to the calculation of absorption coefficients.
Author
Stefan Buehler
Date
2001-03-12
Definition in file m_abs.cc.
Function Documentation
abs_coefCalc()
void abs_coefCalc (Matrix & abs_coef, ArrayOfMatrix & abs_coef_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Vector & f_grid, const Vector & abs_p, const Vector & abs_t, const Vector & abs_n2, const Vector & abs_h2o, const Matrix & abs_vmrs, const ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfLineshapeSpec & abs_lineshape, const ArrayOfString & abs_cont_names, const ArrayOfString & abs_cont_models, const ArrayOfVector & abs_cont_parameters, const Verbosity & verbosity)
WORKSPACE METHOD: abs_coefCalc.
Calculate absorption coefficients.
This function calculates both the total absorption (abs_coef), and the absorption per species (abs_coef_per_species).
The method calls four other methods:
abs_xsec_per_speciesInit: <br> Initialize abs_xsec_per_species
abs_xsec_per_speciesAddLines: <br> Calculate cross sections per tag group for line spectra.
abs_xsec_per_speciesAddConts: <br> Calculate cross sections per tag group for continua.
abs_coefCalcFromXsec: <br> Calculate absorption coefficients from the cross sections by <br> multiplying each cross section by n*VMR.
This is done once for each tag group (output abs_coef_per_species), and for the sum of all tag groups (output abs_coef).
Author
Axel von Engeln
Stefan Buehler
Parameters
[out] abs_coef WS Output
[out] abs_coef_per_species WS Output
[in] abs_species WS Input
[in] f_grid WS Input
[in] abs_p WS Input
[in] abs_t WS Input
[in] abs_n2 WS Input
[in] abs_h2o WS Input
[in] abs_vmrs WS Input
[in] abs_lines_per_species WS Input
[in] abs_lineshape WS Input
[in] abs_cont_names WS Input
[in] abs_cont_models WS Input
[in] abs_cont_parameters WS Input
Definition at line 1198 of file m_abs.cc.
References abs_coefCalcFromXsec(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddLines(), and abs_xsec_per_speciesInit().
Referenced by abs_coefCalc_g(), and abs_scalar_gasCalcLBL().
abs_coefCalcFromXsec()
void abs_coefCalcFromXsec (Matrix & abs_coef, ArrayOfMatrix & abs_coef_per_species, const ArrayOfMatrix & abs_xsec_per_species, const Matrix & abs_vmrs, const Vector & abs_p, const Vector & abs_t, const Verbosity & verbosity)
WORKSPACE METHOD: abs_coefCalcFromXsec.
Calculate absorption coefficients from cross sections.
This calculates both the total absorption and the absorption per species.
Cross sections are multiplied by n*VMR.
Author
Stefan Buehler
Axel von Engeln
Parameters
[out] abs_coef WS Output
[out] abs_coef_per_species WS Output
[in] abs_xsec_per_species WS Input
[in] abs_vmrs WS Input
[in] abs_p WS Input
[in] abs_t WS Input
Definition at line 1371 of file m_abs.cc.
References chk_size(), CREATE_OUT3, ConstMatrixView::ncols(), Array< base >::nelem(), ConstMatrixView::nrows(), number_density(), and Matrix::resize().
Referenced by abs_coefCalc(), abs_coefCalcFromXsec_g(), and abs_coefCalcSaveMemory().
abs_coefCalcSaveMemory()
void abs_coefCalcSaveMemory (Matrix & abs_coef, const ArrayOfArrayOfSpeciesTag & abs_species, const Vector & f_grid, const Vector & abs_p, const Vector & abs_t, const Vector & abs_n2, const Vector & abs_h2o, const Matrix & abs_vmrs, const ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfLineshapeSpec & abs_lineshape, const ArrayOfString & abs_cont_names, const ArrayOfString & abs_cont_models, const ArrayOfVector & abs_cont_parameters, const Verbosity & verbosity)
WORKSPACE METHOD: abs_coefCalcSaveMemory.
Calculate absorption coefficients, trying to conserve memory.
This function calculates only the total absorption (abs_coef), NOT the absorption per tag group (abs_coef_per_species).
This means you cannot use it if you want to calculate Jacobians later.
The implementation follows abs_coefCalc.
Author
Stefan Buehler
Parameters
[out] abs_coef WS Output
[in] abs_species WS Input
[in] f_grid WS Input
[in] abs_p WS Input
[in] abs_t WS Input
[in] abs_n2 WS Input
[in] abs_h2o WS Input
[in] abs_vmrs WS Input
[in] abs_lines_per_species WS Input
[in] abs_lineshape WS Input
[in] abs_cont_names WS Input
[in] abs_cont_models WS Input
[in] abs_cont_parameters WS Input
Definition at line 1259 of file m_abs.cc.
References abs_coefCalcFromXsec(), abs_xsec_per_speciesAddConts(), abs_xsec_per_speciesAddLines(), abs_xsec_per_speciesInit(), CREATE_OUT3, joker, ConstMatrixView::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and Matrix::resize().
Referenced by abs_coefCalcSaveMemory_g().
abs_cont_descriptionAppend()
void abs_cont_descriptionAppend (ArrayOfString & abs_cont_names, ArrayOfString & abs_cont_models, ArrayOfVector & abs_cont_parameters, const String & tagname, const String & model, const Vector & userparameters, const Verbosity & verbosity)
WORKSPACE METHOD: abs_cont_descriptionAppend.
Appends the description of a continuum model or a complete absorption model to abs_cont_names and abs_cont_parameters.
See online documentation for abs_cont_names for a list of allowed models and for information what parameters they require. See file includes/continua.arts for default parameters for the various models.
Author
Thomas Kuhn
Stefan Buehler
Parameters
[out] abs_cont_names WS Output
[out] abs_cont_models WS Output
[out] abs_cont_parameters WS Output
[in] tagname Generic Input
[in] model Generic Input
[in] userparameters Generic Input
Definition at line 2016 of file m_abs.cc.
References check_continuum_model().
Referenced by abs_cont_descriptionAppend_g().
abs_cont_descriptionInit()
void abs_cont_descriptionInit (ArrayOfString & abs_cont_names, ArrayOfString & abs_cont_models, ArrayOfVector & abs_cont_parameters, const Verbosity & verbosity)
WORKSPACE METHOD: abs_cont_descriptionInit.
Initializes the two workspace variables for the continuum description, abs_cont_names* and abs_cont_parameters.
This method does not really do anything, except setting the two variables to empty Arrays. It is just necessary because the method abs_cont_descriptionAppend* wants to append to the variables.
Formally, the continuum description workspace variables are required by the absorption calculation methods (e.g., abs_coefCalc). Therefore you always have to call at least abs_cont_descriptionInit, even if you do not want to use any continua.
Author
Thomas Kuhn
Stefan Buehler
Parameters
[out] abs_cont_names WS Output
[out] abs_cont_models WS Output
[out] abs_cont_parameters WS Output
Definition at line 1998 of file m_abs.cc.
References CREATE_OUT2, and parameters.
Referenced by abs_cont_descriptionInit_g().
abs_h2oSet()
void abs_h2oSet (Vector & abs_h2o, const ArrayOfArrayOfSpeciesTag & abs_species, const Matrix & abs_vmrs, const Verbosity & verbosity)
WORKSPACE METHOD: abs_h2oSet.
Sets abs_h2o to the profile of the first tag group containing water.
This is necessary, because for example abs_coefCalc requires abs_h2o to contain the water vapour profile(the reason for this is the calculation of oxygen line broadening requires water vapour profile). Then this function can be used to copy the profile of the first tag group of water.
Author
Stefan Buehler
Parameters
[out] abs_h2o WS Output
[in] abs_species WS Input
[in] abs_vmrs WS Input
Definition at line 1134 of file m_abs.cc.
References find_first_species_tg(), joker, ConstMatrixView::ncols(), Vector::resize(), and species_index_from_species_name().
Referenced by abs_h2oSet_g(), and abs_scalar_gasCalcLBL().
abs_lines_per_speciesAddMirrorLines()
void abs_lines_per_speciesAddMirrorLines (ArrayOfArrayOfLineRecord & abs_lines_per_species, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesAddMirrorLines.
Adds mirror lines at negative frequencies to abs_lines_per_species.
For each line at frequency +f in abs_lines_per_species a corresponding entry at frequency -f is added to abs_lines_per_species. The mirror lines are appended to the line list after the original lines.
Author
Axel von Engeln
Stefan Buehler
Parameters
[out] abs_lines_per_species WS Output
Definition at line 783 of file m_abs.cc.
References LineRecord::F(), ll, Array< base >::nelem(), and LineRecord::setF().
Referenced by abs_lines_per_speciesAddMirrorLines_g().
abs_lines_per_speciesCompact()
void abs_lines_per_speciesCompact (ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfLineshapeSpec & abs_lineshape, const Vector & f_grid, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesCompact.
Removes all lines outside the defined lineshape cutoff frequencies from abs_lines_per_species. This can save computation time. It should be particularly useful to call this method after abs_lines_per_speciesAddMirrorLines*.
Author
Axel von Engeln
Stefan Buehler
Parameters
[out] abs_lines_per_species WS Output
[in] abs_lineshape WS Input
[in] f_grid WS Input
Definition at line 820 of file m_abs.cc.
References ll, Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by abs_lines_per_speciesCompact_g().
abs_lines_per_speciesCreateFromLines()
void abs_lines_per_speciesCreateFromLines (ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfLineRecord & abs_lines, const ArrayOfArrayOfSpeciesTag & abs_species, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesCreateFromLines.
Split lines up into the different species.
The species are tested in the order in which they are specified in the controlfile. Lines are assigned to the first species that matches. That means if the list of species is ["O3-666","O3"], then the last group O3 gets assigned all the O3 lines that do not fit in the first group (all other isotopes than the main isotope).
Author
Stefan Buehler
Parameters
[out] abs_lines_per_species WS Output
[in] abs_lines WS Input
[in] abs_species WS Input
Definition at line 639 of file m_abs.cc.
References CREATE_OUT2, CREATE_OUT3, LineRecord::F(), SpeciesTag::Isotope(), SpeciesRecord::Isotope(), LineRecord::Isotope(), SpeciesTag::Lf(), SpeciesRecord::Name(), Array< base >::nelem(), SpeciesTag::Species(), LineRecord::Species(), species_data, LineRecord::SpeciesData(), and SpeciesTag::Uf().
Referenced by abs_lines_per_speciesCreateFromLines_g(), and abs_lines_per_speciesReadFromCatalogues().
abs_lines_per_speciesReadFromCatalogues()
void abs_lines_per_speciesReadFromCatalogues (ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfString & filenames, const ArrayOfString & formats, const Vector & fmin, const Vector & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesReadFromCatalogues.
Read spectral line data from different line catalogues.
For each absorption species, you can specify which catalogue to use. Because the method creates abs_lines_per_species directly, it replaces for example the following two method calls:
<br> - abs_linesReadFromHitran <br> - abs_lines_per_speciesCreateFromLines
This method needs as input WSVs the list of species abs_species*. Generic input parameters must specify the names of the catalogue files to use and the matching formats. Names can be anything, formats can currently be HITRAN96 (for HITRAN 1986-2001 databases), HITRAN04 (for HITRAN 2004 database), MYTRAN2, JPL, or ARTS. Furthermore, you have to specify minimum and maximum frequency for each species. To safe typing, if there are less elements in the keyword parameters than there are species, the last parameters are applied to all following species.
Example usage:
abs_lines_per_speciesReadFromCatalogues(<br> [ "../data/cat1.dat", "../data/cat2.dat" ] <br> [ "MYTRAN2", "HITRAN96" ] <br> [ 0, 0 ] <br> [ 2000e9, 100e9 ])
In this example, lines for the first species will be taken from cat1, lines for all other species will be taken from cat2. This allows you for example to use a special line file just for water vapor lines.
Catalogues are only read once, even if several tag groups have the same catalogue. However, in that case the frequency ranges MUST be the same. (If you want to do fine-tuning of the frequency ranges, you can do this inside the tag definitions, e.g., "H2O-*-0-2000e9".)
This function uses the various reading routines (abs_linesReadFromHitran, etc.), as well as abs_lines_per_speciesCreateFromLines*.
Author
Stefan Buehler
Parameters
[out] abs_lines_per_species WS Output
[in] abs_species WS Input
[in] filenames Generic Input
[in] formats Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 429 of file m_abs.cc.
References abs_lines_per_speciesCreateFromLines(), abs_linesReadFromArts(), abs_linesReadFromHitran(), abs_linesReadFromHitran2004(), abs_linesReadFromJpl(), abs_linesReadFromMytran2(), CREATE_OUT3, Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by abs_lines_per_speciesReadFromCatalogues_g().
abs_lines_per_speciesSetEmpty()
void abs_lines_per_speciesSetEmpty (ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lines_per_speciesSetEmpty.
Sets abs_lines_per_species to empty line lists.
You can use this method to set abs_lines_per_species if you do not really want to compute line spectra. Formally, abs_coefCalc will still require abs_lines_per_species to be set.
Author
Stefan Buehler
Parameters
[out] abs_lines_per_species WS Output
[in] abs_species WS Input
Definition at line 83 of file m_abs.cc.
References Array< base >::nelem().
Referenced by abs_lines_per_speciesSetEmpty_g().
abs_lineshape_per_tgDefine()
void abs_lineshape_per_tgDefine (ArrayOfLineshapeSpec & abs_lineshape, const ArrayOfArrayOfSpeciesTag & abs_species, const ArrayOfString & shape, const ArrayOfString & normalizationfactor, const Vector & cutoff, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lineshape_per_tgDefine.
Set the lineshape, separately for each absorption species.
This method is similar to abs_lineshapeDefine, except that a different lineshape can be set for each absorption species (see abs_species*). For example, you might want to use different values of the cutoff frequency for different species.
For detailed documentation on the available options for the input parameters see documentation of method abs_lineshapeDefine.
Author
Axel von Engeln
Stefan Buehler
Parameters
[out] abs_lineshape WS Output
[in] abs_species WS Input
[in] shape Generic Input
[in] normalizationfactor Generic Input
[in] cutoff Generic Input
Definition at line 1045 of file m_abs.cc.
References CREATE_OUT2, lineshape_data, lineshape_norm_data, Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by abs_lineshape_per_tgDefine_g().
abs_lineshapeDefine()
void abs_lineshapeDefine (ArrayOfLineshapeSpec & abs_lineshape, const String & shape, const String & normalizationfactor, const Numeric & cutoff, const Verbosity & verbosity)
WORKSPACE METHOD: abs_lineshapeDefine.
Set the lineshape for all calculated lines.
Sets the lineshape function. Beside the lineshape function itself, you also have so select a forefactor and a frequency cutoff. The forefactor is later multiplied with the lineshape function.
The cutoff frequency is used to make lineshapes finite in frequency, the response outside the cutoff is set to zero, and the lineshape value at the cutoff frequency is subtracted from the overall lineshape as a constant offset. This ensures that the lineshape goes to zero at the cutoff frequency without a discontinuity.
We generate only one copy of the lineshape settings. Absorption routines check for this case and use it for all species.
The allowed values for the input parameters are:
shape: <br> no_shape: no specified shape <br> Doppler: Doppler lineshape <br> Lorentz: Lorentz lineshape <br> Voigt_Kuntz3: Kuntz approximation to the Voigt lineshape, <br> accuracy > 2x10^(-3) <br> Voigt_Kuntz4: Kuntz approximation to the Voigt lineshape, <br> accuracy > 2x10^(-4) <br> Voigt_Kuntz6: Kuntz approximation to the Voigt lineshape, <br> accuracy > 2x10^(-6) <br> Voigt_Drayson: Drayson approximation to the Voigt lineshape <br> Rosenkranz_Voigt_Drayson: Rosenkrantz oxygen absortion with overlap correction <br> on the basis of Drayson routine <br> Rosenkranz_Voigt_Kuntz6 : Rosenkrantz oxygen absortion with overlap correction <br> on the basis of Kuntz routine, accuracy > 2x10^(-6) <br> CO2_Lorentz: Lorentz multiplied with Cousin's chi factors <br> CO2_Drayson: Drayson multiplied with Cousin's chi factors
forefactor: <br> no_norm: 1 <br> quadratic: (f/f0)^2 <br> VVH: (f*tanh(h*f/(2k*T))) / (f0*tanh(h*f0/(2k*T)))
cutoff: <br> -1: no cutoff <br> <Number>: positive cutoff frequency in Hz
Author
Axel von Engeln
Stefan Buehler
Parameters
[out] abs_lineshape WS Output
[in] shape Generic Input
[in] normalizationfactor Generic Input
[in] cutoff Generic Input
Definition at line 976 of file m_abs.cc.
References CREATE_OUT2, lineshape_data, and lineshape_norm_data.
Referenced by abs_lineshapeDefine_g().
abs_linesReadFromArts()
void abs_linesReadFromArts (ArrayOfLineRecord & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadFromArts.
Read all the lines from an Arts catalogue file in the given frequency range. Otherwise a runtime error will be thrown
Please note that all lines must correspond to legal species / isotope combinations
Author
Stefan Buehler
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 274 of file m_abs.cc.
References CREATE_OUT2, Array< base >::nelem(), and xml_read_arts_catalogue_from_file().
Referenced by abs_lines_per_speciesReadFromCatalogues(), abs_linesReadFromArts_g(), and abs_linesReadFromSplitArtscat().
abs_linesReadFromArtsObsolete()
void abs_linesReadFromArtsObsolete (ArrayOfLineRecord & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
Obsolete old ARTS catalogue reading function.
This function is for the old ARTS catalogue format without XML header. It is no longer used, but left here for historical reasons.
Author
Stefan Buehler
Parameters
abs_lines Line data.
filename Name of catalogue file.
fmin Minimum frequency.
fmax Maximum frequency.
Definition at line 347 of file m_abs.cc.
References CREATE_OUT2, LineRecord::F(), Array< base >::nelem(), open_input_file(), LineRecord::ReadFromArtscat3Stream(), LineRecord::Version(), and LineRecord::VersionString().
abs_linesReadFromHitran()
void abs_linesReadFromHitran (ArrayOfLineRecord & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadFromHitran.
Read all the lines from a HITRAN 1986-2001 catalogue file in the given frequency range. Otherwise a runtime error will be thrown. For HITRAN 2004 line data use the workspace method abs_linesReadFromHitran2004*.
Please note that all lines must correspond to legal species / isotope combinations and that the line data file must be sorted by increasing frequency
WWW access of the HITRAN catalogue: http://www.hitran.com/
Author
Thomas Kuhn
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 100 of file m_abs.cc.
References CREATE_OUT2, LineRecord::F(), Array< base >::nelem(), open_input_file(), and LineRecord::ReadFromHitranStream().
Referenced by abs_lines_per_speciesReadFromCatalogues(), and abs_linesReadFromHitran_g().
abs_linesReadFromHitran2004()
void abs_linesReadFromHitran2004 (ArrayOfLineRecord & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadFromHitran2004.
Read all the lines from a HITRAN 2004 catalogue file in the given frequency range. Otherwise a runtime error is thrown.
Records of molecules unknown to ARTS are ignored but a warning is issued. In particular this happens for CH3OH (HITRAN molecule number 39) because there is no total internal partition sum available.
The database must be sorted by increasing frequency!
WWW access of the HITRAN catalogue: http://www.hitran.com/
For data in the Hitran 1986-2001 format use the workspace method: abs_linesReadFromHitran
Author
Hermann Berg
Thomas Kuhn
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 144 of file m_abs.cc.
References CREATE_OUT2, LineRecord::F(), Array< base >::nelem(), open_input_file(), and LineRecord::ReadFromHitran2004Stream().
Referenced by abs_lines_per_speciesReadFromCatalogues(), and abs_linesReadFromHitran2004_g().
abs_linesReadFromJpl()
void abs_linesReadFromJpl (ArrayOfLineRecord & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadFromJpl.
Read all the lines from a JPL catalogue file in the given frequency range. Otherwise a runtime error will be thrown
Please note that all lines must correspond to legal species / isotope combinations.
WWW access of the JPL catalogue: http://spec.jpl.nasa.gov/
Author
Thomas Kuhn
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 229 of file m_abs.cc.
References CREATE_OUT2, LineRecord::F(), Array< base >::nelem(), open_input_file(), and LineRecord::ReadFromJplStream().
Referenced by abs_lines_per_speciesReadFromCatalogues(), and abs_linesReadFromJpl_g().
abs_linesReadFromMytran2()
void abs_linesReadFromMytran2 (ArrayOfLineRecord & abs_lines, const String & filename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadFromMytran2.
Read all the lines from a MYTRAN2 catalogue file in the given frequency range. Otherwise a runtime error will be thrown
Please note that all lines must correspond to legal species / isotope combinations
Author
Axel von Engeln
Stefan Buehler
Parameters
[out] abs_lines WS Output
[in] filename Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 188 of file m_abs.cc.
References CREATE_OUT2, LineRecord::F(), Array< base >::nelem(), open_input_file(), and LineRecord::ReadFromMytran2Stream().
Referenced by abs_lines_per_speciesReadFromCatalogues(), and abs_linesReadFromMytran2_g().
abs_linesReadFromSplitArtscat()
void abs_linesReadFromSplitArtscat (ArrayOfLineRecord & abs_lines, const ArrayOfArrayOfSpeciesTag & abs_species, const String & basename, const Numeric & fmin, const Numeric & fmax, const Verbosity & verbosity)
WORKSPACE METHOD: abs_linesReadFromSplitArtscat.
Read all the lines in the given frequency range from a split Arts catalogue file.
Please note that all lines must correspond to legal species / isotope combinations
Author
Oliver Lemke
Parameters
[out] abs_lines WS Output
[in] abs_species WS Input
[in] basename Generic Input
[in] fmin Generic Input
[in] fmax Generic Input
Definition at line 291 of file m_abs.cc.
References abs_linesReadFromArts(), CREATE_OUT2, Array< base >::nelem(), and species_data.
Referenced by abs_linesReadFromSplitArtscat_g().
abs_n2Set()
void abs_n2Set (Vector & abs_n2, const ArrayOfArrayOfSpeciesTag & abs_species, const Matrix & abs_vmrs, const Verbosity & verbosity)
WORKSPACE METHOD: abs_n2Set.
Sets abs_n2 to the profile of the first tag group containing molecular nitrogen. See abs_h2oSet for more details.
Author
Stefan Buehler
Parameters
[out] abs_n2 WS Output
[in] abs_species WS Input
[in] abs_vmrs WS Input
Definition at line 1152 of file m_abs.cc.
References find_first_species_tg(), joker, ConstMatrixView::ncols(), Vector::resize(), and species_index_from_species_name().
Referenced by abs_n2Set_g().
abs_scalar_gasCalcLBL()
void abs_scalar_gasCalcLBL (Matrix & abs_scalar_gas, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const Vector & abs_n2, const ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfLineshapeSpec & abs_lineshape, const ArrayOfString & abs_cont_names, const ArrayOfString & abs_cont_models, const ArrayOfVector & abs_cont_parameters, const Index & f_index, const Numeric & rte_pressure, const Numeric & rte_temperature, const Vector & rte_vmr_list, const Numeric & rte_doppler, const Verbosity & verbosity)
WORKSPACE METHOD: abs_scalar_gasCalcLBL.
Calculates scalar gas absorption coefficients line-by-line.
This method can be used inside abs_scalar_gas_agenda just like abs_scalar_gasExtractFromLookup*. It is a shortcut for putting in some other methods explicitly, namely:
<br> 1. f_gridSelectFIndex <br> 2. NumericScale(rte_doppler, rte_doppler, -1) <br> 3. VectorAddScalar(f_grid, f_grid, rte_doppler) <br> 4. AbsInputFromRteScalars <br> 5. abs_h2oSet <br> 6. abs_coefCalc <br> 7. abs_scalar_gasFromAbsCoef
Sub-methods 2 and 3 are called only if rte_doppler is not zero. The treatment of the Doppler-shift here is exact, since the underlying frequency grid is shifted.
The calculation is for one specific atmospheric condition, i.e., a set of pressure, temperature, VMR values, and Doppler shift. It can be either for a single frequency (f_index>=0), or for all frequencies (f_index<0). The dimension of the output abs_scalar_gas is adjusted accordingly.
Author
Stefan Buehler
Parameters
[out] abs_scalar_gas WS Output
[in] f_grid WS Input
[in] abs_species WS Input
[in] abs_n2 WS Input
[in] abs_lines_per_species WS Input
[in] abs_lineshape WS Input
[in] abs_cont_names WS Input
[in] abs_cont_models WS Input
[in] abs_cont_parameters WS Input
[in] f_index WS Input
[in] rte_pressure WS Input
[in] rte_temperature WS Input
[in] rte_vmr_list WS Input
[in] rte_doppler WS Input
Definition at line 2080 of file m_abs.cc.
References abs_coefCalc(), abs_h2oSet(), abs_scalar_gasFromAbsCoef(), AbsInputFromRteScalars(), CREATE_OUT3, f_gridSelectFIndex(), NumericScale(), and VectorAddScalar().
Referenced by abs_scalar_gasCalcLBL_g(), and calc_lookup_error().
abs_scalar_gasFromAbsCoef()
void abs_scalar_gasFromAbsCoef (Matrix & abs_scalar_gas, const ArrayOfMatrix & abs_coef_per_species, const Verbosity & verbosity)
WORKSPACE METHOD: abs_scalar_gasFromAbsCoef.
Copy abs_scalar_gas from abs_coef. This is handy for putting an explicit line-by-line calculation into the abs_scalar_gas_agenda*. See also method AbsInputFromRteScalars.
Author
Stefan Buehler
Parameters
[out] abs_scalar_gas WS Output
[in] abs_coef_per_species WS Input
Definition at line 2041 of file m_abs.cc.
References joker, Array< base >::nelem(), and Matrix::resize().
Referenced by abs_scalar_gasCalcLBL(), and abs_scalar_gasFromAbsCoef_g().
abs_speciesDefineAllInScenario()
void abs_speciesDefineAllInScenario (ArrayOfArrayOfSpeciesTag & abs_species, const String & basename, const Verbosity & verbosity)
WORKSPACE METHOD: abs_speciesDefineAllInScenario.
Define one tag group for each species known to ARTS and included in an atmospheric scenario.
You can use this as an alternative to tgsDefine if you want to make an absorption calculation that is as complete as possible. The method goes through all defined species and tries to open the VMR file. If this works the tag is included, otherwise it is skipped.
Author
Stefan Buehler
Parameters
[out] abs_species WS Output
[in] basename Generic Input
Definition at line 914 of file m_abs.cc.
References CREATE_OUT2, Array< base >::nelem(), open_input_file(), and species_data.
Referenced by abs_speciesDefineAllInScenario_g().
abs_xsec_per_speciesAddConts()
void abs_xsec_per_speciesAddConts (ArrayOfMatrix & abs_xsec_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Vector & f_grid, const Vector & abs_p, const Vector & abs_t, const Vector & abs_n2, const Vector & abs_h2o, const Matrix & abs_vmrs, const ArrayOfString & abs_cont_names, const ArrayOfVector & abs_cont_parameters, const ArrayOfString & abs_cont_models, const Verbosity & verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddConts.
Calculate absorption cross sections per tag group for continua.
Author
Stefan Buehler
Parameters
[out] abs_xsec_per_species WS Output
[in] abs_species WS Input
[in] f_grid WS Input
[in] abs_p WS Input
[in] abs_t WS Input
[in] abs_n2 WS Input
[in] abs_h2o WS Input
[in] abs_vmrs WS Input
[in] abs_cont_names WS Input
[in] abs_cont_parameters WS Input
[in] abs_cont_models WS Input
Definition at line 1715 of file m_abs.cc.
References check_continuum_model(), CREATE_OUT3, joker, ConstMatrixView::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), species_data, and xsec_continuum_tag().
Referenced by abs_coefCalc(), abs_coefCalcSaveMemory(), and abs_xsec_per_speciesAddConts_g().
abs_xsec_per_speciesAddLines()
void abs_xsec_per_speciesAddLines (ArrayOfMatrix & abs_xsec_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Vector & f_grid, const Vector & abs_p, const Vector & abs_t, const Vector & abs_h2o, const Matrix & abs_vmrs, const ArrayOfArrayOfLineRecord & abs_lines_per_species, const ArrayOfLineshapeSpec & abs_lineshape, const Verbosity & verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesAddLines.
Calculates the line spectrum for each tag group and adds it to abs_xsec_per_species.
Author
Stefan Buehler
Axel von Engeln
Parameters
[out] abs_xsec_per_species WS Output
[in] abs_species WS Input
[in] f_grid WS Input
[in] abs_p WS Input
[in] abs_t WS Input
[in] abs_h2o WS Input
[in] abs_vmrs WS Input
[in] abs_lines_per_species WS Input
[in] abs_lineshape WS Input
Definition at line 1484 of file m_abs.cc.
References CREATE_OUT3, LineshapeSpec::Cutoff(), get_tag_group_name(), LineshapeSpec::Ind_ls(), LineshapeSpec::Ind_lsn(), joker, lineshape_data, ll, min, Array< base >::nelem(), ConstMatrixView::nrows(), species_data, and xsec_species().
Referenced by abs_coefCalc(), abs_coefCalcSaveMemory(), and abs_xsec_per_speciesAddLines_g().
abs_xsec_per_speciesInit()
void abs_xsec_per_speciesInit (ArrayOfMatrix & abs_xsec_per_species, const ArrayOfArrayOfSpeciesTag & abs_species, const Vector & f_grid, const Vector & abs_p, const Verbosity & verbosity)
WORKSPACE METHOD: abs_xsec_per_speciesInit.
Initialize abs_xsec_per_species.
The initialization is necessary, because methods abs_xsec_per_speciesAddLines and abs_xsec_per_speciesAddConts just add to abs_xsec_per_species. The size is determined from tgs.
Author
Stefan Buehler
Parameters
[out] abs_xsec_per_species WS Output
[in] abs_species WS Input
[in] f_grid WS Input
[in] abs_p WS Input
Definition at line 1451 of file m_abs.cc.
References CREATE_OUT3, Array< base >::nelem(), and ConstVectorView::nelem().
Referenced by abs_coefCalc(), abs_coefCalcSaveMemory(), and abs_xsec_per_speciesInit_g().
AbsInputFromAtmFields()
void AbsInputFromAtmFields (Vector & abs_p, Vector & abs_t, Matrix & abs_vmrs, const Index & atmosphere_dim, const Vector & p_grid, const Tensor3 & t_field, const Tensor4 & vmr_field, const Verbosity & verbosity)
WORKSPACE METHOD: AbsInputFromAtmFields.
Initialises the WSVs abs_p, abs_t and abs_vmrs from p_grid, t_field and vmr_field.
This only works for a 1D atmosphere!
Author
Stefan Buehler
Parameters
[out] abs_p WS Output
[out] abs_t WS Output
[out] abs_vmrs WS Output
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] t_field WS Input
[in] vmr_field WS Input
Definition at line 1170 of file m_abs.cc.
References joker.
Referenced by AbsInputFromAtmFields_g().
AbsInputFromRteScalars()
void AbsInputFromRteScalars (Vector & abs_p, Vector & abs_t, Matrix & abs_vmrs, const Numeric & rte_pressure, const Numeric & rte_temperature, const Vector & rte_vmr_list, const Verbosity & verbosity)
WORKSPACE METHOD: AbsInputFromRteScalars.
Initialize absorption input WSVs from local atmospheric conditions.
The purpose of this method is to allow an explicit line-by-line calculation, e.g., by abs_coefCalc, to be put inside the abs_scalar_gas_agenda*. What the method does is to prepare absorption input parameters (pressure, temperature, VMRs), from the input parameters to abs_scalar_gas_agenda. There is a matching method to turn the output of abs_coefCalc into what the agenda expects (abs_scalar_gasFromAbsCoef).
Author
Stefan Buehler
Parameters
[out] abs_p WS Output
[out] abs_t WS Output
[out] abs_vmrs WS Output
[in] rte_pressure WS Input
[in] rte_temperature WS Input
[in] rte_vmr_list WS Input
Definition at line 58 of file m_abs.cc.
References ConstVectorView::nelem(), Vector::resize(), and Matrix::resize().
Referenced by abs_scalar_gasCalcLBL(), and AbsInputFromRteScalars_g().
f_gridSelectFIndex()
void f_gridSelectFIndex (Vector & f_grid, const Index & f_index, const Verbosity & verbosity)
WORKSPACE METHOD: f_gridSelectFIndex.
Reduce f_grid to the frequency given by f_index.
This is one of the methods necessary to do line by line absorption calculations inside abs_scalar_gas_agenda.
It reduces the f_grid to only one frequency, the one given by f_index. If f_index is -1, then all frequencies are kept. This behavior is consistent with abs_scalar_gasExtractFromLookup.
Author
Stefan Buehler
Parameters
[out] f_grid WS Output
[in] f_index WS Input
Definition at line 2197 of file m_abs.cc.
References ConstVectorView::nelem(), and Vector::resize().
Referenced by abs_scalar_gasCalcLBL(), and f_gridSelectFIndex_g().
linesElowToJoule()
void linesElowToJoule (ArrayOfLineRecord & abs_lines)
FIXME: Remove this when we don't need the helper function anymore.
Definition at line 420 of file m_abs.cc.
References Array< base >::nelem(), and wavenumber_to_joule().
WriteMolTau()
void WriteMolTau (const Vector & f_grid, const Tensor3 & z_field, const Tensor5 & abs_field, const Index & atmosphere_dim, const String & filename, const Verbosity & verbosity)
WORKSPACE METHOD: WriteMolTau.
Writes a 'molecular_tau_file' as required for libRadtran.
The libRadtran (www.libradtran.org) radiative transfer package is a comprehensive package for various applications, it can be used to compute radiances, irradiances, actinic fluxes, ... for the solar and the thermal spectral ranges. Absorption is usually treated using k-distributions or other parameterizations. For calculations with high spectral resolution it requires absorption coefficients from an external line-by-line model. Using this method, arts generates a file that can be used by libRadtran (option molecular_tau_file).
Author
Claudia Emde
Parameters
[in] f_grid WS Input
[in] z_field WS Input
[in] abs_field WS Input
[in] atmosphere_dim WS Input
[in] filename Generic Input
Definition at line 2350 of file m_abs.cc.
Referenced by WriteMolTau_g().
Variable Documentation
SPEED_OF_LIGHT
const Numeric SPEED_OF_LIGHT extern