ARTS: m_append.h File Reference
m_append.h File Reference
Implementation of Append.
#include "array.h"
#include "exceptions.h"
#include "matpackI.h"
Functions
template<class T >
void Append (Array< T > &out, const Array< T > &in, const Verbosity &)
template<class T >
void Append (Array< T > &out, const T &in, const Verbosity &)
void Append (Vector &out, const Vector &in, const Verbosity &)
void Append (String &out, const String &in, const Verbosity &)
Detailed Description
Implementation of Append.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Fri Jun 14 17:09:05 2002
This file contains the implementation of the supergeneric method Append.
Definition in file m_append.h.
Function Documentation
Append() [1/4]
template<class T > void Append (Array< T > & out, const Array< T > & in, const Verbosity &)
Definition at line 41 of file m_append.h.
References Array< base >::nelem().
Referenced by Append_sg_ArrayOfArrayOfGriddedField1ArrayOfArrayOfGriddedField1_g(), Append_sg_ArrayOfArrayOfGriddedField3ArrayOfArrayOfGriddedField3_g(), Append_sg_ArrayOfArrayOfIndexArrayOfArrayOfIndex_g(), Append_sg_ArrayOfArrayOfLineRecordArrayOfArrayOfLineRecord_g(), Append_sg_ArrayOfArrayOfMatrixArrayOfArrayOfMatrix_g(), Append_sg_ArrayOfArrayOfSpeciesTagArrayOfArrayOfSpeciesTag_g(), Append_sg_ArrayOfArrayOfTensor3ArrayOfArrayOfTensor3_g(), Append_sg_ArrayOfArrayOfTensor6ArrayOfArrayOfTensor6_g(), Append_sg_ArrayOfGriddedField1ArrayOfGriddedField1_g(), Append_sg_ArrayOfGriddedField2ArrayOfGriddedField2_g(), Append_sg_ArrayOfGriddedField3ArrayOfGriddedField3_g(), Append_sg_ArrayOfGriddedField4ArrayOfGriddedField4_g(), Append_sg_ArrayOfIndexArrayOfIndex_g(), Append_sg_ArrayOfLineRecordArrayOfLineRecord_g(), Append_sg_ArrayOfLineshapeSpecArrayOfLineshapeSpec_g(), Append_sg_ArrayOfMatrixArrayOfMatrix_g(), Append_sg_ArrayOfRetrievalQuantityArrayOfRetrievalQuantity_g(), Append_sg_ArrayOfScatteringMetaDataArrayOfScatteringMetaData_g(), Append_sg_ArrayOfScatteringMetaDataScatteringMetaData_g(), Append_sg_ArrayOfSingleScatteringDataArrayOfSingleScatteringData_g(), Append_sg_ArrayOfSingleScatteringDataSingleScatteringData_g(), Append_sg_ArrayOfSparseArrayOfSparse_g(), Append_sg_ArrayOfStringArrayOfString_g(), Append_sg_ArrayOfTensor3ArrayOfTensor3_g(), Append_sg_ArrayOfTensor4ArrayOfTensor4_g(), Append_sg_ArrayOfTensor6ArrayOfTensor6_g(), Append_sg_ArrayOfTensor7ArrayOfTensor7_g(), Append_sg_ArrayOfVectorArrayOfVector_g(), Append_sg_StringString_g(), and Append_sg_VectorVector_g().
Append() [2/4]
template<class T > void Append (Array< T > & out, const T & in, const Verbosity &)
Definition at line 56 of file m_append.h.
Append() [3/4]
void Append (String & out, const String & in, const Verbosity &)
Definition at line 87 of file m_append.h.
Append() [4/4]
void Append (Vector & out, const Vector & in, const Verbosity &)
Definition at line 67 of file m_append.h.
References ConstVectorView::nelem(), and Vector::resize().