ARTS: m_copy.h File Reference
m_copy.h File Reference
Implementation of Copy.
#include "messages.h"
#include "mystring.h"
#include "workspace_ng.h"
#include "agenda_class.h"
Functions
template<class T >
void Copy (T &out, const T &in, const Verbosity &)
WORKSPACE METHOD: Copy.
void Copy (Workspace &ws, Agenda &out, const Agenda &in, const Verbosity &)
Detailed Description
Implementation of Copy.
Implementation of Select.
Author
Stefan Buehler sbueh.nosp@m.ler@.nosp@m.ltu.s.nosp@m.e
Date
Fri Jun 14 17:09:05 2002
This file contains the implementation of the supergeneric method Copy.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2008-08-27
This file contains the implementation of the supergeneric method Select.
Definition in file m_copy.h.
Function Documentation
Copy() [1/2]
template<class T > void Copy (T & gout1, const T & gin1, const Verbosity & verbosity)
WORKSPACE METHOD: Copy.
Copy a workspace variable.
This method can copy any workspace variable to another workspace variable of the same group. (E.g., a Matrix to another Matrix.)
As always, output comes first in the argument list!
Usage example:
Copy(f_grid, p_grid)
Will copy the content of p_grid to f_grid. The size of f_grid is adjusted automatically (the normal behaviour for workspace methods).
Author
Stefan Buehler
Parameters
[out] gout1 Supergeneric output
[in] gin1 Generic Input
Definition at line 40 of file m_copy.h.
Referenced by Copy_sg_Agenda_g(), Copy_sg_ArrayOfArrayOfGriddedField1_g(), Copy_sg_ArrayOfArrayOfGriddedField3_g(), Copy_sg_ArrayOfArrayOfIndex_g(), Copy_sg_ArrayOfArrayOfLineRecord_g(), Copy_sg_ArrayOfArrayOfMatrix_g(), Copy_sg_ArrayOfArrayOfSpeciesTag_g(), Copy_sg_ArrayOfArrayOfTensor3_g(), Copy_sg_ArrayOfArrayOfTensor6_g(), Copy_sg_ArrayOfGriddedField1_g(), Copy_sg_ArrayOfGriddedField2_g(), Copy_sg_ArrayOfGriddedField3_g(), Copy_sg_ArrayOfGriddedField4_g(), Copy_sg_ArrayOfIndex_g(), Copy_sg_ArrayOfLineRecord_g(), Copy_sg_ArrayOfLineshapeSpec_g(), Copy_sg_ArrayOfMatrix_g(), Copy_sg_ArrayOfRetrievalQuantity_g(), Copy_sg_ArrayOfScatteringMetaData_g(), Copy_sg_ArrayOfSingleScatteringData_g(), Copy_sg_ArrayOfSparse_g(), Copy_sg_ArrayOfString_g(), Copy_sg_ArrayOfTensor3_g(), Copy_sg_ArrayOfTensor4_g(), Copy_sg_ArrayOfTensor6_g(), Copy_sg_ArrayOfTensor7_g(), Copy_sg_ArrayOfVector_g(), Copy_sg_GasAbsLookup_g(), Copy_sg_GriddedField1_g(), Copy_sg_GriddedField2_g(), Copy_sg_GriddedField3_g(), Copy_sg_GriddedField4_g(), Copy_sg_GridPos_g(), Copy_sg_Index_g(), Copy_sg_Matrix_g(), Copy_sg_MCAntenna_g(), Copy_sg_Numeric_g(), Copy_sg_Ppath_g(), Copy_sg_ScatteringMetaData_g(), Copy_sg_SingleScatteringData_g(), Copy_sg_Sparse_g(), Copy_sg_String_g(), Copy_sg_Tensor3_g(), Copy_sg_Tensor4_g(), Copy_sg_Tensor5_g(), Copy_sg_Tensor6_g(), Copy_sg_Tensor7_g(), Copy_sg_Timer_g(), Copy_sg_Vector_g(), and Copy_sg_Verbosity_g().
Copy() [2/2]
void Copy (Workspace & ws, Agenda & out, const Agenda & in, const Verbosity &)
Definition at line 53 of file m_copy.h.