ARTS: m_fos.cc File Reference
m_fos.cc File Reference
Workspace functions associated with the FOS scattering scheme.
#include <cmath>
#include <stdexcept>
#include "arts.h"
#include "arts_omp.h"
#include "auto_md.h"
#include "montecarlo.h"
#include "rte.h"
#include "special_interp.h"
Functions
void fos_yStandard (Workspace &ws, Tensor3 &fos_y, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, const Vector &rte_pos, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &stokes_dim, const Vector &f_grid, const Agenda &ppath_step_agenda, const Agenda &emission_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &iy_clearsky_agenda, const Tensor3 &iy_transmission, const Tensor4 &pnd_field, const ArrayOfSingleScatteringData &scat_data_raw, const Agenda &opt_prop_gas_agenda, const Agenda &fos_y_agenda, const Matrix &fos_angles, const Index &use_mean_scat_data, const Index &fos_n, const Index &fos_i, const Verbosity &verbosity)
void iyFOS (Workspace &ws, Matrix &iy, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, const Tensor3 &iy_transmission, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &stokes_dim, const Vector &f_grid, const Agenda &ppath_step_agenda, const Agenda &emission_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &iy_clearsky_agenda, const Tensor4 &pnd_field, const ArrayOfSingleScatteringData &scat_data_raw, const Agenda &opt_prop_gas_agenda, const Agenda &fos_y_agenda, const Matrix &fos_angles, const Index &use_mean_scat_data, const Index &fos_n, const Index &fos_i, const Verbosity &verbosity)
Variables
const Numeric DEG2RAD
const Numeric RAD2DEG
const Numeric PI
Detailed Description
Workspace functions associated with the FOS scattering scheme.
Author
Patrick Eriksson patri.nosp@m.ck.e.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2010-04-06
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_fos.cc.
Function Documentation
fos_yStandard()
void fos_yStandard (Workspace & ws, Tensor3 & fos_y, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, const Vector & rte_pos, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & stokes_dim, const Vector & f_grid, const Agenda & ppath_step_agenda, const Agenda & emission_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & iy_clearsky_agenda, const Tensor3 & iy_transmission, const Tensor4 & pnd_field, const ArrayOfSingleScatteringData & scat_data_raw, const Agenda & opt_prop_gas_agenda, const Agenda & fos_y_agenda, const Matrix & fos_angles, const Index & use_mean_scat_data, const Index & fos_n, const Index & fos_i, const Verbosity & verbosity)
Definition at line 64 of file m_fos.cc.
References DEG2RAD, iy_clearsky_agendaExecute(), iyFOS(), joker, max, ConstVectorView::nelem(), ConstMatrixView::nrows(), and Tensor3::resize().
iyFOS()
void iyFOS (Workspace & ws, Matrix & iy, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, const Tensor3 & iy_transmission, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & stokes_dim, const Vector & f_grid, const Agenda & ppath_step_agenda, const Agenda & emission_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & iy_clearsky_agenda, const Tensor4 & pnd_field, const ArrayOfSingleScatteringData & scat_data_raw, const Agenda & opt_prop_gas_agenda, const Agenda & fos_y_agenda, const Matrix & fos_angles, const Index & use_mean_scat_data, const Index & fos_n, const Index & fos_i, const Verbosity & verbosity)
Definition at line 257 of file m_fos.cc.
References get_ppath_atmvars(), get_ppath_cloudrtvars(), get_ppath_pnd(), iy_clearsky_agendaExecute(), iy_transmission_mult(), joker, Ppath::l_step, Ppath::los, max, min, mirror_los(), mult(), ConstMatrixView::ncols(), ConstVectorView::nelem(), Ppath::np, ConstMatrixView::nrows(), pha_mat_singleCalc(), PI, Ppath::pos, ppath_calc(), ppath_what_background(), and rte_step_std().
Referenced by fos_yStandard().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
Referenced by fos_yStandard().
PI
const Numeric PI extern
Referenced by iyFOS().
RAD2DEG
const Numeric RAD2DEG extern