ARTS: m_physics.cc File Reference
m_physics.cc File Reference
Workspace methods of physical character.
#include "arts.h"
#include "auto_md.h"
#include "check_input.h"
#include "logic.h"
#include "math_funcs.h"
#include "messages.h"
#include "physics_funcs.h"
Functions
void complex_nWaterLiebe93 (Matrix &complex_n, const Vector &f_grid, const Numeric &t, const Verbosity &verbosity)
WORKSPACE METHOD: complex_nWaterLiebe93.
void emissionPlanck (Vector &emission, const Vector &f, const Numeric &t, const Verbosity &)
WORKSPACE METHOD: emissionPlanck.
void MatrixCBR (Matrix &m, const Index &stokes_dim, const Vector &f, const Verbosity &)
WORKSPACE METHOD: MatrixCBR.
void MatrixPlanck (Matrix &m, const Index &stokes_dim, const Vector &f, const Numeric &t, const Verbosity &verbosity)
WORKSPACE METHOD: MatrixPlanck.
void MatrixUnitIntensity (Matrix &m, const Index &stokes_dim, const Vector &f, const Verbosity &verbosity)
WORKSPACE METHOD: MatrixUnitIntensity.
Variables
const Numeric COSMIC_BG_TEMP
const Numeric TEMP_0_C
Detailed Description
Workspace methods of physical character.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@r.nosp@m.ss.ch.nosp@m.alme.nosp@m.rs.se
Date
2002-08-20
This file includes workspace methods for operations that have some connection to basic physics. Example of methods are:
Setting WSV to hold blackbody radiation.
Conversion to brightness temperature.
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_physics.cc.
Function Documentation
complex_nWaterLiebe93()
void complex_nWaterLiebe93 (Matrix & complex_n, const Vector & f_grid, const Numeric & t, const Verbosity & verbosity)
WORKSPACE METHOD: complex_nWaterLiebe93.
Complex refractive index of liquid water according to Liebe 1993.
The method treats liquid water without salt. Thus, not valid below 10 GHz. Upper frequency limit not known, here set to 1000 GHz. Model parameters taken from Atmlab function epswater93 (by C. Maetzler), which refer to Liebe 1993 without closer specifications.
Temperature must be between 0 and 100 degrees Celsius.
Author
Patrick Eriksson
Parameters
[out] complex_n WS Output
[in] f_grid WS Input
[in] t Generic Input
Definition at line 66 of file m_physics.cc.
References chk_if_in_range(), CREATE_OUT2, CREATE_OUT3, max, min, ConstVectorView::nelem(), Matrix::resize(), and TEMP_0_C.
Referenced by complex_nWaterLiebe93_g().
emissionPlanck()
void emissionPlanck (Vector & emission, const Vector & f_grid, const Numeric & rte_temperature, const Verbosity & verbosity)
WORKSPACE METHOD: emissionPlanck.
Emission source term for LTE.
Sets emission for cases when emission is considered and local thermodynamic equilibrium is valid. The standard definition, in ARTS, of the Planck function is followed and the unit of the returned data is W/(m^2 Hz sr).
Author
Patrick Eriksson
Parameters
[out] emission WS Output
[in] f_grid WS Input
[in] rte_temperature WS Input
Definition at line 110 of file m_physics.cc.
References ConstVectorView::nelem(), planck(), and Vector::resize().
Referenced by emissionPlanck_g().
MatrixCBR()
void MatrixCBR (Matrix & m, const Index & stokes_dim, const Vector & f, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixCBR.
Sets a matrix to hold cosmic background radiation (CBR).
The CBR is assumed to be un-polarized and Stokes components 2-4 are zero. Number of Stokes components, that equals the number of columns in the created matrix, is determined by stokes_dim. The number of rows in the created matrix equals the length of the given frequency vector.
The cosmic radiation is modelled as blackbody radiation for the temperature given by the global constant COSMIC_BG_TEMP, set in the file constants.cc. The frequencies are taken from the generic input vector.
The standard definition, in ARTS, of the Planck function is followed and the unit of the returned data is W/(m3 * Hz * sr).
Author
Patrick Eriksson
Parameters
[out] m Generic output
[in] stokes_dim WS Input
[in] f Generic Input
Definition at line 125 of file m_physics.cc.
References COSMIC_BG_TEMP, ConstVectorView::nelem(), planck(), and Matrix::resize().
Referenced by MatrixCBR_g().
MatrixPlanck()
void MatrixPlanck (Matrix & m, const Index & stokes_dim, const Vector & gin1, const Numeric & gin2, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixPlanck.
Sets a matrix to hold blackbody radiation.
The radiation is assumed to be un-polarized and Stokes components 2-4 are zero. Number of Stokes components, that equals the number of columns in the created matrix, is determined by stokes_dim. The number of rows in the created matrix equals the length of the given frequency vector.
The standard definition, in ARTS, of the Planck function is followed and the unit of the returned data is W/(m3 * Hz * sr).
Author
Patrick Eriksson
Parameters
[out] m Generic output
[in] stokes_dim WS Input
[in] gin1 Generic Input
[in] gin2 Generic Input
Definition at line 147 of file m_physics.cc.
References CREATE_OUT2, ConstVectorView::nelem(), planck(), and Matrix::resize().
Referenced by MatrixPlanck_g().
MatrixUnitIntensity()
void MatrixUnitIntensity (Matrix & m, const Index & stokes_dim, const Vector & f, const Verbosity & verbosity)
WORKSPACE METHOD: MatrixUnitIntensity.
Sets a matrix to hold unpolarised radiation with unit intensity.
Works as MatrixPlanck where the radiation is set to 1.
Author
Patrick Eriksson
Parameters
[out] m Generic output
[in] stokes_dim WS Input
[in] f Generic Input
Definition at line 176 of file m_physics.cc.
References CREATE_OUT2, ConstVectorView::nelem(), and Matrix::resize().
Referenced by MatrixUnitIntensity_g().
Variable Documentation
COSMIC_BG_TEMP
const Numeric COSMIC_BG_TEMP extern
Referenced by MatrixCBR().
TEMP_0_C
const Numeric TEMP_0_C extern
Referenced by complex_nWaterLiebe93().