ARTS: m_rte.cc File Reference
m_rte.cc File Reference
Workspace functions for solving clear sky radiative transfer.
#include <cmath>
#include <stdexcept>
#include "arts.h"
#include "arts_omp.h"
#include "auto_md.h"
#include "check_input.h"
#include "jacobian.h"
#include "logic.h"
#include "math_funcs.h"
#include "messages.h"
#include "montecarlo.h"
#include "physics_funcs.h"
#include "ppath.h"
#include "rte.h"
#include "special_interp.h"
Macros
#define FOR_ANALYTICAL_JACOBIANS_DO(what_to_do)
Functions
void from_dpath_to_dx (MatrixView diy_dx, ConstMatrixView diy_dq, const Numeric &w)
diy_from_path_to_rgrids
void add_extrap (ArrayOfGridPos &gp)
void diy_from_path_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity &jacobian_quantity, ConstTensor3View diy_dpath, const Index &atmosphere_dim, const Ppath &ppath, ConstVectorView ppath_p)
void get_pointers_for_analytical_jacobians (ArrayOfIndex &abs_species_i, ArrayOfIndex &is_t, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfSpeciesTag &abs_species)
Help function for analytical jacobian calculations.
void get_iy_of_background (Workspace &ws, Matrix &iy, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, ConstTensor3View iy_transmission, const Index &jacobian_do, const Ppath &ppath, const Index &atmosphere_dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View t_field, ConstTensor3View z_field, ConstTensor4View vmr_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const Index &stokes_dim, ConstVectorView f_grid, const Agenda &iy_clearsky_agenda, const Agenda &iy_space_agenda, const Agenda &surface_prop_agenda, const Agenda &iy_cloudbox_agenda, const Verbosity &verbosity)
get_iy_of_background
void iyb_calc (Workspace &ws, Vector &iyb, Vector &iyb_error, Index &iy_error_type, Vector &iyb_aux, ArrayOfMatrix &diyb_dx, const Index &imblock, const Index &atmosphere_dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View t_field, ConstTensor3View z_field, ConstTensor4View vmr_field, const Index &cloudbox_on, const Index &stokes_dim, ConstVectorView f_grid, ConstMatrixView sensor_pos, ConstMatrixView sensor_los, ConstVectorView mblock_za_grid, ConstVectorView mblock_aa_grid, const Index &antenna_dim, const Agenda &iy_clearsky_agenda, const String &y_unit, const Index &j_analytical_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfIndex &jacobian_indices, const Verbosity &verbosity)
iyb_calc
void iyBeerLambertStandardClearsky (Workspace &ws, Matrix &iy, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, const Index &iy_agenda_call1, const Tensor3 &iy_transmission, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Tensor3 &wind_u_field, const Tensor3 &wind_v_field, const Tensor3 &wind_w_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &stokes_dim, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const Agenda &ppath_step_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &iy_clearsky_agenda, const Agenda &iy_space_agenda, const Agenda &surface_prop_agenda, const Agenda &iy_cloudbox_agenda, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfIndex &jacobian_indices, const Verbosity &verbosity)
WORKSPACE METHOD: iyBeerLambertStandardClearsky.
void iyBeerLambertStandardCloudbox (Workspace &ws, Matrix &iy, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, const Tensor3 &iy_transmission, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &stokes_dim, const Vector &f_grid, const Agenda &ppath_step_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &iy_clearsky_agenda, const Tensor4 &pnd_field, const Index &use_mean_scat_data, const ArrayOfSingleScatteringData &scat_data_raw, const Agenda &opt_prop_gas_agenda, const Verbosity &verbosity)
WORKSPACE METHOD: iyBeerLambertStandardCloudbox.
void iyEmissionStandardClearsky (Workspace &ws, Matrix &iy, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, const Index &iy_agenda_call1, const Tensor3 &iy_transmission, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Tensor3 &wind_u_field, const Tensor3 &wind_v_field, const Tensor3 &wind_w_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &stokes_dim, const Vector &f_grid, const ArrayOfArrayOfSpeciesTag &abs_species, const Agenda &ppath_step_agenda, const Agenda &emission_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &iy_clearsky_agenda, const Agenda &iy_space_agenda, const Agenda &surface_prop_agenda, const Agenda &iy_cloudbox_agenda, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfIndex &jacobian_indices, const Verbosity &verbosity)
WORKSPACE METHOD: iyEmissionStandardClearsky.
void iyEmissionStandardClearskyBasic (Workspace &ws, Matrix &iy, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Tensor3 &wind_u_field, const Tensor3 &wind_v_field, const Tensor3 &wind_w_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &stokes_dim, const Vector &f_grid, const Agenda &ppath_step_agenda, const Agenda &emission_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &iy_clearsky_basic_agenda, const Agenda &iy_space_agenda, const Agenda &surface_prop_agenda, const Agenda &iy_cloudbox_agenda, const Verbosity &verbosity)
WORKSPACE METHOD: iyEmissionStandardClearskyBasic.
void iyMC (Workspace &ws, Matrix &iy, Matrix &iy_error, Index &iy_error_type, Matrix &iy_aux, ArrayOfTensor3 &diy_dx, const Index &iy_agenda_call1, const Tensor3 &iy_transmission, const Vector &rte_pos, const Vector &rte_los, const Index &jacobian_do, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const Matrix &r_geoid, const Matrix &z_surface, const Index &cloudbox_on, const ArrayOfIndex &cloudbox_limits, const Index &cloudbox_checked, const Index &stokes_dim, const Vector &f_grid, const ArrayOfSingleScatteringData &scat_data_raw, const Agenda &iy_space_agenda, const Agenda &surface_prop_agenda, const Agenda &abs_scalar_gas_agenda, const Agenda &opt_prop_gas_agenda, const Tensor4 &pnd_field, const String &y_unit, const Numeric &mc_std_err, const Index &mc_max_time, const Index &mc_max_iter, const Verbosity &verbosity)
WORKSPACE METHOD: iyMC.
void yCalc (Workspace &ws, Vector &y, Vector &y_f, ArrayOfIndex &y_pol, Matrix &y_pos, Matrix &y_los, Vector &y_error, Vector &y_aux, Matrix &jacobian, const Index &basics_checked, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &t_field, const Tensor3 &z_field, const Tensor4 &vmr_field, const Index &cloudbox_on, const Index &cloudbox_checked, const Index &stokes_dim, const Vector &f_grid, const Matrix &sensor_pos, const Matrix &sensor_los, const Vector &mblock_za_grid, const Vector &mblock_aa_grid, const Index &antenna_dim, const Sparse &sensor_response, const Vector &sensor_response_f, const ArrayOfIndex &sensor_response_pol, const Vector &sensor_response_za, const Vector &sensor_response_aa, const Agenda &iy_clearsky_agenda, const String &y_unit, const Agenda &jacobian_agenda, const Index &jacobian_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfIndex &jacobian_indices, const Verbosity &verbosity)
WORKSPACE METHOD: yCalc.
void y_unitApply (Vector &y, Vector &y_error, Matrix &jacobian, const Vector &y_f, const ArrayOfIndex &y_pol, const String &y_unit, const Verbosity &)
WORKSPACE METHOD: y_unitApply.
void yCalc2 (Workspace &ws, Vector &y, Vector &y_f, ArrayOfIndex &y_pol, Matrix &y_pos, Matrix &y_los, Vector &y_error, Vector &y_aux, Matrix &jacobian, const Index &basics_checked, const Index &atmosphere_dim, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &t_field, const Tensor3 &z_field, const Tensor4 &vmr_field, const Index &cloudbox_on, const Index &cloudbox_checked, const Index &stokes_dim, const Vector &f_grid, const Matrix &sensor_pos, const Matrix &sensor_los, const Vector &mblock_za_grid, const Vector &mblock_aa_grid, const Index &antenna_dim, const Agenda &sensor_response_agenda, const Agenda &iy_clearsky_agenda, const String &y_unit, const Agenda &jacobian_agenda, const Index &jacobian_do, const ArrayOfRetrievalQuantity &jacobian_quantities, const ArrayOfArrayOfIndex &jacobian_indices, const Verbosity &verbosity)
WORKSPACE METHOD: yCalc2.
Variables
const String ABSSPECIES_MAINTAG
const String TEMPERATURE_MAINTAG
Detailed Description
Workspace functions for solving clear sky radiative transfer.
Author
Patrick Eriksson patri.nosp@m.ck.e.nosp@m.rikss.nosp@m.on@c.nosp@m.halme.nosp@m.rs.s.nosp@m.e
Date
2002-05-11
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_rte.cc.
Macro Definition Documentation
FOR_ANALYTICAL_JACOBIANS_DO
#define FOR_ANALYTICAL_JACOBIANS_DO (what_to_do)
Value:
  for( Index iq=0; iq<jacobian_quantities.nelem(); iq++ ) \
    { \
      if( jacobian_quantities[iq].Analytical() ) \
        { what_to_do } \
    }
Definition at line 64 of file m_rte.cc.
Function Documentation
add_extrap()
void add_extrap (ArrayOfGridPos & gp)
Definition at line 110 of file m_rte.cc.
References Array< base >::nelem().
Referenced by diy_from_path_to_rgrids().
diy_from_path_to_rgrids()
void diy_from_path_to_rgrids (Tensor3View diy_dx, const RetrievalQuantity & jacobian_quantity, ConstTensor3View diy_dpath, const Index & atmosphere_dim, const Ppath & ppath, ConstVectorView ppath_p)
Definition at line 127 of file m_rte.cc.
References add_extrap(), from_dpath_to_dx(), gridpos(), RetrievalQuantity::Grids(), joker, ConstVectorView::nelem(), Ppath::np, p2gridpos(), and Ppath::pos.
Referenced by iyBeerLambertStandardClearsky(), and iyEmissionStandardClearsky().
from_dpath_to_dx()
void from_dpath_to_dx (MatrixView diy_dx, ConstMatrixView diy_dq, const Numeric & w)
diy_from_path_to_rgrids
Maps jacobian data for points along the propagation path, to jacobian retrieval grid data.
Parameters
diy_dx Out: Jacobians for selected retrieval grids.
jacobian_quantity As the WSV.
diy_dpath Jacobians along the propagation path.
atmosphere_dim As the WSV.
ppath As the WSV.
ppath_p The pressure at each ppath point.
Author
Patrick Eriksson
Date
2009-10-08
Definition at line 96 of file m_rte.cc.
References ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by diy_from_path_to_rgrids().
get_iy_of_background()
void get_iy_of_background (Workspace & ws, Matrix & iy, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, ConstTensor3View iy_transmission, const Index & jacobian_do, const Ppath & ppath, const Index & atmosphere_dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View t_field, ConstTensor3View z_field, ConstTensor4View vmr_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const Index & stokes_dim, ConstVectorView f_grid, const Agenda & iy_clearsky_agenda, const Agenda & iy_space_agenda, const Agenda & surface_prop_agenda, const Agenda & iy_cloudbox_agenda, const Verbosity & verbosity)
get_iy_of_background
Determines iy of the "background" of a propgation path.
The task is to determine iy and related variables for the background, or to continue the raditiave calculations "backwards". The details here depends on the method selected for the agendas.
Each background is handled by an agenda. Several of these agandes can involve recursive calls of iy_clearsky_agenda. It is also allowed to input iy_clearsky_basic_agenda instead of iy_clearsky_agenda*.
Parameters
ws Out: The workspace
iy Out: As the WSV.
iy_error Out: As the WSV.
iy_error_type Out: As the WSV.
iy_aux Out: As the WSV.
diy_aux Out: As the WSV.
iy_transmission As the WSV.
jacobian_do As the WSV.
ppath As the WSV.
atmosphere_dim As the WSV.
p_grid As the WSV.
lat_grid As the WSV.
lon_grid As the WSV.
t_field As the WSV.
z_field As the WSV.
vmr_field As the WSV.
cloudbox_on As the WSV.
stokes_dim As the WSV.
f_grid As the WSV.
iy_clearsky_agenda As the WSV or iy_clearsky_basic_agenda.
iy_space_agenda As the WSV.
surface_prop_agenda As the WSV.
iy_cloudbox_agenda As the WSV.
Author
Patrick Eriksson
Date
2009-10-08
Definition at line 360 of file m_rte.cc.
References Ppath::background, CREATE_OUT1, CREATE_OUT3, Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, gridpos_copy(), iy_clearsky_agendaExecute(), iy_clearsky_basic_agendaExecute(), iy_cloudbox_agendaExecute(), iy_space_agendaExecute(), iy_transmission_mult(), joker, Ppath::los, max, min, Agenda::name(), ConstTensor4View::nbooks(), ConstMatrixView::ncols(), ConstTensor4View::ncols(), ConstVectorView::nelem(), Ppath::np, ConstTensor3View::npages(), ConstTensor4View::npages(), ConstMatrixView::nrows(), ConstTensor4View::nrows(), Ppath::pos, ppath_what_background(), Vector::resize(), sign(), surface_calc(), surface_prop_agendaExecute(), and surfacetilt().
Referenced by iyBeerLambertStandardClearsky(), iyEmissionStandardClearsky(), and iyEmissionStandardClearskyBasic().
get_pointers_for_analytical_jacobians()
void get_pointers_for_analytical_jacobians (ArrayOfIndex & abs_species_i, ArrayOfIndex & is_t, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfSpeciesTag & abs_species)
Help function for analytical jacobian calculations.
The function determines which terms in jacobian_quantities that are analytical absorption species and temperature jacobians.
abs_species_i* and is_t shall be sized to have the same length as jacobian_quantities. For analytical absorption species jacobians, abs_species_i is set to the matching index in abs_species*. Otherwise, to -1. For analytical temperature jacobians, is_t is set to 1. Otherwise to 0.
Parameters
abs_species_i Out: Matching index in abs_species
is_t Out: Flag for: Is a temperature jacobian?
jacobian_quantities As the WSV.
abs_species As the WSV.
Author
Patrick Eriksson
Date
2009-10-07
Definition at line 286 of file m_rte.cc.
References ABSSPECIES_MAINTAG, array_species_tag_from_string(), chk_contains(), FOR_ANALYTICAL_JACOBIANS_DO, and TEMPERATURE_MAINTAG.
Referenced by iyBeerLambertStandardClearsky(), and iyEmissionStandardClearsky().
iyb_calc()
void iyb_calc (Workspace & ws, Vector & iyb, Vector & iyb_error, Index & iy_error_type, Vector & iyb_aux, ArrayOfMatrix & diyb_dx, const Index & imblock, const Index & atmosphere_dim, ConstVectorView p_grid, ConstVectorView lat_grid, ConstVectorView lon_grid, ConstTensor3View t_field, ConstTensor3View z_field, ConstTensor4View vmr_field, const Index & cloudbox_on, const Index & stokes_dim, ConstVectorView f_grid, ConstMatrixView sensor_pos, ConstMatrixView sensor_los, ConstVectorView mblock_za_grid, ConstVectorView mblock_aa_grid, const Index & antenna_dim, const Agenda & iy_clearsky_agenda, const String & y_unit, const Index & j_analytical_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfIndex & jacobian_indices, const Verbosity & verbosity)
iyb_calc
Calculation of pencil beam monochromatic spectra for 1 measurement block.
All in- and output variables as the WSV with the same name.
Author
Patrick Eriksson
Date
2009-10-16
Definition at line 588 of file m_rte.cc.
References abs, apply_y_unit(), apply_y_unit2(), CREATE_OUT0, exit_or_rethrow(), FOR_ANALYTICAL_JACOBIANS_DO, iy_clearsky_agendaExecute(), joker, map_daa(), ConstMatrixView::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Vector::resize(), and sign().
Referenced by jacobianCalcAbsSpeciesPerturbations(), jacobianCalcPointingZaRecalc(), jacobianCalcTemperaturePerturbations(), yCalc(), and yCalc2().
iyBeerLambertStandardClearsky()
void iyBeerLambertStandardClearsky (Workspace & ws, Matrix & iy, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, const Index & iy_agenda_call1, const Tensor3 & iy_transmission, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Tensor3 & wind_u_field, const Tensor3 & wind_v_field, const Tensor3 & wind_w_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & stokes_dim, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const Agenda & ppath_step_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & iy_clearsky_agenda, const Agenda & iy_space_agenda, const Agenda & surface_prop_agenda, const Agenda & iy_cloudbox_agenda, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfIndex & jacobian_indices, const Verbosity & verbosity)
WORKSPACE METHOD: iyBeerLambertStandardClearsky.
Standard method for handling transmission measurements.
Designed to be part of iy_clearsky_agenda. That is, only valid outside the cloudbox (no scattering or polarised absorption).
This method works exactly as iyEmissionStandardClearsky, but does add any emission. In fact, the latter method with emission_agenda set to return zero would give exactly the same result as this WSM. For propagation paths above the surface, the result is the output of iy_space_agenda times the (vector) transmission through the atmosphere (i.e. standard Beer-Lambert).
If the propagation paths intercepts with the surface, the surface variables are used as for iyEmissionStandardClearsky, and surface_emission* should probably be set to 0. Multiple-beams will be followed if surface_los has length > 1.
iy_aux* is not set.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_error WS Output
[out] iy_error_type WS Output
[out] iy_aux WS Output
[out] diy_dx WS Output
[in] iy_agenda_call1 WS Input
[in] iy_transmission WS Input
[in] rte_pos WS Input
[in] rte_los WS Input
[in] jacobian_do WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] z_field WS Input
[in] t_field WS Input
[in] vmr_field WS Input
[in] wind_u_field WS Input
[in] wind_v_field WS Input
[in] wind_w_field WS Input
[in] r_geoid WS Input
[in] z_surface WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] abs_species WS Input
[in] ppath_step_agenda WS Input
[in] abs_scalar_gas_agenda WS Input
[in] iy_clearsky_agenda WS Input
[in] iy_space_agenda WS Input
[in] surface_prop_agenda WS Input
[in] iy_cloudbox_agenda WS Input
[in] jacobian_quantities WS Input
[in] jacobian_indices WS Input
Definition at line 789 of file m_rte.cc.
References diy_from_path_to_rgrids(), FOR_ANALYTICAL_JACOBIANS_DO, get_iy_of_background(), get_pointers_for_analytical_jacobians(), get_ppath_atmvars(), get_ppath_rtvars(), iy_transmission_for_scalar_tau(), iy_transmission_mult_scalar_tau(), joker, Ppath::l_step, mult(), Array< base >::nelem(), ConstVectorView::nelem(), Ppath::np, ppath_calc(), Vector::resize(), transpose(), and vmrunitscf().
Referenced by iyBeerLambertStandardClearsky_g().
iyBeerLambertStandardCloudbox()
void iyBeerLambertStandardCloudbox (Workspace & ws, Matrix & iy, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, const Tensor3 & iy_transmission, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & stokes_dim, const Vector & f_grid, const Agenda & ppath_step_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & iy_clearsky_agenda, const Tensor4 & pnd_field, const Index & use_mean_scat_data, const ArrayOfSingleScatteringData & scat_data_raw, const Agenda & opt_prop_gas_agenda, const Verbosity & verbosity)
WORKSPACE METHOD: iyBeerLambertStandardCloudbox.
Standard method for handling transmission measurements.
Designed to be part of iy_cloudbox_agenda, and is thus a complement to iyBeerLambertStandardClearsky.
Only scattering out of the propagation path is considered. Thus, this method could be used for direct solar occultation measurements but clearly not for observations of scattered solar radiation.
For regions of no scattering there is a marginal difference between running this method and the corresponding pure clear-sky agenda, and there is not critical to set the cloudbox limits in a "tight" manner.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_error WS Output
[out] iy_error_type WS Output
[out] iy_aux WS Output
[out] diy_dx WS Output
[in] iy_transmission WS Input
[in] rte_pos WS Input
[in] rte_los WS Input
[in] jacobian_do WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] z_field WS Input
[in] t_field WS Input
[in] vmr_field WS Input
[in] r_geoid WS Input
[in] z_surface WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] ppath_step_agenda WS Input
[in] abs_scalar_gas_agenda WS Input
[in] iy_clearsky_agenda WS Input
[in] pnd_field WS Input
[in] use_mean_scat_data WS Input
[in] scat_data_raw WS Input
[in] opt_prop_gas_agenda WS Input
Definition at line 1097 of file m_rte.cc.
References get_ppath_atmvars(), get_ppath_cloudrtvars(), get_ppath_pnd(), iy_clearsky_agendaExecute(), iy_transmission_mult(), joker, Ppath::los, mult(), ConstVectorView::nelem(), Ppath::np, Ppath::pos, ppath_calc(), and ppath_what_background().
Referenced by iyBeerLambertStandardCloudbox_g().
iyEmissionStandardClearsky()
void iyEmissionStandardClearsky (Workspace & ws, Matrix & iy, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, const Index & iy_agenda_call1, const Tensor3 & iy_transmission, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Tensor3 & wind_u_field, const Tensor3 & wind_v_field, const Tensor3 & wind_w_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & stokes_dim, const Vector & f_grid, const ArrayOfArrayOfSpeciesTag & abs_species, const Agenda & ppath_step_agenda, const Agenda & emission_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & iy_clearsky_agenda, const Agenda & iy_space_agenda, const Agenda & surface_prop_agenda, const Agenda & iy_cloudbox_agenda, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfIndex & jacobian_indices, const Verbosity & verbosity)
WORKSPACE METHOD: iyEmissionStandardClearsky.
Standard method for radiative transfer calculations with emission.
Designed to be part of iy_clearsky_agenda. That is, only valid outside the cloudbox (no scattering or polarised absorption). Assumes local thermodynamic equilibrium for emission.
The overall strategy is to take the average of the absorption and the emission source function at the end points of each step of the propagation path. See further the user guide. iy_error is considered to be 0.
The WSV iy_aux is set to hold the transmission, if the radiative background is space or the surface. That is, as long as there is no intersection with a cloudbox, the method sets iy_aux to the transmission through the atmosphere either down to the surface, or to the top of the atmosphere. The treatment of iy_aux if there is an interesection with the cloudbox depends on the scattering method selected.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_error WS Output
[out] iy_error_type WS Output
[out] iy_aux WS Output
[out] diy_dx WS Output
[in] iy_agenda_call1 WS Input
[in] iy_transmission WS Input
[in] rte_pos WS Input
[in] rte_los WS Input
[in] jacobian_do WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] z_field WS Input
[in] t_field WS Input
[in] vmr_field WS Input
[in] wind_u_field WS Input
[in] wind_v_field WS Input
[in] wind_w_field WS Input
[in] r_geoid WS Input
[in] z_surface WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] abs_species WS Input
[in] ppath_step_agenda WS Input
[in] emission_agenda WS Input
[in] abs_scalar_gas_agenda WS Input
[in] iy_clearsky_agenda WS Input
[in] iy_space_agenda WS Input
[in] surface_prop_agenda WS Input
[in] iy_cloudbox_agenda WS Input
[in] jacobian_quantities WS Input
[in] jacobian_indices WS Input
Definition at line 1240 of file m_rte.cc.
References diy_from_path_to_rgrids(), FOR_ANALYTICAL_JACOBIANS_DO, get_iy_of_background(), get_pointers_for_analytical_jacobians(), get_ppath_atmvars(), get_ppath_rtvars(), iy_transmission_for_scalar_tau(), iy_transmission_mult_scalar_tau(), joker, Ppath::l_step, mult(), Array< base >::nelem(), ConstVectorView::nelem(), Ppath::np, ppath_calc(), ppath_what_background(), Vector::resize(), Matrix::resize(), transpose(), and vmrunitscf().
Referenced by iyEmissionStandardClearsky_g().
iyEmissionStandardClearskyBasic()
void iyEmissionStandardClearskyBasic (Workspace & ws, Matrix & iy, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Tensor3 & wind_u_field, const Tensor3 & wind_v_field, const Tensor3 & wind_w_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & stokes_dim, const Vector & f_grid, const Agenda & ppath_step_agenda, const Agenda & emission_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & iy_clearsky_basic_agenda, const Agenda & iy_space_agenda, const Agenda & surface_prop_agenda, const Agenda & iy_cloudbox_agenda, const Verbosity & verbosity)
WORKSPACE METHOD: iyEmissionStandardClearskyBasic.
As iyEmissionStandardClearsky, but lacking support for auxilary variables and jacobian calculations.
Designed to be part of iy_clearsky_basic_agenda. See further iyEmissionStandardClearsky*.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[in] rte_pos WS Input
[in] rte_los WS Input
[in] jacobian_do WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] z_field WS Input
[in] t_field WS Input
[in] vmr_field WS Input
[in] wind_u_field WS Input
[in] wind_v_field WS Input
[in] wind_w_field WS Input
[in] r_geoid WS Input
[in] z_surface WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] ppath_step_agenda WS Input
[in] emission_agenda WS Input
[in] abs_scalar_gas_agenda WS Input
[in] iy_clearsky_basic_agenda WS Input
[in] iy_space_agenda WS Input
[in] surface_prop_agenda WS Input
[in] iy_cloudbox_agenda WS Input
Definition at line 1612 of file m_rte.cc.
References get_iy_of_background(), get_ppath_atmvars(), get_ppath_rtvars(), ConstVectorView::nelem(), Ppath::np, and ppath_calc().
Referenced by iyEmissionStandardClearskyBasic_g().
iyMC()
void iyMC (Workspace & ws, Matrix & iy, Matrix & iy_error, Index & iy_error_type, Matrix & iy_aux, ArrayOfTensor3 & diy_dx, const Index & iy_agenda_call1, const Tensor3 & iy_transmission, const Vector & rte_pos, const Vector & rte_los, const Index & jacobian_do, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const Matrix & r_geoid, const Matrix & z_surface, const Index & cloudbox_on, const ArrayOfIndex & cloudbox_limits, const Index & cloudbox_checked, const Index & stokes_dim, const Vector & f_grid, const ArrayOfSingleScatteringData & scat_data_raw, const Agenda & iy_space_agenda, const Agenda & surface_prop_agenda, const Agenda & abs_scalar_gas_agenda, const Agenda & opt_prop_gas_agenda, const Tensor4 & pnd_field, const String & y_unit, const Numeric & mc_std_err, const Index & mc_max_time, const Index & mc_max_iter, const Verbosity & verbosity)
WORKSPACE METHOD: iyMC.
Interface to Monte Carlo part for iy_clearsky_agenda.
Basically an interface to MCGeneral for doing monochromatic pencil beam calculations. This functions allows Monte Carlo (MC) calculations for sets of frequencies and sensor pos/los in a single run. Sensor responses can be included in the standard manner (through yCalc).
MC unit is set as for MCGeneral. No antenna pattern is included.
This function does not apply the MC approach when it comes to sensor properties. These properties are not considered when tracking photons, which is done in MCGeneral (but then only for the antenna pattern).
The MC calculation errors are all assumed be uncorrelated and each have a normal distribution. These properties are of relevance when weighting the errors with the sensor repsonse matrix. The seed is reset for each call of MCGeneral to obtain uncorrelated errors.
MC control arguments (mc_std_err, mc_max_time, mc_max_iter and mc_z_field_is_1D) as for MCGeneral. The arguments are applied for each monochromatic pencil beam calculation individually.
iy_aux* is not set.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] iy WS Output
[out] iy_error WS Output
[out] iy_error_type WS Output
[out] iy_aux WS Output
[out] diy_dx WS Output
[in] iy_agenda_call1 WS Input
[in] iy_transmission WS Input
[in] rte_pos WS Input
[in] rte_los WS Input
[in] jacobian_do WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] z_field WS Input
[in] t_field WS Input
[in] vmr_field WS Input
[in] r_geoid WS Input
[in] z_surface WS Input
[in] cloudbox_on WS Input
[in] cloudbox_limits WS Input
[in] cloudbox_checked WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] scat_data_raw WS Input
[in] iy_space_agenda WS Input
[in] surface_prop_agenda WS Input
[in] abs_scalar_gas_agenda WS Input
[in] opt_prop_gas_agenda WS Input
[in] pnd_field WS Input
[in] y_unit WS Input
[in] mc_std_err WS Input
[in] mc_max_time WS Input
[in] mc_max_iter WS Input
Definition at line 1731 of file m_rte.cc.
References invrayjean(), joker, MCGeneral(), MCSetSeedFromTime(), ConstTensor3View::ncols(), ConstVectorView::nelem(), Matrix::resize(), scat_data_monoCalc(), and MCAntenna::set_pencil_beam().
Referenced by iyMC_g().
y_unitApply()
void y_unitApply (Vector & y, Vector & y_error, Matrix & jacobian, const Vector & y_f, const ArrayOfIndex & y_pol, const String & y_unit, const Verbosity & verbosity)
WORKSPACE METHOD: y_unitApply.
Conversion to other spectral units.
Any conversion to brightness temperature is normally made inside yCalc*. This method makes it possible to also make this conversion after yCalc, but with restrictions for jacobian.
The method handles y, y_error and jacobian in parallel, where the two last variables are only considered if they are set. The input data must be in original radiance units. A completely stringent check of this can not be performed.
The method can not be used with jacobian quantities that are not obtained through radiative transfer calculations. One example on quantity that can not be handled is jacobianAddPolyfit.
If you are using this method, y_unit should be set to "1" when calling yCalc, and be changed before calling this method.
See further y_unit.
Author
Patrick Eriksson
Parameters
[out] y WS Output
[out] y_error WS Output
[out] jacobian WS Output
[in] y_f WS Input
[in] y_pol WS Input
[in] y_unit WS Input
Definition at line 2156 of file m_rte.cc.
References apply_y_unit(), apply_y_unit2(), joker, max, ConstMatrixView::ncols(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and transpose().
Referenced by y_unitApply_g().
yCalc()
void yCalc (Workspace & ws, Vector & y, Vector & y_f, ArrayOfIndex & y_pol, Matrix & y_pos, Matrix & y_los, Vector & y_error, Vector & y_aux, Matrix & jacobian, const Index & basics_checked, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & t_field, const Tensor3 & z_field, const Tensor4 & vmr_field, const Index & cloudbox_on, const Index & cloudbox_checked, const Index & stokes_dim, const Vector & f_grid, const Matrix & sensor_pos, const Matrix & sensor_los, const Vector & mblock_za_grid, const Vector & mblock_aa_grid, const Index & antenna_dim, const Sparse & sensor_response, const Vector & sensor_response_f, const ArrayOfIndex & sensor_response_pol, const Vector & sensor_response_za, const Vector & sensor_response_aa, const Agenda & iy_clearsky_agenda, const String & y_unit, const Agenda & jacobian_agenda, const Index & jacobian_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfIndex & jacobian_indices, const Verbosity & verbosity)
WORKSPACE METHOD: yCalc.
Calculation of complete measurement vectors (y).
The method performs radiative transfer calculations from a sensor perspective. Radiative transfer calculations are performed for monochromatic pencil beams, following iy_clearsky_agenda and associated agendas. Obtained radiances are weighted together by sensor_response*, to include the characteristics of the sensor. The measurement vector obtained can contain anything from a single frequency value to a series of measurement scans (each consisting of a series of spectra), all depending on the settings. Spectra and jacobians are calculated in parallel.
The unit of output radiances and jacobians follow y_unit. The conversion is applied on monochromatic pencil beam values. That is, before any sensor responses have been included. The frequency, polarisation etc. for each measurement value is given by y_f, y_pol etc. No unit conversion is applied for y_aux*.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] y WS Output
[out] y_f WS Output
[out] y_pol WS Output
[out] y_pos WS Output
[out] y_los WS Output
[out] y_error WS Output
[out] y_aux WS Output
[out] jacobian WS Output
[in] basics_checked WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] t_field WS Input
[in] z_field WS Input
[in] vmr_field WS Input
[in] cloudbox_on WS Input
[in] cloudbox_checked WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] sensor_pos WS Input
[in] sensor_los WS Input
[in] mblock_za_grid WS Input
[in] mblock_aa_grid WS Input
[in] antenna_dim WS Input
[in] sensor_response WS Input
[in] sensor_response_f WS Input
[in] sensor_response_pol WS Input
[in] sensor_response_za WS Input
[in] sensor_response_aa WS Input
[in] iy_clearsky_agenda WS Input
[in] y_unit WS Input
[in] jacobian_agenda WS Input
[in] jacobian_do WS Input
[in] jacobian_quantities WS Input
[in] jacobian_indices WS Input
Definition at line 1856 of file m_rte.cc.
References chk_if_in_range(), chk_if_increasing(), FOR_ANALYTICAL_JACOBIANS_DO, get_rowindex_for_mblock(), Range::get_start(), iyb_calc(), jacobian_agendaExecute(), joker, max, min, mult(), ConstMatrixView::ncols(), Sparse::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Sparse::nrows(), Vector::resize(), and Matrix::resize().
Referenced by yCalc_g().
yCalc2()
void yCalc2 (Workspace & ws, Vector & y, Vector & y_f, ArrayOfIndex & y_pol, Matrix & y_pos, Matrix & y_los, Vector & y_error, Vector & y_aux, Matrix & jacobian, const Index & basics_checked, const Index & atmosphere_dim, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & t_field, const Tensor3 & z_field, const Tensor4 & vmr_field, const Index & cloudbox_on, const Index & cloudbox_checked, const Index & stokes_dim, const Vector & f_grid, const Matrix & sensor_pos, const Matrix & sensor_los, const Vector & mblock_za_grid, const Vector & mblock_aa_grid, const Index & antenna_dim, const Agenda & sensor_response_agenda, const Agenda & iy_clearsky_agenda, const String & y_unit, const Agenda & jacobian_agenda, const Index & jacobian_do, const ArrayOfRetrievalQuantity & jacobian_quantities, const ArrayOfArrayOfIndex & jacobian_indices, const Verbosity & verbosity)
WORKSPACE METHOD: yCalc2.
Calculation of complete measurement vectors (y).
The method performs radiative transfer calculations from a sensor perspective. Radiative transfer calculations are performed for monochromatic pencil beams, following iy_clearsky_agenda and associated agendas. Obtained radiances are weighted together by sensor_response*, to include the characteristics of the sensor. The measurement vector obtained can contain anything from a single frequency value to a series of measurement scans (each consisting of a series of spectra), all depending on the settings. Spectra and jacobians are calculated in parallel.
The unit of output radiances and jacobians follow y_unit. The conversion is applied on monochromatic pencil beam values. That is, before any sensor responses have been included. The frequency, polarisation etc. for each measurement value is given by y_f, y_pol etc. No unit conversion is applied for y_aux*.
Author
Patrick Eriksson
Parameters
[in,out] ws Workspace
[out] y WS Output
[out] y_f WS Output
[out] y_pol WS Output
[out] y_pos WS Output
[out] y_los WS Output
[out] y_error WS Output
[out] y_aux WS Output
[out] jacobian WS Output
[in] basics_checked WS Input
[in] atmosphere_dim WS Input
[in] p_grid WS Input
[in] lat_grid WS Input
[in] lon_grid WS Input
[in] t_field WS Input
[in] z_field WS Input
[in] vmr_field WS Input
[in] cloudbox_on WS Input
[in] cloudbox_checked WS Input
[in] stokes_dim WS Input
[in] f_grid WS Input
[in] sensor_pos WS Input
[in] sensor_los WS Input
[in] mblock_za_grid WS Input
[in] mblock_aa_grid WS Input
[in] antenna_dim WS Input
[in] sensor_response_agenda WS Input
[in] iy_clearsky_agenda WS Input
[in] y_unit WS Input
[in] jacobian_agenda WS Input
[in] jacobian_do WS Input
[in] jacobian_quantities WS Input
[in] jacobian_indices WS Input
Definition at line 2318 of file m_rte.cc.
References chk_if_in_range(), chk_if_increasing(), FOR_ANALYTICAL_JACOBIANS_DO, iyb_calc(), jacobian_agendaExecute(), joker, max, min, mult(), ConstMatrixView::ncols(), Sparse::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), Sparse::nrows(), Vector::resize(), Matrix::resize(), and sensor_response_agendaExecute().
Referenced by yCalc2_g().
Variable Documentation
ABSSPECIES_MAINTAG
const String ABSSPECIES_MAINTAG extern
Referenced by get_pointers_for_analytical_jacobians().
TEMPERATURE_MAINTAG
const String TEMPERATURE_MAINTAG extern
Referenced by get_pointers_for_analytical_jacobians().