ARTS: m_refraction.cc File Reference
m_refraction.cc File Reference
Workspace methods releated to refraction.
#include "absorption.h"
#include "arts.h"
#include "check_input.h"
#include "matpackI.h"
#include "messages.h"
#include "refraction.h"
#include "special_interp.h"
#include "abs_species_tags.h"
Functions
void refr_indexIR (Numeric &refr_index, const Numeric &a_pressure, const Numeric &a_temperature, const Vector &a_vmr_list, const Verbosity &)
WORKSPACE METHOD: refr_indexIR.
void refr_indexThayer (Numeric &refr_index, const Numeric &a_pressure, const Numeric &a_temperature, const Vector &a_vmr_list, const ArrayOfArrayOfSpeciesTag &abs_species, const Verbosity &)
WORKSPACE METHOD: refr_indexThayer.
void refr_indexUnit (Numeric &refr_index, const Verbosity &)
WORKSPACE METHOD: refr_indexUnit.
Detailed Description
Workspace methods releated to refraction.
Author
Patrick Eriksson Patri.nosp@m.ck.E.nosp@m.rikss.nosp@m.on@r.nosp@m.ss.ch.nosp@m.alme.nosp@m.rs.se
Date
2003-01-09
These functions are listed in the doxygen documentation as entries of the file auto_md.h.
Definition in file m_refraction.cc.
Function Documentation
refr_indexIR()
void refr_indexIR (Numeric & refr_index, const Numeric & rte_pressure, const Numeric & rte_temperature, const Vector & rte_vmr_list, const Verbosity & verbosity)
WORKSPACE METHOD: refr_indexIR.
Calculates the IR refractive index due to gases in the Earth's atmosphere.
Only refractivity of dry air is considered. The formula used is contributed by Michael Hoefner, Forschungszentrum Karlsruhe.
Author
Mattias Ekstrom
Parameters
[out] refr_index WS Output
[in] rte_pressure WS Input
[in] rte_temperature WS Input
[in] rte_vmr_list WS Input
Definition at line 58 of file m_refraction.cc.
References ConstVectorView::nelem(), and refr_index_ir().
Referenced by refr_indexIR_g().
refr_indexThayer()
void refr_indexThayer (Numeric & refr_index, const Numeric & rte_pressure, const Numeric & rte_temperature, const Vector & rte_vmr_list, const ArrayOfArrayOfSpeciesTag & abs_species, const Verbosity & verbosity)
WORKSPACE METHOD: refr_indexThayer.
Calculates the microwave refractive index due to gases in the Earth's atmosphere.
The refractivity of dry air and water vapour is summed. All other gases are assumed to have a negligible contribution.
The parameterisation of Thayer (Radio Science, 9, 803-807, 1974) is used. See also Eq. 3 and 5 of Solheim et al. (JGR, 104, pp. 9664).
Author
Patrick Eriksson
Parameters
[out] refr_index WS Output
[in] rte_pressure WS Input
[in] rte_temperature WS Input
[in] rte_vmr_list WS Input
[in] abs_species WS Input
Definition at line 74 of file m_refraction.cc.
References find_first_species_tg(), Array< base >::nelem(), ConstVectorView::nelem(), refr_index_thayer_1974(), and species_index_from_species_name().
Referenced by refr_indexThayer_g().
refr_indexUnit()
void refr_indexUnit (Numeric & refr_index, const Verbosity & verbosity)
WORKSPACE METHOD: refr_indexUnit.
Sets the refractive index to 1.
If this method is used, the obtained path should be identical to the geomtrical path.
Author
Patrick Eriksson
Parameters
[out] refr_index WS Output
Definition at line 98 of file m_refraction.cc.
Referenced by refr_indexUnit_g().