ARTS: mc_interp.cc File Reference
mc_interp.cc File Reference
Interpolation classes and functions created for use within Monte Carlo scattering simulations.
#include "mc_interp.h"
#include "logic.h"
#include "montecarlo.h"
Functions
ostream & operator<< (ostream &os, const SLIData2 &)
void interp (MatrixView tia, ConstVectorView itw, const ArrayOfMatrix &a, const GridPos &tc)
Red 1D Interpolate.
void interp (VectorView tia, ConstVectorView itw, const ArrayOfVector &a, const GridPos &tc)
Red 1D Interpolate.
void interp_scat_angle_temperature (VectorView pha_mat_int, Numeric &theta_rad, const SingleScatteringData &scat_data, const Numeric &za_sca, const Numeric &aa_sca, const Numeric &za_inc, const Numeric &aa_inc, const Numeric &rte_temperature)
void interpTArray (Matrix &T, Vector &K_abs, Numeric &temperature, MatrixView &K, Vector &rte_pos, Vector &rte_los, VectorView &pnd_vec, const ArrayOfMatrix &TArray, const ArrayOfMatrix &ext_matArray, const ArrayOfVector &abs_vecArray, const Vector &t_ppath, const Matrix &pnd_ppath, const Vector &cum_l_step, const Numeric &pathlength, const Index &stokes_dim, const Ppath &ppath)
interpTarray
Detailed Description
Interpolation classes and functions created for use within Monte Carlo scattering simulations.
Author
Cory Davis cory@.nosp@m.met..nosp@m.ed.ac.nosp@m..uk
Date
2005-02-28
Definition in file mc_interp.cc.
Function Documentation
interp() [1/2]
void interp (MatrixView tia, ConstVectorView itw, const ArrayOfMatrix & a, const GridPos & tc)
Red 1D Interpolate.
This is a slight modifiaction of Stefan's code to do 1_D interpolation to get a Matrix from an array of Matrices
The dimension of itw must be consistent with the dimension of the interpolation (2^n).
Parameters
[out] tia Interpolated value.
[in] itw Interpolation weights.
[in] a The field to interpolate.(ArrayOfMatrix)
[in] tc The grid position for the column dimension.
Author
Cory Davis (modified original code by Stefan Buehler)
Date
2003-06-19
Definition at line 111 of file mc_interp.cc.
References DEBUG_ONLY, GridPos::idx, is_same_within_epsilon(), is_size(), ConstMatrixView::ncols(), ConstMatrixView::nrows(), ConstVectorView::sum(), and sum_check_epsilon.
Referenced by interp_scat_angle_temperature(), SLIData2::interpolate(), and interpTArray().
interp() [2/2]
void interp (VectorView tia, ConstVectorView itw, const ArrayOfVector & a, const GridPos & tc)
Red 1D Interpolate.
This is a slight modifiaction of Stefan's code to do 1_D interpolation to get a Vector from an array of Vectors
The dimension of itw must be consistent with the dimension of the interpolation (2^n).
Parameters
[out] tia Interpolated value.
[in] itw Interpolation weights.
[in] a The field to interpolate. (ArrayOfVector)
[in] tc The grid position for the column dimension.
Author
Cory Davis (modified original code by Stefan Buehler)
Date
2003-06-19
Definition at line 158 of file mc_interp.cc.
References DEBUG_ONLY, GridPos::idx, is_same_within_epsilon(), is_size(), Array< base >::nelem(), ConstVectorView::nelem(), ConstVectorView::sum(), and sum_check_epsilon.
interp_scat_angle_temperature()
void interp_scat_angle_temperature (VectorView pha_mat_int, Numeric & theta_rad, const SingleScatteringData & scat_data, const Numeric & za_sca, const Numeric & aa_sca, const Numeric & za_inc, const Numeric & aa_inc, const Numeric & rte_temperature)
Definition at line 183 of file mc_interp.cc.
References abs, DEG2RAD, gridpos(), interp(), interpweights(), joker, ConstTensor7View::ncols(), ConstVectorView::nelem(), SingleScatteringData::pha_mat_data, PI, RAD2DEG, SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
Referenced by pha_mat_singleExtract().
interpTArray()
void interpTArray (Matrix & T, Vector & K_abs, Numeric & temperature, MatrixView & K, Vector & rte_pos, Vector & rte_los, VectorView & pnd_vec, const ArrayOfMatrix & TArray, const ArrayOfMatrix & ext_matArray, const ArrayOfVector & abs_vecArray, const Vector & t_ppath, const Matrix & pnd_ppath, const Vector & cum_l_step, const Numeric & pathlength, const Index & stokes_dim, const Ppath & ppath)
interpTarray
Interpolates several arrays calculated by TarrayCalc to give values at a given pathlength
Parameters
[out] T transmittance matrix (I may have made this term up).
[out] K_abs absorption coefficient vector
[out] temperature temperature
[out] K extinction matrix at interpolation point
[out] rte_pos position at pathlength along ppath
[out] rte_los LOS at pathlength along ppath
[in] pnd_vec pnd vector
[in] TArray array of transmittance matrices
[in] ext_matArray array of extinction matrices
[in] abs_vecArray array of absorption coefficients
[in] t_ppath array of temperatures
[in] pnd_ppath array of pressures
[in] cum_l_step vector of cumulative pathlengths
[in] pathlength pathlength at which to calculate above values
[in] stokes_dim length of Stokes vector
[in] ppath the Ppath
Author
Cory Davis
Date
2003-06-19
Definition at line 290 of file mc_interp.cc.
References gridpos(), interp(), interpweights(), is_diagonal(), joker, Ppath::los, matrix_exp_p30(), mult(), ConstVectorView::nelem(), and Ppath::pos.
operator<<()
ostream& operator<< (ostream & os, const SLIData2 &)
Definition at line 78 of file mc_interp.cc.