ARTS: montecarlo.h File Reference
montecarlo.h File Reference
#include <stdexcept>
#include <cmath>
#include "messages.h"
#include "arts.h"
#include "ppath.h"
#include "matpackI.h"
#include "special_interp.h"
#include "check_input.h"
#include "rte.h"
#include "lin_alg.h"
#include "logic.h"
#include "optproperties.h"
#include "physics_funcs.h"
#include "xml_io.h"
#include "rng.h"
#include "cloudbox.h"
Functions
void clear_rt_vars_at_gp (Workspace &ws, MatrixView ext_mat_mono, VectorView abs_vec_mono, Numeric &temperature, const Agenda &opt_prop_gas_agenda, const Agenda &abs_scalar_gas_agenda, const Index f_index, const GridPos &gp_p, const GridPos &gp_lat, const GridPos &gp_lon, ConstVectorView p_grid, ConstTensor3View t_field, ConstTensor4View vmr_field)
clear_rt_vars_at_gp
void cloudy_rt_vars_at_gp (Workspace &ws, MatrixView ext_mat_mono, VectorView abs_vec_mono, VectorView pnd_vec, Numeric &temperature, const Agenda &opt_prop_gas_agenda, const Agenda &abs_scalar_gas_agenda, const Index stokes_dim, const Index f_index, const GridPos &gp_p, const GridPos &gp_lat, const GridPos &gp_lon, ConstVectorView p_grid_cloud, ConstTensor3View t_field_cloud, ConstTensor4View vmr_field_cloud, const Tensor4 &pnd_field, const ArrayOfSingleScatteringData &scat_data_mono, const ArrayOfIndex &cloudbox_limits, const Vector &rte_los, const Verbosity &verbosity)
cloudy_rt_vars_at_gp
void cloud_atm_vars_by_gp (VectorView pressure, VectorView temperature, MatrixView vmr, MatrixView pnd, const ArrayOfGridPos &gp_p, const ArrayOfGridPos &gp_lat, const ArrayOfGridPos &gp_lon, const ArrayOfIndex &cloudbox_limits, ConstVectorView p_grid_cloud, ConstTensor3View t_field_cloud, ConstTensor4View vmr_field_cloud, ConstTensor4View pnd_field)
cloud_atm_vars_by_gp
void cum_l_stepCalc (Vector &cum_l_step, const Ppath &ppath)
cum_l_stepCalc
void findZ11max (Vector &Z11maxvector, const ArrayOfSingleScatteringData &scat_data_mono)
findZ11max
bool is_anyptype30 (const ArrayOfSingleScatteringData &scat_data_mono)
is_anyptype30
void iwp_cloud_opt_pathCalc (Workspace &ws, Numeric &iwp, Numeric &cloud_opt_path, const Vector &rte_pos, const Vector &rte_los, const Agenda &ppath_step_agenda, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Matrix &r_geoid, const Matrix &z_surface, const Tensor3 &z_field, const Tensor3 &t_field, const Tensor4 &vmr_field, const ArrayOfIndex &cloudbox_limits, const Tensor4 &pnd_field, const ArrayOfSingleScatteringData &scat_data_mono, const Vector &particle_masses, const Verbosity &verbosity)
iwp_cloud_opt_pathCalc
void matrix_exp_p30 (MatrixView M, ConstMatrixView A)
matrix_exp_p30
void mcPathTraceGeneral (Workspace &ws, MatrixView evol_op, Vector &abs_vec_mono, Numeric &temperature, MatrixView ext_mat_mono, Rng &rng, Vector &rte_pos, Vector &rte_los, Vector &pnd_vec, Numeric &g, Ppath &ppath_step, Index &termination_flag, bool &inside_cloud, const Agenda &opt_prop_gas_agenda, const Agenda &abs_scalar_gas_agenda, const Index stokes_dim, const Index f_index, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Matrix &r_geoid, const Matrix &z_surface, const Tensor3 &t_field, const Tensor4 &vmr_field, const ArrayOfIndex &cloudbox_limits, const Tensor4 &pnd_field, const ArrayOfSingleScatteringData &scat_data_mono, const Verbosity &verbosity)
mcPathTraceGeneral
void mcPathTraceIPA (Workspace &ws, MatrixView evol_op, Vector &abs_vec_mono, Numeric &temperature, MatrixView ext_mat_mono, Rng &rng, Vector &rte_pos, Vector &rte_los, Vector &pnd_vec, Numeric &g, Index &termination_flag, bool &inside_cloud, const Agenda &opt_prop_gas_agenda, const Agenda &abs_scalar_gas_agenda, const Index stokes_dim, const Index f_index, const Vector &p_grid, const Vector &lat_grid, const Vector &lon_grid, const Tensor3 &z_field, const Matrix &r_geoid, const Matrix &z_surface, const Tensor3 &t_field, const Tensor4 &vmr_field, const ArrayOfIndex &cloudbox_limits, const Tensor4 &pnd_field, const ArrayOfSingleScatteringData &scat_data_mono, const Index z_field_is_1D, const Ppath &ppath, const Verbosity &verbosity)
mcPathTraceIPA
void opt_propCalc (MatrixView K, VectorView K_abs, const Numeric za, const Numeric aa, const ArrayOfSingleScatteringData &scat_data_mono, const Index stokes_dim, ConstVectorView pnd_vec, const Numeric rte_temperature, const Verbosity &verbosity)
opt_propCalc
void opt_propExtract (MatrixView K_spt, VectorView K_abs_spt, const SingleScatteringData &scat_data, const Numeric za, const Numeric aa, const Numeric rte_temperature, const Index stokes_dim, const Verbosity &verbosity)
Extract ext_mat_mono and abs_vec_mono from a monochromatic SingleScatteringData object.
void pha_mat_singleCalc (MatrixView Z, const Numeric za_sca, const Numeric aa_sca, const Numeric za_inc, const Numeric aa_inc, const ArrayOfSingleScatteringData &scat_data_mono, const Index stokes_dim, ConstVectorView pnd_vec, const Numeric rte_temperature, const Verbosity &verbosity)
pha_mat_singleCalc
void pha_mat_singleExtract (MatrixView Z_spt, const SingleScatteringData &scat_data, const Numeric za_sca, const Numeric aa_sca, const Numeric za_inc, const Numeric aa_inc, const Numeric rte_temperature, const Index stokes_dim, const Verbosity &verbosity)
Extract the phase matrix from a monochromatic SingleScatteringData object.
void Sample_los (VectorView new_rte_los, Numeric &g_los_csc_theta, MatrixView Z, Rng &rng, ConstVectorView rte_los, const ArrayOfSingleScatteringData &scat_data_mono, const Index stokes_dim, ConstVectorView pnd_vec, const bool anyptype30, ConstVectorView Z11maxvector, const Numeric Csca, const Numeric rte_temperature, const Verbosity &verbosity)
Sample_los.
Variables
const Numeric DEG2RAD
const Numeric RAD2DEG
const Numeric PI
Function Documentation
clear_rt_vars_at_gp()
void clear_rt_vars_at_gp (Workspace & ws, MatrixView ext_mat_mono, VectorView abs_vec_mono, Numeric & temperature, const Agenda & opt_prop_gas_agenda, const Agenda & abs_scalar_gas_agenda, const Index f_index, const GridPos & gp_p, const GridPos & gp_lat, const GridPos & gp_lon, ConstVectorView p_grid, ConstTensor3View t_field, ConstTensor4View vmr_field)
clear_rt_vars_at_gp
Calculates a bunch of atmospheric variables at the end of a ppath.
Author
Cory Davis
Date
2005-02-19?
Definition at line 57 of file montecarlo.cc.
References abs_scalar_gas_agendaExecute(), interp_atmfield_by_itw(), interp_atmfield_gp2itw(), interpweights(), itw2p(), joker, ConstTensor4View::nbooks(), ns, and opt_prop_gas_agendaExecute().
Referenced by mcPathTraceGeneral(), and mcPathTraceIPA().
cloud_atm_vars_by_gp()
void cloud_atm_vars_by_gp (VectorView pressure, VectorView temperature, MatrixView vmr, MatrixView pnd, const ArrayOfGridPos & gp_p, const ArrayOfGridPos & gp_lat, const ArrayOfGridPos & gp_lon, const ArrayOfIndex & cloudbox_limits, ConstVectorView p_grid_cloud, ConstTensor3View t_field_cloud, ConstTensor4View vmr_field_cloud, ConstTensor4View pnd_field)
cloud_atm_vars_by_gp
Returns pressure, temperature, VMRs and PNDs, at points corresponding to arrays of gridpositions gp_p, gp_lat, and gp_lon. The field and grid input variables all span only the cloudbox
Parameters
pressure Output: a vector of pressures
temperature Output: a vector of temperatures
vmr Output: a n_species by n matrix of VMRs
pnd Output: a n_ptypes by n matrix of VMRs
gp_p an array of pressre gridpoints
gp_lat an array of latitude gridpoints
gp_lon an array of longitude gridpoints
cloudbox_limits the WSV
p_grid_cloud the subset of the p_grid corresponding to the cloudbox
t_field_cloud the t_field within the cloudbox
vmr_field_cloud the t_field within the cloudbox
pnd_field The WSV
Author
Cory Davis
Date
2005-06-07
Definition at line 231 of file montecarlo.cc.
References gridpos_upperend_check(), interp_atmfield_by_itw(), interp_atmfield_gp2itw(), interpweights(), itw2p(), joker, ConstTensor4View::nbooks(), Array< base >::nelem(), ConstVectorView::nelem(), and ns.
Referenced by cloudy_rt_vars_at_gp(), and iwp_cloud_opt_pathCalc().
cloudy_rt_vars_at_gp()
void cloudy_rt_vars_at_gp (Workspace & ws, MatrixView ext_mat_mono, VectorView abs_vec_mono, VectorView pnd_vec, Numeric & temperature, const Agenda & opt_prop_gas_agenda, const Agenda & abs_scalar_gas_agenda, const Index stokes_dim, const Index f_index, const GridPos & gp_p, const GridPos & gp_lat, const GridPos & gp_lon, ConstVectorView p_grid_cloud, ConstTensor3View t_field_cloud, ConstTensor4View vmr_field_cloud, const Tensor4 & pnd_field, const ArrayOfSingleScatteringData & scat_data_mono, const ArrayOfIndex & cloudbox_limits, const Vector & rte_los, const Verbosity & verbosity)
cloudy_rt_vars_at_gp
Calculates a bunch of atmospheric variables at the end of a ppath.
Author
Cory Davis
Date
2005-02-19?
Definition at line 129 of file montecarlo.cc.
References abs_scalar_gas_agendaExecute(), cloud_atm_vars_by_gp(), joker, ConstTensor4View::nbooks(), ns, opt_prop_gas_agendaExecute(), and opt_propCalc().
Referenced by mcPathTraceGeneral(), and mcPathTraceIPA().
cum_l_stepCalc()
void cum_l_stepCalc (Vector & cum_l_step, const Ppath & ppath)
cum_l_stepCalc
Returns a vector of cumulative pathlengths for a given ppath by adding ppath.l_step
Parameters
cum_l_step Output: vector of cumulative pathlengths.
ppath a Ppath.
Author
Cory Davis
Date
2003-06-19
Definition at line 325 of file montecarlo.cc.
References Ppath::l_step, Ppath::np, and Vector::resize().
Referenced by mcPathTraceGeneral().
findZ11max()
void findZ11max (Vector & Z11maxvector, const ArrayOfSingleScatteringData & scat_data_mono)
findZ11max
The direction sampling method requires a bounding value for Z11. This returns a vector with the maximum value of Z11 for each particle type.
Parameters
[out] Z11maxvector Maximum value of Z11 for each particle type
[in] scat_data_mono
Author
Cory Davis
Date
2004-31-1
Definition at line 351 of file montecarlo.cc.
References joker, max, Array< base >::nelem(), PARTICLE_TYPE_HORIZ_AL, PARTICLE_TYPE_MACROS_ISO, and Vector::resize().
Referenced by MCGeneral(), and MCIPA().
is_anyptype30()
bool is_anyptype30 (const ArrayOfSingleScatteringData & scat_data_mono)
is_anyptype30
Some operations in Monte Carlo simulations are different depending on the particle type of the scattering particles. This function searches scat_data_mono to determine if any of the particle types have ptype=30
Author
Cory Davis
Date
2004-1-31
Definition at line 388 of file montecarlo.cc.
References Array< base >::nelem(), and PARTICLE_TYPE_HORIZ_AL.
Referenced by MCGeneral(), and MCIPA().
iwp_cloud_opt_pathCalc()
void iwp_cloud_opt_pathCalc (Workspace & ws, Numeric & iwp, Numeric & cloud_opt_path, const Vector & rte_pos, const Vector & rte_los, const Agenda & ppath_step_agenda, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Matrix & r_geoid, const Matrix & z_surface, const Tensor3 & z_field, const Tensor3 & t_field, const Tensor4 & vmr_field, const ArrayOfIndex & cloudbox_limits, const Tensor4 & pnd_field, const ArrayOfSingleScatteringData & scat_data_mono, const Vector & particle_masses, const Verbosity & verbosity)
iwp_cloud_opt_pathCalc
Calculated the ice water path(iwp) and cloud optical path (cloud_opt_path) for a given sensor_pos_ and sensor_los
Author
Cory Davis
Date
2006-6-15
Definition at line 417 of file montecarlo.cc.
References cloud_atm_vars_by_gp(), Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, joker, Ppath::l_step, Ppath::los, ConstTensor4View::nbooks(), ConstVectorView::nelem(), Ppath::np, opt_propCalc(), Ppath::pos, ppath_calc(), and ppath_what_background().
Referenced by mc_IWP_cloud_opt_pathCalc().
matrix_exp_p30()
void matrix_exp_p30 (MatrixView M, ConstMatrixView A)
matrix_exp_p30
When we have p30 particles, and therefore the extinction matrix has a block diagonal form with 3 independent elements, the matrix expontential can be calculated very quickly and exactly using this function.
Parameters
M output matrix
A input matrix (must be of the form described above)
Author
Cory Davis
Date
2005-3-2
Definition at line 517 of file montecarlo.cc.
References M, ConstMatrixView::ncols(), and ConstMatrixView::nrows().
Referenced by interpTArray(), mcPathTraceGeneral(), and mcPathTraceIPA().
mcPathTraceGeneral()
void mcPathTraceGeneral (Workspace & ws, MatrixView evol_op, Vector & abs_vec_mono, Numeric & temperature, MatrixView ext_mat_mono, Rng & rng, Vector & rte_pos, Vector & rte_los, Vector & pnd_vec, Numeric & g, Ppath & ppath_step, Index & termination_flag, bool & inside_cloud, const Agenda & opt_prop_gas_agenda, const Agenda & abs_scalar_gas_agenda, const Index stokes_dim, const Index f_index, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Matrix & r_geoid, const Matrix & z_surface, const Tensor3 & t_field, const Tensor4 & vmr_field, const ArrayOfIndex & cloudbox_limits, const Tensor4 & pnd_field, const ArrayOfSingleScatteringData & scat_data_mono, const Verbosity & verbosity)
mcPathTraceGeneral
Performs the tasks of pathlength sampling, ray tracing (but now only as far as determined by pathlength sampling) and calculation of the evolution operator and several atmospheric variables at the new point.
Author
Cory Davis
Date
2005-2-21
Definition at line 557 of file montecarlo.cc.
References clear_rt_vars_at_gp(), cloudy_rt_vars_at_gp(), cum_l_stepCalc(), Rng::draw(), fractional_gp(), Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, gridpos(), id_mat(), interp(), interpweights(), is_diagonal(), is_inside_cloudbox(), joker, Ppath::los, matrix_exp_p30(), mult(), ConstVectorView::nelem(), Ppath::np, Ppath::pos, ppath_start_stepping(), ppath_step_geom_3d(), and ppath_what_background().
Referenced by MCGeneral().
mcPathTraceIPA()
void mcPathTraceIPA (Workspace & ws, MatrixView evol_op, Vector & abs_vec_mono, Numeric & temperature, MatrixView ext_mat_mono, Rng & rng, Vector & rte_pos, Vector & rte_los, Vector & pnd_vec, Numeric & g, Index & termination_flag, bool & inside_cloud, const Agenda & opt_prop_gas_agenda, const Agenda & abs_scalar_gas_agenda, const Index stokes_dim, const Index f_index, const Vector & p_grid, const Vector & lat_grid, const Vector & lon_grid, const Tensor3 & z_field, const Matrix & r_geoid, const Matrix & z_surface, const Tensor3 & t_field, const Tensor4 & vmr_field, const ArrayOfIndex & cloudbox_limits, const Tensor4 & pnd_field, const ArrayOfSingleScatteringData & scat_data_mono, const Index z_field_is_1D, const Ppath & ppath, const Verbosity & verbosity)
mcPathTraceIPA
Performs the tasks of pathlength sampling, ray tracing (but now only as far as determined by pathlength sampling) and calculation of the evolution operator and several atmospheric variables at the new point. This is the same as mcPathTraceGeneral modified for the independent pixel approximation.
Author
Cory Davis
Date
2005-2-21
Definition at line 821 of file montecarlo.cc.
References abs, cart2poslos(), clear_rt_vars_at_gp(), cloudy_rt_vars_at_gp(), DEG2RAD, Rng::draw(), dx, fractional_gp(), Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, gridpos(), id_mat(), GridPos::idx, interp(), interp_atmfield_by_gp(), interpweights(), is_diagonal(), is_gp_inside_cloudbox(), is_inside_cloudbox(), joker, Ppath::los, matrix_exp_p30(), mult(), ConstVectorView::nelem(), Ppath::np, Ppath::pos, poslos2cart(), ppath_start_stepping(), and z_at_latlon().
Referenced by MCIPA().
opt_propCalc()
void opt_propCalc (MatrixView ext_mat_mono, VectorView abs_vec_mono, const Numeric za, const Numeric aa, const ArrayOfSingleScatteringData & scat_data_mono, const Index stokes_dim, ConstVectorView pnd_vec, const Numeric rte_temperature, const Verbosity & verbosity)
opt_propCalc
Returns the extinction matrix and absorption vector due to scattering particles from scat_data_mono
Parameters
ext_mat_mono Output: extinction matrix
abs_vec_mono Output: absorption coefficient vector
za zenith angle of propagation direction
aa azimuthal angle of propagation
scat_data_mono workspace variable
stokes_dim workspace variable
pnd_vec vector pf particle number densities (one element per particle type)
rte_temperature loacl temperature (workspace variable)
Author
Cory Davis
Date
2004-7-16
Definition at line 1180 of file montecarlo.cc.
References ConstMatrixView::ncols(), Array< base >::nelem(), ConstVectorView::nelem(), ConstMatrixView::nrows(), and opt_propExtract().
Referenced by cloudy_rt_vars_at_gp(), get_ppath_cloudrtvars(), and iwp_cloud_opt_pathCalc().
opt_propExtract()
void opt_propExtract (MatrixView ext_mat_mono_spt, VectorView abs_vec_mono_spt, const SingleScatteringData & scat_data, const Numeric za, const Numeric aa, const Numeric rte_temperature, const Index stokes_dim, const Verbosity & verbosity)
Extract ext_mat_mono and abs_vec_mono from a monochromatic SingleScatteringData object.
Given a monochromatic SingleScatteringData object, propagation directions, and the temperature, this function returns the extinction matrix and the absorption coefficient vector Output:
Parameters
ext_mat_mono_spt the extinction matrix (spt: this is for a single particle)
abs_vec_mono_spt the absorption coefficient vector Input:
scat_data a monochromatic SingleScatteringData object
za
aa
rte_temperature
stokes_dim
Author
Cory Davis
Date
2004-07-16
Definition at line 1279 of file montecarlo.cc.
References SingleScatteringData::abs_vec_data, CREATE_OUT0, SingleScatteringData::ext_mat_data, gridpos(), interp(), interpweights(), joker, ConstTensor5View::ncols(), ConstVectorView::nelem(), PARTICLE_TYPE_GENERAL, PARTICLE_TYPE_HORIZ_AL, PARTICLE_TYPE_MACROS_ISO, SingleScatteringData::ptype, SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
Referenced by opt_propCalc().
pha_mat_singleCalc()
void pha_mat_singleCalc (MatrixView Z, const Numeric za_sca, const Numeric aa_sca, const Numeric za_inc, const Numeric aa_inc, const ArrayOfSingleScatteringData & scat_data_mono, const Index stokes_dim, ConstVectorView pnd_vec, const Numeric rte_temperature, const Verbosity & verbosity)
pha_mat_singleCalc
Returns the total phase matrix for given incident and scattered directions . It requires a vector of particle number densities to be precalculated
Parameters
[out] Z Output: phase matrix
[in] za_sca scattered
[in] aa_sca and
[in] za_inc incident
[in] aa_inc directions
[in] scat_data_mono workspace variable
[in] stokes_dim workspace variable
[in] pnd_vec vector of particle number densities at the point in question
[in] rte_temperature workspace variable
Author
Cory Davis
Date
2003-11-27
Definition at line 1456 of file montecarlo.cc.
References ConstVectorView::nelem(), and pha_mat_singleExtract().
Referenced by iyFOS(), pha_matExtractManually(), and Sample_los().
pha_mat_singleExtract()
void pha_mat_singleExtract (MatrixView Z_spt, const SingleScatteringData & scat_data, const Numeric za_sca, const Numeric aa_sca, const Numeric za_inc, const Numeric aa_inc, const Numeric rte_temperature, const Index stokes_dim, const Verbosity & verbosity)
Extract the phase matrix from a monochromatic SingleScatteringData object.
Given a monochromatic SingleScatteringData object, incident and scattered directions, and the temperature, this function returns the phase matrix in the laboratory frame
Parameters
[out] Z_spt the phase matrix
[in] scat_data a monochromatic SingleScatteringData object
[in] za_sca
[in] aa_sca
[in] za_inc
[in] aa_inc
[in] rte_temperature
[in] stokes_dim
Author
Cory Davis
Date
2004-07-16
Definition at line 1507 of file montecarlo.cc.
References SingleScatteringData::aa_grid, abs, CREATE_OUT0, gridpos(), interp(), interp_scat_angle_temperature(), interpweights(), joker, ConstTensor7View::ncols(), ConstVectorView::nelem(), PARTICLE_TYPE_GENERAL, PARTICLE_TYPE_HORIZ_AL, PARTICLE_TYPE_MACROS_ISO, SingleScatteringData::pha_mat_data, pha_mat_labCalc(), SingleScatteringData::ptype, SingleScatteringData::T_grid, and SingleScatteringData::za_grid.
Referenced by pha_mat_singleCalc().
Sample_los()
void Sample_los (VectorView new_rte_los, Numeric & g_los_csc_theta, MatrixView Z, Rng & rng, ConstVectorView rte_los, const ArrayOfSingleScatteringData & scat_data_mono, const Index stokes_dim, ConstVectorView pnd_vec, const bool anyptype30, ConstVectorView Z11maxvector, const Numeric Csca, const Numeric rte_temperature, const Verbosity & verbosity)
Sample_los.
FIXME: 2011-06-17 Documentation removed by Gerrit (severely out of date)
Parameters
[out] new_rte_los incident line of sight for subsequent
[out] g_los_csc_theta probability density for the chosen direction multiplied by sin(za)
[out] Z
[in,out] rng Rng random number generator instance
[in] rte_los incident line of sight for subsequent ray-tracing.
[in] scat_data_mono
[in] stokes_dim
[in] pnd_vec
[in] anyptype30
[in] Z11maxvector
[in] Csca
[in] rte_temperature
Author
Cory Davis
Date
2003-06-19
Definition at line 1712 of file montecarlo.cc.
References Rng::draw(), Array< base >::nelem(), ConstVectorView::nelem(), pha_mat_singleCalc(), and RAD2DEG.
Referenced by MCGeneral(), and MCIPA().
Variable Documentation
DEG2RAD
const Numeric DEG2RAD extern
PI
const Numeric PI extern
RAD2DEG
const Numeric RAD2DEG extern