ARTS: optproperties.h File Reference
optproperties.h File Reference
Scattering database structure and functions.
#include "matpackVII.h"
#include "mystring.h"
#include "messages.h"
Classes
struct SingleScatteringData
Structure which describes the single scattering properties of a.
struct ScatteringMetaData
Typedefs
typedef Array< SingleScatteringData > ArrayOfSingleScatteringData
typedef Array< ScatteringMetaData > ArrayOfScatteringMetaData
Enumerations
enum ParticleType { PARTICLE_TYPE_GENERAL = 10, PARTICLE_TYPE_MACROS_ISO = 20, PARTICLE_TYPE_HORIZ_AL = 30, PARTICLE_TYPE_SPHERICAL = 40 }
An attribute to classify the particle type in a SingleScatteringData.
Functions
ostream & operator<< (ostream &os, const SingleScatteringData &ssd)
ostream & operator<< (ostream &os, const ArrayOfSingleScatteringData &assd)
ostream & operator<< (ostream &os, const ScatteringMetaData &ssd)
ostream & operator<< (ostream &os, const ArrayOfScatteringMetaData &assd)
void abs_vecTransform (VectorView abs_vec_lab, ConstTensor3View abs_vec_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const ParticleType &ptype, const Numeric &za_sca, const Numeric &aa_sca, const Verbosity &verbosity)
Transformation of absorption vector.
void ext_matTransform (MatrixView ext_mat_lab, ConstTensor3View ext_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const ParticleType &ptype, const Numeric &za_sca, const Numeric &aa_sca, const Verbosity &verbosity)
Transformation of extinction matrix.
void pha_matTransform (MatrixView pha_mat_lab, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const ParticleType &ptype, const Index &za_sca_idx, const Index &aa_sca_idx, const Index &za_inc_idx, const Index &aa_inc_idx, ConstVectorView scat_za_grid, ConstVectorView scat_aa_grid, const Verbosity &verbosity)
Transformation of phase matrix.
void interpolate_scat_angle (VectorView pha_mat_int, Numeric &theta_rad, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, const Numeric &za_sca, const Numeric &aa_sca, const Numeric &za_inc, const Numeric &aa_inc)
Interpolate data on the scattering angle.
void pha_mat_labCalc (MatrixView pha_mat_lab, ConstVectorView pha_mat_int, const Numeric &za_sca, const Numeric &aa_sca, const Numeric &za_inc, const Numeric &aa_inc, const Numeric &theta_rad)
Calculate phase matrix in laboratory coordinate system.
Detailed Description
Scattering database structure and functions.
Author
Claudia Emde claud.nosp@m.ia.e.nosp@m.mde@d.nosp@m.lr.d.nosp@m.e
Date
2003-03-06
This file contains the definition of the SingleScatteringData structure and the functions in optproperties.cc that are of interest elsewhere.
Definition in file optproperties.h.
Typedef Documentation
ArrayOfScatteringMetaData
typedef Array<ScatteringMetaData> ArrayOfScatteringMetaData
Definition at line 110 of file optproperties.h.
ArrayOfSingleScatteringData
typedef Array<SingleScatteringData> ArrayOfSingleScatteringData
Definition at line 86 of file optproperties.h.
Enumeration Type Documentation
ParticleType
enum ParticleType
An attribute to classify the particle type in a SingleScatteringData.
GENERAL General case MACROS_ISO Macroscopically isotropic and mirror-symmetric scattering media HORIZ_AL Horizonatally aligned plates and columns SPHERICAL Spherical particles
A detailed description of the different cases can be found in AUG.
Enumerator
PARTICLE_TYPE_GENERAL
PARTICLE_TYPE_MACROS_ISO
PARTICLE_TYPE_HORIZ_AL
PARTICLE_TYPE_SPHERICAL
Definition at line 55 of file optproperties.h.
Function Documentation
abs_vecTransform()
void abs_vecTransform (VectorView abs_vec_lab, ConstTensor3View abs_vec_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const ParticleType & ptype, const Numeric & za_sca, const Numeric & aa_sca, const Verbosity & verbosity)
Transformation of absorption vector.
In the single scattering database the data of the absorption vector is stored in different coordinate systems, depending on the type of hydrometeor species.
See AUG for information about different classifications of the hydrometeor species.
Output and Input:
Parameters
abs_vec_lab Absorption vector in Laboratory frame. Input:
abs_vec_data Absorption vector in database.
za_datagrid Zenith angle grid in the database.
aa_datagrid Zenith angle grid in the database.
ptype Clasiification of the hydometeor species.
za_sca Zenith angle of scattered direction.
aa_sca Azimuth angle of scattered direction.
Author
Claudia Emde
Date
2003-05-24
Definition at line 85 of file optproperties.cc.
References CREATE_OUT0, gridpos(), interp(), interpweights(), joker, ConstTensor3View::ncols(), ConstVectorView::nelem(), ConstTensor3View::npages(), PARTICLE_TYPE_GENERAL, PARTICLE_TYPE_HORIZ_AL, and PARTICLE_TYPE_MACROS_ISO.
Referenced by opt_prop_sptFromData(), and opt_prop_sptFromMonoData().
ext_matTransform()
void ext_matTransform (MatrixView ext_mat_lab, ConstTensor3View ext_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const ParticleType & ptype, const Numeric & za_sca, const Numeric & aa_sca, const Verbosity & verbosity)
Transformation of extinction matrix.
In the single scattering database the data of the extinction matrix is stored in different coordinate systems, depending on the type of hydrometeor species.
See AUG for information about different classifications of the hydrometeor species.
Output and Input:
Parameters
ext_mat_lab Extinction matrix in Laboratory frame. Input:
ext_mat_data Extinction matrix in database.
za_datagrid Zenith angle grid in the database.
aa_datagrid Zenith angle grid in the database.
ptype Clasiification of the hydometeor species.
za_sca Zenith angle of scattered direction.
aa_sca Azimuth angle of scattered direction.
Author
Claudia Emde
Date
2003-05-24
Definition at line 190 of file optproperties.cc.
References CREATE_OUT0, gridpos(), interp(), interpweights(), joker, ConstMatrixView::ncols(), ConstTensor3View::ncols(), ConstTensor3View::npages(), PARTICLE_TYPE_GENERAL, PARTICLE_TYPE_HORIZ_AL, and PARTICLE_TYPE_MACROS_ISO.
Referenced by opt_prop_sptFromData(), and opt_prop_sptFromMonoData().
interpolate_scat_angle()
void interpolate_scat_angle (VectorView pha_mat_int, Numeric & theta_rad, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, const Numeric & za_sca, const Numeric & aa_sca, const Numeric & za_inc, const Numeric & aa_inc)
Interpolate data on the scattering angle.
This function is used for the transformation of the phase matrix from scattering frame to the laboratory frame for randomly oriented scattering media (case PTYPE_MACRO_ISO).
The scattering angle is calculated from the angles defining the directions of the incoming and scattered radiation. After that the data (which is stored in the data files as a function of the scattering angle) is interpolated on the calculated scattering angle.
Parameters
[out] pha_mat_int Interpolated phase matrix.
[out] theta_rad Scattering angle [rad].
[in] pha_mat_data Phase matrix in database.
[in] za_datagrid Zenith angle grid in the database.
[in] za_sca Zenith angle of scattered direction [rad].
[in] aa_sca Azimuth angle of scattered direction [rad].
[in] za_inc Zenith angle of incoming direction [rad].
[in] aa_inc Azimuth angle of incoming direction [rad].
Author
Claudia Emde
Date
2003-08-19
Definition at line 614 of file optproperties.cc.
References abs, DEG2RAD, gridpos(), interp(), interpweights(), joker, ConstTensor5View::ncols(), PI, and RAD2DEG.
Referenced by pha_matTransform().
operator<<() [1/4]
ostream& operator<< (ostream & os, const ArrayOfScatteringMetaData & assd)
Definition at line 910 of file optproperties.cc.
operator<<() [2/4]
ostream& operator<< (ostream & os, const ArrayOfSingleScatteringData & assd)
Definition at line 897 of file optproperties.cc.
operator<<() [3/4]
ostream& operator<< (ostream & os, const ScatteringMetaData & ssd)
Definition at line 903 of file optproperties.cc.
operator<<() [4/4]
ostream& operator<< (ostream & os, const SingleScatteringData & ssd)
Definition at line 890 of file optproperties.cc.
pha_mat_labCalc()
void pha_mat_labCalc (MatrixView pha_mat_lab, ConstVectorView pha_mat_int, const Numeric & za_sca, const Numeric & aa_sca, const Numeric & za_inc, const Numeric & aa_inc, const Numeric & theta_rad)
Calculate phase matrix in laboratory coordinate system.
Transformation function for the phase matrix for the case of randomly oriented particles (case PTYPE_MACRO_ISO).
Some of the formulas can be found in
Mishchenkho: "Scattering, Absorption and Emission of Light by Small Particles", Cambridge University Press, 2002 Capter 4
The full set of formulas will be documented in AUG.
Output and Input:
Parameters
pha_mat_lab Phase matrix in laboratory frame. Input:
pha_mat_int Interpolated phase matrix.
za_sca Zenith angle of scattered direction.
aa_sca Azimuth angle of scattered direction.
za_inc Zenith angle of incoming direction.
aa_inc Azimuth angle of incoming direction.
theta_rad Scattering angle [rad].
Author
Claudia Emde
Date
2003-05-13
Definition at line 705 of file optproperties.cc.
References abs, ANGTOL, DEG2RAD, F11, F12, F22, F33, F34, F44, ConstMatrixView::ncols(), PI, and RAD2DEG.
Referenced by pha_mat_singleExtract(), and pha_matTransform().
pha_matTransform()
void pha_matTransform (MatrixView pha_mat_lab, ConstTensor5View pha_mat_data, ConstVectorView za_datagrid, ConstVectorView aa_datagrid, const ParticleType & ptype, const Index & za_sca_idx, const Index & aa_sca_idx, const Index & za_inc_idx, const Index & aa_inc_idx, ConstVectorView scat_za_grid, ConstVectorView scat_aa_grid, const Verbosity & verbosity)
Transformation of phase matrix.
In the single scattering database the data of the phase matrix is stored in different coordinate systems, depending on the type of hydrometeor species.
See AUG for information about different classifications of the hydrometeor species.
Parameters
[in,out] pha_mat_lab Phase matrix in Laboratory frame.
[in] pha_mat_data Phase matrix in database.
[in] za_datagrid Zenith angle grid in the database.
[in] aa_datagrid Zenith angle grid in the database.
[in] ptype Classification of the hydometeor species.
[in] za_sca_idx Index of zenith angle of scattered direction.
[in] aa_sca_idx Index of azimuth angle of scattered direction.
[in] za_inc_idx Index of zenith angle of incoming direction.
[in] aa_inc_idx Index of azimuth angle of incoming direction.
[in] scat_za_grid FIXME: DOC
[in] scat_aa_grid FIXME: DOC
Author
Claudia Emde
Date
2003-08-19
Definition at line 345 of file optproperties.cc.
References abs, CREATE_OUT0, gridpos(), interp(), interpolate_scat_angle(), interpweights(), joker, ConstMatrixView::ncols(), ConstTensor5View::ncols(), ConstTensor5View::npages(), PARTICLE_TYPE_GENERAL, PARTICLE_TYPE_HORIZ_AL, PARTICLE_TYPE_MACROS_ISO, and pha_mat_labCalc().
Referenced by DoitScatteringDataPrepare(), pha_mat_sptFromData(), and pha_mat_sptFromMonoData().