ARTS: parameters.cc File Reference
parameters.cc File Reference
This file contains the function get_parameters, which reads command line parameters.
#include <iostream>
#include <cstdio>
#include <cstdlib>
#include "arts.h"
#include <arts_getopt.h>
#include "parameters.h"
Functions
bool get_parameters (int argc, char **argv)
Get the command line parameters.
Variables
Parameters parameters
Holds the command line parameters.
Detailed Description
This file contains the function get_parameters, which reads command line parameters.
Standard GNU functions are used for this.
Author
Stefan Buehler
Date
2001-07-24
Definition in file parameters.cc.
Function Documentation
get_parameters()
bool get_parameters (int argc, char ** argv)
Get the command line parameters.
They are stored in the global variable parameters which is a structure of type Parameters. If needed, this variable should be declared like this:
extern const Parameters parameters
Returns
false=ok, true=error
Parameters
argc Number of command line parameters
argv Values of command line parameters
Author
Stefan Buehler
Version
1
Definition at line 42 of file parameters.cc.
References ARTS_DEFAULT_INCLUDE_DIR, arts_exit(), Parameters::basename, Parameters::baseurl, Parameters::controlfiles, Parameters::daemon, Parameters::describe, Parameters::docserver, getopt_long(), Parameters::groups, Parameters::gui, option::has_arg, Parameters::help, Parameters::helptext, Parameters::includepath, Parameters::input, Parameters::methods, option::name, Array< base >::nelem(), no_argument, my_basic_string< charT >::npos, Parameters::numthreads, optarg, optind, optional_argument, parameters, Parameters::plain, Parameters::reporting, required_argument, Parameters::usage, option::val, Parameters::version, and Parameters::workspacevariables.
Referenced by main().
Variable Documentation
parameters
Parameters parameters
Holds the command line parameters.
Definition at line 40 of file parameters.cc.
Referenced by abs_cont_descriptionInit(), find_file(), get_parameters(), main(), option_methods(), option_workspacevariables(), ArtsParser::parse_agenda(), and xsec_continuum_tag().