ARTS: xml_io_array_types.cc File Reference
xml_io_array_types.cc File Reference
This file contains basic functions to handle XML data files.
#include "arts.h"
#include "xml_io_private.h"
#include "xml_io_types.h"
#include "jacobian.h"
Functions
void xml_read_from_stream (istream &is_xml, Array< SpeciesRecord > &asrecord, bifstream *pbifs, const Verbosity &verbosity)
Reads SpeciesData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Array< SpeciesRecord > &asrecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SpeciesData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfSpeciesTag &aastag, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfSpeciesTag from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfSpeciesTag &aastag, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfSpeciesTag to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfPpath &appath, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfPpath from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfPpath &appath, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfPpath to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfTensor3 &aatensor3, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfTensor3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfTensor3 &aatensor3, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfTensor3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfTensor6 &aatensor6, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfTensor6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfTensor6 &aatensor6, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfTensor6 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGridPos &agpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGridPos &agpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGridPos &aagpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGridPos &aagpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfArrayOfGridPos &aaagpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfArrayOfGridPos &aaagpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfArrayOfArrayOfGridPos &aaaagpos, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfArrayOfArrayOfGridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfArrayOfArrayOfGridPos &aaaagpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfArrayOfArrayOfGridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfIndex &aindex, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfIndex from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfIndex &aindex, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfIndex to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfIndex &aaindex, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfIndex from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfIndex &aaindex, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfIndex to XML output stream.
void xml_read_from_stream (istream &is_xml, Array< IsotopeRecord > &airecord, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfIsotopeRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Array< IsotopeRecord > &airecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfIsotopeRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfMatrix &amatrix, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfMatrix &amatrix, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfMatrix &aamatrix, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfMatrix from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfMatrix &aamatrix, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfMatrix to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfSparse &asparse, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfSparse from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfSparse &asparse, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfSparse to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfRetrievalQuantity &arq, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfRetrievalQuantity from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfRetrievalQuantity &arq, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfRetrivalQuantity to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfSpeciesTag &astag, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfSpeciesTag from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfSpeciesTag &astag, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfSpeciesTag to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfSingleScatteringData &assdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfSingleScatteringData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfSingleScatteringData &assdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfSingleScatteringData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfScatteringMetaData &asmdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfScatteringMetaData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfScatteringMetaData &asmdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfScatteringMetaData to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField1 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField1 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField1 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField1 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField2 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField2 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField2 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField3 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField3 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGriddedField1 &aagfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGriddedField1 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGriddedField1 &aagfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGriddedField1 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfGriddedField3 &aagfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfGriddedField3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfGriddedField3 &aagfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfGriddedField3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfGriddedField4 &agfield, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfGriddedField4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfGriddedField4 &agfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfGriddedField4 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfLineRecord &alrecord, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfLineRecord from XML input stream.
void xml_read_from_stream (istream &is_xml, ArrayOfLineRecord &alrecord, const Numeric fmin, const Numeric fmax, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfLineRecord from XML input stream within specified frequency range.
void xml_write_to_stream (ostream &os_xml, const ArrayOfLineRecord &alrecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfLineRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfArrayOfLineRecord &aalrecord, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfArrayOfLineRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfArrayOfLineRecord &aalrecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfArrayOfLineRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfLineshapeSpec &alspec, bifstream *pbifs, const Verbosity &)
Reads ArrayOfLineshapeSpec from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfLineshapeSpec &alspec, bofstream *pbofs, const String &name, const Verbosity &)
Writes ArrayOfLineshapeSpec to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor3 &atensor3, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor3 &atensor3, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor3 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor4 &atensor4, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor4 &atensor4, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor4 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor6 &atensor6, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor6 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor6 &atensor6, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor6 to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfTensor7 &atensor7, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfTensor7 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfTensor7 &atensor7, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfTensor6 to XML output stream.
void xml_parse_from_stream (istream &is_xml, ArrayOfString &astring, bifstream *pbifs, ArtsXMLTag &tag, const Verbosity &verbosity)
Parse ArrayOfString from XML input stream.
void xml_read_from_stream (istream &is_xml, ArrayOfString &astring, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfString from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfString &astring, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfString to XML output stream.
void xml_read_from_stream (istream &is_xml, ArrayOfVector &avector, bifstream *pbifs, const Verbosity &verbosity)
Reads ArrayOfVector from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ArrayOfVector &avector, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ArrayOfVector to XML output stream.
Detailed Description
This file contains basic functions to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_array_types.cc.
Function Documentation
xml_parse_from_stream()
void xml_parse_from_stream (istream & is_xml, ArrayOfString & astring, bifstream * pbifs, ArtsXMLTag & tag, const Verbosity & verbosity)
Parse ArrayOfString from XML input stream.
Parameters
is_xml XML Input stream
astring ArrayOfString return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
tag XML tag object
Definition at line 2692 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::get_attribute_value(), and xml_read_from_stream().
Referenced by xml_read_from_stream().
xml_read_from_stream() [1/35]
void xml_read_from_stream (istream & is_xml, Array< IsotopeRecord > & airecord, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfIsotopeRecord from XML input stream.
Parameters
is_xml XML Input stream
airecord ArrayOfIsotopeRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 956 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [2/35]
void xml_read_from_stream (istream & is_xml, Array< SpeciesRecord > & asrecord, bifstream * pbifs, const Verbosity & verbosity)
Reads SpeciesData from XML input stream.
Parameters
is_xml XML Input stream
asrecord SpeciesData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 50 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), and ArtsXMLTag::read_from_stream().
Referenced by xml_parse_from_stream(), xml_read_arts_catalogue_from_file(), xml_read_from_file(), and xml_read_from_stream().
xml_read_from_stream() [3/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfArrayOfArrayOfGridPos & aaaagpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfArrayOfArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
aaaagpos ArrayOfArrayOfArrayOfArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 707 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [4/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfArrayOfGridPos & aaagpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
aaagpos ArrayOfArrayOfArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 625 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [5/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGriddedField1 & aagfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGriddedField1 from XML input stream.
Parameters
is_xml XML Input stream
aagfield ArrayOfArrayOfGriddedField1 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1849 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [6/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGriddedField3 & aagfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGriddedField3 from XML input stream.
Parameters
is_xml XML Input stream
aagfield ArrayOfArrayOfGriddedField3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1930 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [7/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfGridPos & aagpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
aagpos ArrayOfArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 544 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [8/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfIndex & aaindex, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfIndex from XML input stream.
Parameters
is_xml XML Input stream
aaindex ArrayOfArrayOfIndex return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 873 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [9/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfLineRecord & aalrecord, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfLineRecord from XML input stream.
Parameters
is_xml XML Input stream
aalrecord ArrayOfArrayOfLineRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2242 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [10/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfMatrix & aamatrix, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfMatrix from XML input stream.
Parameters
is_xml XML Input stream
aamatrix ArrayOfArrayOfMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1120 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [11/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfSpeciesTag & aastag, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfSpeciesTag from XML input stream.
Parameters
is_xml XML Input stream
aastag ArrayOfArrayOfSpeciesTag return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 133 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [12/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfTensor3 & aatensor3, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfTensor3 from XML input stream.
Parameters
is_xml XML Input stream
aatensor3 ArrayOfArrayOfTensor3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 300 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [13/35]
void xml_read_from_stream (istream & is_xml, ArrayOfArrayOfTensor6 & aatensor6, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfArrayOfTensor6 from XML input stream.
Parameters
is_xml XML Input stream
aatensor6 ArrayOfArrayOfTensor6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 382 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [14/35]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField1 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField1 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField1 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1606 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [15/35]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField2 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField2 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField2 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1687 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [16/35]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField3 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField3 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1768 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [17/35]
void xml_read_from_stream (istream & is_xml, ArrayOfGriddedField4 & agfield, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGriddedField4 from XML input stream.
Parameters
is_xml XML Input stream
agfield ArrayOfGriddedField4 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2011 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [18/35]
void xml_read_from_stream (istream & is_xml, ArrayOfGridPos & agpos, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfGridPos from XML input stream.
Parameters
is_xml XML Input stream
agpos ArrayOfGridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 463 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [19/35]
void xml_read_from_stream (istream & is_xml, ArrayOfIndex & aindex, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfIndex from XML input stream.
Parameters
is_xml XML Input stream
aindex ArrayOfIndex return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 790 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [20/35]
void xml_read_from_stream (istream & is_xml, ArrayOfLineRecord & alrecord, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfLineRecord from XML input stream.
Parameters
is_xml XML Input stream
alrecord ArrayOfLineRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2092 of file xml_io_array_types.cc.
References xml_read_from_stream().
xml_read_from_stream() [21/35]
void xml_read_from_stream (istream & is_xml, ArrayOfLineRecord & alrecord, const Numeric fmin, const Numeric fmax, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfLineRecord from XML input stream within specified frequency range.
Parameters
is_xml XML Input stream
alrecord ArrayOfLineRecord return value
fmin Lowest frequency (NAN = no limit)
fmax Highest frequency (NAN = no limit)
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2110 of file xml_io_array_types.cc.
References ArtsXMLTag::check_name(), LineRecord::F(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), LineRecord::ReadFromArtscat3Stream(), and LineRecord::ReadFromArtscat4Stream().
xml_read_from_stream() [22/35]
void xml_read_from_stream (istream & is_xml, ArrayOfLineshapeSpec & alspec, bifstream * pbifs, const Verbosity &)
Reads ArrayOfLineshapeSpec from XML input stream.
Parameters
is_xml XML Input stream
alspec ArrayOfLineshapeSpec return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2325 of file xml_io_array_types.cc.
xml_read_from_stream() [23/35]
void xml_read_from_stream (istream & is_xml, ArrayOfMatrix & amatrix, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfMatrix from XML input stream.
Parameters
is_xml XML Input stream
amatrix ArrayOfMatrix return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1038 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [24/35]
void xml_read_from_stream (istream & is_xml, ArrayOfPpath & appath, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfPpath from XML input stream.
Parameters
is_xml XML Input stream
appath ArrayOfPpath return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 216 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [25/35]
void xml_read_from_stream (istream & is_xml, ArrayOfRetrievalQuantity & arq, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfRetrievalQuantity from XML input stream.
Parameters
is_xml XML Input stream
arq ArrayOfRetrievalQuantity return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1283 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [26/35]
void xml_read_from_stream (istream & is_xml, ArrayOfScatteringMetaData & asmdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfScatteringMetaData from XML input stream.
Parameters
is_xml XML Input stream
asmdata ArrayOfScatteringMetaData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1525 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [27/35]
void xml_read_from_stream (istream & is_xml, ArrayOfSingleScatteringData & assdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfSingleScatteringData from XML input stream.
Parameters
is_xml XML Input stream
assdata ArrayOfSingleScatteringData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1445 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [28/35]
void xml_read_from_stream (istream & is_xml, ArrayOfSparse & asparse, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfSparse from XML input stream.
Parameters
is_xml XML Input stream
asparse ArrayOfSparse return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1201 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [29/35]
void xml_read_from_stream (istream & is_xml, ArrayOfSpeciesTag & astag, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfSpeciesTag from XML input stream.
Parameters
is_xml XML Input stream
astag ArrayOfSpeciesTag return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1364 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [30/35]
void xml_read_from_stream (istream & is_xml, ArrayOfString & astring, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfString from XML input stream.
Parameters
is_xml XML Input stream
astring ArrayOfString return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2729 of file xml_io_array_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), and xml_parse_from_stream().
xml_read_from_stream() [31/35]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor3 & atensor3, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor3 from XML input stream.
Parameters
is_xml XML Input stream
atensor3 ArrayOfTensor3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2363 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [32/35]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor4 & atensor4, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor4 from XML input stream.
Parameters
is_xml XML Input stream
atensor4 ArrayOfTensor4 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2446 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [33/35]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor6 & atensor6, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor6 from XML input stream.
Parameters
is_xml XML Input stream
atensor6 ArrayOfTensor6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2529 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [34/35]
void xml_read_from_stream (istream & is_xml, ArrayOfTensor7 & atensor7, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfTensor7 from XML input stream.
Parameters
is_xml XML Input stream
atensor7 ArrayOfTensor6 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2610 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [35/35]
void xml_read_from_stream (istream & is_xml, ArrayOfVector & avector, bifstream * pbifs, const Verbosity & verbosity)
Reads ArrayOfVector from XML input stream.
Parameters
is_xml XML Input stream
avector ArrayOfVector return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 2791 of file xml_io_array_types.cc.
References ArtsXMLTag::check_attribute(), ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_write_to_stream() [1/34]
void xml_write_to_stream (ostream & os_xml, const Array< IsotopeRecord > & airecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfIsotopeRecord to XML output stream.
Parameters
os_xml XML Output stream
airecord ArrayOfIsotopeRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 998 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [2/34]
void xml_write_to_stream (ostream & os_xml, const Array< SpeciesRecord > & asrecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SpeciesData to XML output stream.
Parameters
os_xml XML Output stream
asrecord SpeciesData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 93 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), and ArtsXMLTag::write_to_stream().
Referenced by xml_write_to_file(), and xml_write_to_stream().
xml_write_to_stream() [3/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfArrayOfArrayOfGridPos & aaaagpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfArrayOfArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
aaaagpos ArrayOfArrayOfArrayOfArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 750 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [4/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfArrayOfGridPos & aaagpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
aaagpos ArrayOfArrayOfArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 668 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [5/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGriddedField1 & aagfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGriddedField1 to XML output stream.
Parameters
os_xml XML Output stream
aagfield ArrayOfArrayOfGriddedField1
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1891 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [6/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGriddedField3 & aagfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGriddedField3 to XML output stream.
Parameters
os_xml XML Output stream
aagfield ArrayOfArrayOfGriddedField3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1972 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [7/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfGridPos & aagpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
aagpos ArrayOfArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 587 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [8/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfIndex & aaindex, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfIndex to XML output stream.
Parameters
os_xml XML Output stream
aaindex ArrayOfArrayOfIndex
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 915 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [9/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfLineRecord & aalrecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfLineRecord to XML output stream.
Parameters
os_xml XML Output stream
aalrecord ArrayOfArrayOfLineRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2285 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [10/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfMatrix & aamatrix, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfMatrix to XML output stream.
Parameters
os_xml XML Output stream
aamatrix ArrayOfArrayOfMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1162 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [11/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfSpeciesTag & aastag, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfSpeciesTag to XML output stream.
Parameters
os_xml XML Output stream
aastag ArrayOfArrayOfSpeciesTag
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 176 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [12/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfTensor3 & aatensor3, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfTensor3 to XML output stream.
Parameters
os_xml XML Output stream
aatensor3 ArrayOfArrayOfTensor3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 343 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [13/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfArrayOfTensor6 & aatensor6, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfArrayOfTensor6 to XML output stream.
Parameters
os_xml XML Output stream
aatensor6 ArrayOfArrayOfTensor6
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 424 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [14/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField1 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField1 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField1
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1648 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [15/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField2 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField2 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField2
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1729 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [16/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField3 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField3 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1810 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [17/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGriddedField4 & agfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGriddedField4 to XML output stream.
Parameters
os_xml XML Output stream
agfield ArrayOfGriddedField4
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2053 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [18/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfGridPos & agpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfGridPos to XML output stream.
Parameters
os_xml XML Output stream
agpos ArrayOfGridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 506 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [19/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfIndex & aindex, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfIndex to XML output stream.
Parameters
os_xml XML Output stream
aindex ArrayOfIndex
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 833 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [20/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfLineRecord & alrecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfLineRecord to XML output stream.
Parameters
os_xml XML Output stream
alrecord ArrayOfLineRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2201 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), LineRecord::Version(), and ArtsXMLTag::write_to_stream().
xml_write_to_stream() [21/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfLineshapeSpec & alspec, bofstream * pbofs, const String & name, const Verbosity &)
Writes ArrayOfLineshapeSpec to XML output stream.
Parameters
os_xml XML Output stream
alspec ArrayOfLineshapeSpec
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2342 of file xml_io_array_types.cc.
xml_write_to_stream() [22/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfMatrix & amatrix, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfMatrix to XML output stream.
Parameters
os_xml XML Output stream
amatrix ArrayOfMatrix
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1081 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [23/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfPpath & appath, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfPpath to XML output stream.
Parameters
os_xml XML Output stream
appath ArrayOfPpath
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 260 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [24/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfRetrievalQuantity & arq, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfRetrivalQuantity to XML output stream.
Parameters
os_xml XML Output stream
arq ArrayOfRetrievalQuantity
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1325 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [25/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfScatteringMetaData & asmdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfScatteringMetaData to XML output stream.
Parameters
os_xml XML Output stream
asmdata ArrayOfScatteringMetaData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1566 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [26/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfSingleScatteringData & assdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfSingleScatteringData to XML output stream.
Parameters
os_xml XML Output stream
assdata ArrayOfSingleScatteringData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1486 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [27/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfSparse & asparse, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfSparse to XML output stream.
Parameters
os_xml XML Output stream
asparse ArrayOfSparse
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1244 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [28/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfSpeciesTag & astag, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfSpeciesTag to XML output stream.
Parameters
os_xml XML Output stream
astag ArrayOfSpeciesTag
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1406 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [29/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfString & astring, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfString to XML output stream.
Parameters
os_xml XML Output stream
astring ArrayOfString
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2753 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [30/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor3 & atensor3, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor3 to XML output stream.
Parameters
os_xml XML Output stream
atensor3 ArrayOfTensor3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2406 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [31/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor4 & atensor4, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor4 to XML output stream.
Parameters
os_xml XML Output stream
atensor4 ArrayOfTensor4
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2489 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [32/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor6 & atensor6, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor6 to XML output stream.
Parameters
os_xml XML Output stream
atensor6 ArrayOfTensor6
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2571 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [33/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfTensor7 & atensor7, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfTensor6 to XML output stream.
Parameters
os_xml XML Output stream
atensor7 ArrayOfTensor7
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2652 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [34/34]
void xml_write_to_stream (ostream & os_xml, const ArrayOfVector & avector, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ArrayOfVector to XML output stream.
Parameters
os_xml XML Output stream
avector ArrayOfVector
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 2834 of file xml_io_array_types.cc.
References ArtsXMLTag::add_attribute(), Array< base >::nelem(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().