ARTS: xml_io_compound_types.cc File Reference
xml_io_compound_types.cc File Reference
This file contains basic functions to handle XML data files.
#include "arts.h"
#include "xml_io_private.h"
#include "xml_io_types.h"
#include "matpackI.h"
#include "matpackII.h"
#include "matpackIII.h"
#include "matpackIV.h"
#include "matpackV.h"
#include "matpackVI.h"
#include "matpackVII.h"
#include "gridded_fields.h"
#include "jacobian.h"
Functions
void xml_read_from_stream (istream &is_xml, GasAbsLookup &gal, bifstream *pbifs, const Verbosity &verbosity)
Reads GasAbsLookup from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GasAbsLookup &gal, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GasAbsLookup to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads the grids for gridded fields from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField &gfield, bofstream *pbofs, const String &, const Verbosity &verbosity)
Writes the grids for gridded fields to an XML input stream.
void xml_read_from_stream (istream &is_xml, GriddedField1 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField1 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField1 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField1 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField2 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField2 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField2 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField3 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField3 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField3 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField3 to XML output stream.
void xml_read_from_stream (istream &is_xml, GriddedField4 &gfield, bifstream *pbifs, const Verbosity &verbosity)
Reads GriddedField4 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GriddedField4 &gfield, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GriddedField4 to XML output stream.
void xml_read_from_stream (istream &is_xml, GridPos &gpos, bifstream *pbifs, const Verbosity &verbosity)
Reads GridPos from XML input stream.
void xml_write_to_stream (ostream &os_xml, const GridPos &gpos, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes GridPos to XML output stream.
void xml_read_from_stream (istream &is_xml, IsotopeRecord &irecord, bifstream *pbifs, const Verbosity &verbosity)
Reads IsotopeRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const IsotopeRecord &irecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes IsotopeRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, Ppath &ppath, bifstream *pbifs, const Verbosity &verbosity)
Reads Ppath from XML input stream.
void xml_write_to_stream (ostream &os_xml, const Ppath &ppath, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes Ppath to XML output stream.
void xml_read_from_stream (istream &is_xml, RetrievalQuantity &rq, bifstream *pbifs, const Verbosity &verbosity)
Reads RetrievalQuantity from XML input stream.
void xml_write_to_stream (ostream &os_xml, const RetrievalQuantity &rq, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes RetrievalQuantity to XML output stream.
void xml_read_from_stream (istream &is_xml, SingleScatteringData &ssdata, bifstream *pbifs, const Verbosity &verbosity)
Reads SingleScatteringData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SingleScatteringData &ssdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SingleScatteringData to XML output stream.
void xml_read_from_stream (istream &is_xml, ScatteringMetaData &smdata, bifstream *pbifs, const Verbosity &verbosity)
Reads ScatteringMetaData from XML input stream.
void xml_write_to_stream (ostream &os_xml, const ScatteringMetaData &smdata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes ScatteringMetaData to XML output stream.
void xml_read_from_stream (istream &is_xml, SLIData2 &slidata, bifstream *pbifs, const Verbosity &verbosity)
Reads SLIData2 from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SLIData2 &slidata, bofstream *pbofs, const String &name, const Verbosity &verbosity)
void xml_read_from_stream (istream &is_xml, SpeciesRecord &srecord, bifstream *pbifs, const Verbosity &verbosity)
Reads SpeciesRecord from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SpeciesRecord &srecord, bofstream *pbofs, const String &name, const Verbosity &verbosity)
Writes SpeciesRecord to XML output stream.
void xml_read_from_stream (istream &is_xml, SpeciesTag &stag, bifstream *, const Verbosity &verbosity)
Reads SpeciesTag from XML input stream.
void xml_write_to_stream (ostream &os_xml, const SpeciesTag &stag, bofstream *, const String &name, const Verbosity &verbosity)
Writes SpeciesTag to XML output stream.
void xml_read_from_stream (istream &, Agenda &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const Agenda &, bofstream *, const String &, const Verbosity &)
void xml_read_from_stream (istream &, MCAntenna &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const MCAntenna &, bofstream *, const String &, const Verbosity &)
void xml_read_from_stream (istream &, Verbosity &, bifstream *, const Verbosity &)
void xml_write_to_stream (ostream &, const Verbosity &, bofstream *, const String &, const Verbosity &)
Detailed Description
This file contains basic functions to handle XML data files.
Author
Oliver Lemke olemk.nosp@m.e@co.nosp@m.re-du.nosp@m.mp.i.nosp@m.nfo
Date
2003-06-11
Definition in file xml_io_compound_types.cc.
Function Documentation
xml_read_from_stream() [1/18]
void xml_read_from_stream (istream & , Agenda & , bifstream * , const Verbosity &)
Definition at line 1154 of file xml_io_compound_types.cc.
xml_read_from_stream() [2/18]
void xml_read_from_stream (istream & , MCAntenna & , bifstream * , const Verbosity &)
Definition at line 1173 of file xml_io_compound_types.cc.
xml_read_from_stream() [3/18]
void xml_read_from_stream (istream & , Verbosity & , bifstream * , const Verbosity &)
Definition at line 1192 of file xml_io_compound_types.cc.
xml_read_from_stream() [4/18]
void xml_read_from_stream (istream & is_xml, GasAbsLookup & gal, bifstream * pbifs, const Verbosity & verbosity)
Reads GasAbsLookup from XML input stream.
Parameters
is_xml XML Input stream
gal GasAbsLookup return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 58 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GasAbsLookup::f_grid, GasAbsLookup::nls_pert, GasAbsLookup::nonlinear_species, GasAbsLookup::p_grid, ArtsXMLTag::read_from_stream(), GasAbsLookup::species, GasAbsLookup::t_pert, GasAbsLookup::t_ref, GasAbsLookup::vmrs_ref, and GasAbsLookup::xsec.
Referenced by xml_read_from_stream().
xml_read_from_stream() [5/18]
void xml_read_from_stream (istream & is_xml, GriddedField & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads the grids for gridded fields from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 130 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), GriddedField::get_dim(), ArtsXMLTag::get_name(), ArtsXMLTag::read_from_stream(), GriddedField::set_grid(), GriddedField::set_grid_name(), xml_parse_error(), and xml_parse_from_stream().
xml_read_from_stream() [6/18]
void xml_read_from_stream (istream & is_xml, GriddedField1 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField1 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField1 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 223 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField::checksize(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), and xml_read_from_stream().
xml_read_from_stream() [7/18]
void xml_read_from_stream (istream & is_xml, GriddedField2 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField2 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField2 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 291 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField::checksize(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), and xml_read_from_stream().
xml_read_from_stream() [8/18]
void xml_read_from_stream (istream & is_xml, GriddedField3 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField3 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField3 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 359 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GriddedField::checksize(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), and xml_read_from_stream().
xml_read_from_stream() [9/18]
void xml_read_from_stream (istream & is_xml, GriddedField4 & gfield, bifstream * pbifs, const Verbosity & verbosity)
Reads GriddedField4 from XML input stream.
Parameters
is_xml XML Input stream
gfield GriddedField4 return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 427 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::get_attribute_value(), ArtsXMLTag::read_from_stream(), GriddedField::set_name(), and xml_read_from_stream().
xml_read_from_stream() [10/18]
void xml_read_from_stream (istream & is_xml, GridPos & gpos, bifstream * pbifs, const Verbosity & verbosity)
Reads GridPos from XML input stream.
Parameters
is_xml XML Input stream
gpos GridPos return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 492 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), GridPos::fd, GridPos::idx, ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [11/18]
void xml_read_from_stream (istream & is_xml, IsotopeRecord & irecord, bifstream * pbifs, const Verbosity & verbosity)
Reads IsotopeRecord from XML input stream.
Parameters
is_xml XML Input stream
irecord SpeciesRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 552 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [12/18]
void xml_read_from_stream (istream & is_xml, Ppath & ppath, bifstream * pbifs, const Verbosity & verbosity)
Reads Ppath from XML input stream.
Parameters
is_xml XML Input stream
ppath Ppath return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 627 of file xml_io_compound_types.cc.
References Ppath::background, ArtsXMLTag::check_name(), Ppath::constant, Ppath::dim, Ppath::geom_tan_pos, Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, Ppath::l_step, Ppath::los, Ppath::next_parts, Ppath::np, Ppath::nreal, Ppath::pos, ArtsXMLTag::read_from_stream(), Ppath::tan_pos, xml_read_from_stream(), and Ppath::z.
xml_read_from_stream() [13/18]
void xml_read_from_stream (istream & is_xml, RetrievalQuantity & rq, bifstream * pbifs, const Verbosity & verbosity)
Reads RetrievalQuantity from XML input stream.
Parameters
is_xml XML Input stream
rq RetrievalQuantity return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 715 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [14/18]
void xml_read_from_stream (istream & is_xml, ScatteringMetaData & smdata, bifstream * pbifs, const Verbosity & verbosity)
Reads ScatteringMetaData from XML input stream.
Parameters
is_xml XML Input stream
smdata ScatteringMetaData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 877 of file xml_io_compound_types.cc.
References ScatteringMetaData::A_projec, ScatteringMetaData::asratio, ArtsXMLTag::check_name(), ScatteringMetaData::d_max, ScatteringMetaData::density, ScatteringMetaData::description, ArtsXMLTag::read_from_stream(), ScatteringMetaData::shape, ScatteringMetaData::type, ScatteringMetaData::V, and xml_read_from_stream().
xml_read_from_stream() [15/18]
void xml_read_from_stream (istream & is_xml, SingleScatteringData & ssdata, bifstream * pbifs, const Verbosity & verbosity)
Reads SingleScatteringData from XML input stream.
Parameters
is_xml XML Input stream
ssdata SingleScatteringData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 787 of file xml_io_compound_types.cc.
References SingleScatteringData::aa_grid, SingleScatteringData::abs_vec_data, ArtsXMLTag::check_name(), SingleScatteringData::description, SingleScatteringData::ext_mat_data, SingleScatteringData::f_grid, ConstVectorView::nelem(), ConstTensor7View::nlibraries(), SingleScatteringData::pha_mat_data, SingleScatteringData::ptype, ArtsXMLTag::read_from_stream(), SingleScatteringData::T_grid, xml_read_from_stream(), and SingleScatteringData::za_grid.
xml_read_from_stream() [16/18]
void xml_read_from_stream (istream & is_xml, SLIData2 & slidata, bifstream * pbifs, const Verbosity & verbosity)
Reads SLIData2 from XML input stream.
Parameters
is_xml XML Input stream
slidata SLIData return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 950 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), SLIData2::x1a, SLIData2::x2a, xml_read_from_stream(), and SLIData2::ya.
xml_read_from_stream() [17/18]
void xml_read_from_stream (istream & is_xml, SpeciesRecord & srecord, bifstream * pbifs, const Verbosity & verbosity)
Reads SpeciesRecord from XML input stream.
Parameters
is_xml XML Input stream
srecord SpeciesRecord return value
pbifs Pointer to binary input stream. NULL in case of ASCII file.
Definition at line 1000 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), and xml_read_from_stream().
xml_read_from_stream() [18/18]
void xml_read_from_stream (istream & is_xml, SpeciesTag & stag, bifstream * , const Verbosity & verbosity)
Reads SpeciesTag from XML input stream.
Parameters
is_xml XML Input stream
stag SpeciesTag return value
Definition at line 1065 of file xml_io_compound_types.cc.
References ArtsXMLTag::check_name(), ArtsXMLTag::read_from_stream(), and xml_parse_error().
xml_write_to_stream() [1/18]
void xml_write_to_stream (ostream & , const Agenda & , bofstream * , const String & , const Verbosity &)
Definition at line 1162 of file xml_io_compound_types.cc.
xml_write_to_stream() [2/18]
void xml_write_to_stream (ostream & , const MCAntenna & , bofstream * , const String & , const Verbosity &)
Definition at line 1181 of file xml_io_compound_types.cc.
xml_write_to_stream() [3/18]
void xml_write_to_stream (ostream & , const Verbosity & , bofstream * , const String & , const Verbosity &)
Definition at line 1200 of file xml_io_compound_types.cc.
xml_write_to_stream() [4/18]
void xml_write_to_stream (ostream & os_xml, const GasAbsLookup & gal, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GasAbsLookup to XML output stream.
Parameters
os_xml XML Output stream
gal GasAbsLookup
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 90 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GasAbsLookup::f_grid, GasAbsLookup::nls_pert, GasAbsLookup::nonlinear_species, GasAbsLookup::p_grid, ArtsXMLTag::set_name(), GasAbsLookup::species, GasAbsLookup::t_pert, GasAbsLookup::t_ref, GasAbsLookup::vmrs_ref, ArtsXMLTag::write_to_stream(), and GasAbsLookup::xsec.
Referenced by xml_write_to_stream().
xml_write_to_stream() [5/18]
void xml_write_to_stream (ostream & os_xml, const GriddedField & gfield, bofstream * pbofs, const String & , const Verbosity & verbosity)
Writes the grids for gridded fields to an XML input stream.
Parameters
os_xml XML output stream
gfield GriddedField with the grids
pbofs Pointer to binary output stream. NULL in case of ASCII file.
Definition at line 191 of file xml_io_compound_types.cc.
References GriddedField::get_dim(), GriddedField::get_grid_name(), GriddedField::get_grid_type(), GriddedField::get_numeric_grid(), GriddedField::get_string_grid(), GRID_TYPE_NUMERIC, GRID_TYPE_STRING, and xml_write_to_stream().
xml_write_to_stream() [6/18]
void xml_write_to_stream (ostream & os_xml, const GriddedField1 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField1 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField1
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 256 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField::get_name(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [7/18]
void xml_write_to_stream (ostream & os_xml, const GriddedField2 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField2 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField2
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 324 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField::get_name(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [8/18]
void xml_write_to_stream (ostream & os_xml, const GriddedField3 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField3 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField3
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 392 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField::get_name(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [9/18]
void xml_write_to_stream (ostream & os_xml, const GriddedField4 & gfield, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GriddedField4 to XML output stream.
Parameters
os_xml XML Output stream
gfield GriddedField4
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 457 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GriddedField::get_name(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [10/18]
void xml_write_to_stream (ostream & os_xml, const GridPos & gpos, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes GridPos to XML output stream.
Parameters
os_xml XML Output stream
gpos GridPos
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 517 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), GridPos::fd, GridPos::idx, ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [11/18]
void xml_write_to_stream (ostream & os_xml, const IsotopeRecord & irecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes IsotopeRecord to XML output stream.
Parameters
os_xml XML Output stream
irecord IsotopeRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 590 of file xml_io_compound_types.cc.
References IsotopeRecord::Abundance(), ArtsXMLTag::add_attribute(), IsotopeRecord::HitranTag(), IsotopeRecord::JplTags(), IsotopeRecord::Mass(), IsotopeRecord::MytranTag(), IsotopeRecord::Name(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [12/18]
void xml_write_to_stream (ostream & os_xml, const Ppath & ppath, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes Ppath to XML output stream.
Parameters
os_xml XML Output stream
ppath Ppath
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 664 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), Ppath::background, Ppath::constant, Ppath::dim, Ppath::geom_tan_pos, Ppath::gp_lat, Ppath::gp_lon, Ppath::gp_p, Ppath::l_step, Ppath::los, Ppath::next_parts, Ppath::np, Ppath::nreal, Ppath::pos, ArtsXMLTag::set_name(), Ppath::tan_pos, ArtsXMLTag::write_to_stream(), xml_write_to_stream(), and Ppath::z.
xml_write_to_stream() [13/18]
void xml_write_to_stream (ostream & os_xml, const RetrievalQuantity & rq, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes RetrievalQuantity to XML output stream.
Parameters
os_xml XML Output stream
rq RetrievalQuantity
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 752 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), RetrievalQuantity::Analytical(), RetrievalQuantity::Grids(), RetrievalQuantity::MainTag(), RetrievalQuantity::Mode(), RetrievalQuantity::Perturbation(), ArtsXMLTag::set_name(), RetrievalQuantity::Subtag(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [14/18]
void xml_write_to_stream (ostream & os_xml, const ScatteringMetaData & smdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes ScatteringMetaData to XML output stream.
Parameters
os_xml XML Output stream
smdata ScatteringMetaData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 912 of file xml_io_compound_types.cc.
References ScatteringMetaData::A_projec, ArtsXMLTag::add_attribute(), ScatteringMetaData::asratio, ScatteringMetaData::d_max, ScatteringMetaData::density, ScatteringMetaData::description, ArtsXMLTag::set_name(), ScatteringMetaData::shape, ScatteringMetaData::type, ScatteringMetaData::V, ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [15/18]
void xml_write_to_stream (ostream & os_xml, const SingleScatteringData & ssdata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SingleScatteringData to XML output stream.
Parameters
os_xml XML Output stream
ssdata SingleScatteringData
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 839 of file xml_io_compound_types.cc.
References SingleScatteringData::aa_grid, SingleScatteringData::abs_vec_data, ArtsXMLTag::add_attribute(), SingleScatteringData::description, SingleScatteringData::ext_mat_data, SingleScatteringData::f_grid, SingleScatteringData::pha_mat_data, SingleScatteringData::ptype, ArtsXMLTag::set_name(), SingleScatteringData::T_grid, ArtsXMLTag::write_to_stream(), xml_write_to_stream(), and SingleScatteringData::za_grid.
xml_write_to_stream() [16/18]
void xml_write_to_stream (ostream & os_xml, const SLIData2 & slidata, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Definition at line 969 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), SLIData2::x1a, SLIData2::x2a, xml_write_to_stream(), and SLIData2::ya.
xml_write_to_stream() [17/18]
void xml_write_to_stream (ostream & os_xml, const SpeciesRecord & srecord, bofstream * pbofs, const String & name, const Verbosity & verbosity)
Writes SpeciesRecord to XML output stream.
Parameters
os_xml XML Output stream
srecord SpeciesRecord
pbofs Pointer to binary file stream. NULL for ASCII output.
name Optional name attribute
Definition at line 1031 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), SpeciesRecord::Degfr(), SpeciesRecord::Isotope(), SpeciesRecord::Name(), ArtsXMLTag::set_name(), ArtsXMLTag::write_to_stream(), and xml_write_to_stream().
xml_write_to_stream() [18/18]
void xml_write_to_stream (ostream & os_xml, const SpeciesTag & stag, bofstream * , const String & name, const Verbosity & verbosity)
Writes SpeciesTag to XML output stream.
Parameters
os_xml XML Output stream
stag SpeciesTag
name Optional name attribute
Definition at line 1125 of file xml_io_compound_types.cc.
References ArtsXMLTag::add_attribute(), SpeciesTag::Name(), ArtsXMLTag::set_name(), and ArtsXMLTag::write_to_stream().